SFDCProject/src/objects/API_Request_Log__c.object
<CustomObject>
    <fields>
        <fullName>External_Created_DateTime__c</fullName>
        <label>External Created DateTime</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Created_Date__c</fullName>
        <label>External Created Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prospect_Id__c</fullName>
        <label>Prospect Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <label>Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready To Look-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Look-up Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Look-up Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Look-up In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Response_Details__c</fullName>
        <label>Response Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>API Request Log</label>
    <nameField>
        <label>API Request Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Request Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/HomeDepotErrorLookupQueueable.cls
public class HomeDepotErrorLookupQueueable implements Queueable, Database.AllowsCallouts  {
    
  public Id apiRequestLogId {get;set;}
    
    public HomeDepotErrorLookupQueueable() {
      this(null);
    }
    
    public HomeDepotErrorLookupQueueable(Id apiRequestLogId) {
      system.debug('API ID'+apiRequestLogId);
        this.apiRequestLogId = apiRequestLogId;
    }
    
  
    public void execute(QueueableContext ctx) {
        String createdDateTime;
        String createdDate;  
        API_Request_Log__c apiReq = [select Id, Object_Name__c, Prospect_Id__c,External_Created_Date__c,External_Created_DateTime__c from API_Request_Log__c where id = :apiRequestLogId];       
        
        If(apiReq.Object_Name__c.equalsIgnoreCase('lead')){
            Lead l = [Select External_Created_Date__c,External_Created_DateTime__c,External_Sync_Batch_ID_Outbound__c from Lead where Prospect_Id__c = :apiReq.Prospect_Id__c];  
            createdDateTime = l.External_Created_DateTime__c;
        }else if (apiReq.Object_Name__c.equalsIgnoreCase('opportunity')){
            Opportunity o = [Select External_Created_Date__c,External_Created_DateTime__c,External_Sync_Batch_ID_Outbound__c from Opportunity where Prospect_Id__c = :apiReq.Prospect_Id__c];    
            createdDateTime = o.External_Created_DateTime__c;
        }
        Sf.HomeDepotSyncService.errorLogLookup(createdDateTime);
        /*if(createdDateTime != null){
           Sf.HomeDepotSyncService.errorLogLookup(createdDateTime);             
        }else{
            apiReq.Request_Status__c = 'Look-up Error'; 
            apiReq.Response_Details__c = 'External Created Date Time is not found';
            update apiReq;
        }*/
    
    }
    
}