SFDCProject/src/objects/App_Log__c.object
<CustomObject>
    <description>Generic object used to log exceptions and other information related to code or api.</description>
    <fields>
        <fullName>Action__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>If there are multiple type of actions within a module, it can be identified here.</inlineHelpText>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <inlineHelpText>This field can be used to store any external identifiers that related to the record that associated with this app log.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <inlineHelpText>Messages associated with the log.</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>The module which generated this log. This may or may not correspond to a class.</inlineHelpText>
        <label>Module</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <inlineHelpText>If this log is related to a particular Salesforce record, then that record could be specified here.</inlineHelpText>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sobject__c</fullName>
        <inlineHelpText>If this log is related to a salesforce record, that records sobject name is listed here.</inlineHelpText>
        <label>Sobject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sync Record</label>
        <referenceTo>Sync_Record__c</referenceTo>
        <relationshipLabel>App Logs</relationshipLabel>
        <relationshipName>App_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <inlineHelpText>If this log due to a request received from external system, that system could be listed here.</inlineHelpText>
        <label>System</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Type of this api log. It is upto the clients to identify the type of the log.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debug</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value3__c</fullName>
        <label>Value3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>App Log</label>
    <nameField>
        <displayFormat>API-{000000000}</displayFormat>
        <label>Api Log#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Sync_Record__c.object
<CustomObject>
    <description>Many times when a record is modified, it needs to be synced to other places and we need to capture the status of the sync status and details for analysis or troubleshooting. If a record needs to be synced to multiple places, then we would end up in creating multiple fields in source object. Also sometimes we will not be able to update the object back due to various reasons. This object helps to keep track of such records and helps update the status with details.</description>
    <fields>
        <fullName>Action__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Indicates the action which this sync job does, within the module. for ex, ContractsSync or GetAccountTitleDetails etc,</inlineHelpText>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>App_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>App Log</label>
        <referenceTo>App_Log__c</referenceTo>
        <relationshipLabel>Sync Records</relationshipLabel>
        <relationshipName>Sync_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <inlineHelpText>When we process a record and sync to external system, if that translates to an id, that could be persisted here.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <inlineHelpText>Short message associated with processing the record. In case of exceptions this would contain the exception message.</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Module to which this sync record associated with. For ex., &apos;AwsSqsSync&apos; or &apos;CoreLogicSync&apos;</inlineHelpText>
        <label>Module</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <inlineHelpText>The record to which this sync queue record tracks.</inlineHelpText>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sobject__c</fullName>
        <label>Sobject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Indicates the type of change in source records. Insert or Update or Delete</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Insert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value1__c</fullName>
        <inlineHelpText>Some times we need to store additional parameters and this field can be used to store such parameters.</inlineHelpText>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value2__c</fullName>
        <label>Value2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value3__c</fullName>
        <label>Value3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sync Record</label>
    <nameField>
        <displayFormat>SYR-{0000000000}</displayFormat>
        <label>Sync Record#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/LogzUploaderJob.cls
public class LogzUploaderJob implements Queueable, Database.AllowsCallouts {
	private static final String LogzUploaderUrl = Sf.settingsService.getString('LogzUploaderUrl', 'https://listener-4.logz.io:8071/?token=hMBMlkBoklHPLBcnRGikbHJvrQsdnJRt');
    private static final String Setting_LogzUploaderLastQueryDate = 'LogzUploaderLastQueryDate';
    private static final BaseClass utils = new BaseClass();
	private static final String[] AsyncApexfields = new String[]{
        'ApexClass.Id',
        'ApexClass.Name',
        'CompletedDate',
        'CreatedBy.Id',
        'CreatedBy.Name',
        'CreatedDate',
        'ExtendedStatus',
        'Id',
        'JobItemsProcessed',
        'JobType',
        'LastProcessed',
        'LastProcessedOffset',
        'MethodName',
        'NumberOfErrors',
        'ParentJobId',
        'Status',
        'TotalJobItems'
    };
 	
	private static final String[] AppLogFields = new String[]{
        'Action__c',
        'External_Id__c',
        'Id',
        'LastModifiedBy.Id',
        'LastModifiedBy.Name',
        'LastModifiedDate',
        'Message__c',
        'Module__c',
        'Name',
        'Record_Id__c',
        'Sobject__c',
        'Sync_Record__c',
        'System__c',
        'Type__c',
        'Value1__c',
        'Value2__c',
        'Value3__c'
    };

    public void execute(QueueableContext context) {
        DateTime newDate = DateTime.now();
        DateTime dateSinceQueried = Sf.settingsService.getDateTime(Setting_LogzUploaderLastQueryDate, DateTime.now().addDays(-7));
    	postAyncApexLogsToLogz(dateSinceQueried);
    	postAppLogsToLogz(dateSinceQueried);
        Sf.settingsService.setDateTime(Setting_LogzUploaderLastQueryDate, newDate);
    }

    public void postAyncApexLogsToLogz(DateTime dateSinceQueried) {
        postToLogz(queryJobs(dateSinceQueried), AsyncApexfields, 'AsyncApexJob', 'ExtendedStatus');
    }

    public void postAppLogsToLogz(DateTime dateSinceQueried) {
        postToLogz(queryAppLogs(dateSinceQueried), AppLogFields, 'App_Log__c', 'Message__c');
    }

    public void postToLogz(List<Sobject> sobjs, String[] fields, String type, String messageField) {
        String payload = '';
        for (Sobject sobj : sobjs) {
            JsonWriter jsonWriter = new JsonWriter();
            for(String field : fields) {
                jsonWriter.write(field, utils.getValue(sobj, field));
            }
            jsonWriter.write('org.Id', UserInfo.getOrganizationId());
            jsonWriter.write('org.Name', UserInfo.getOrganizationName());
            
            if (messageField != null) {
                //Logz recognizes this field and shows in main screen.
	            jsonWriter.write('message', utils.getValue(sobj, messageField));
            }
            jsonWriter.write('environment', utils.isSandbox()?'sandbox':'production');
            
            payload += '\n' + jsonWriter.toJson();
        }
    
        if (!String.isBlank(payload.trim())) {
            String url = LogzUploaderUrl + '&type=' + type;
            utils.httpPost(url, payload.trim(), new Map<String, String>{'Content-Type' => 'text/plain'});
        }
    }
    
    List<AsyncApexJob> queryJobs(DateTime dateSinceQueried) {
        String soql = utils.createSoql(AsyncApexfields, 'AsyncApexJob', new String[]{'CompletedDate >= :dateSinceQueried', 'CompletedDate != null'}, 'CompletedDate', null, null);
        List<AsyncApexJob> jobs = Database.query(soql + ' limit ' + Sf.settingsService.getInteger('LogzUploaderQueryLimit', 1000));
        
        if (Test.isRunningTest()) {
            jobs = Database.query(utils.createSoql(AsyncApexfields, 'AsyncApexJob'));
        }
        
        return jobs;
    }

    List<App_Log__c> queryAppLogs(DateTime dateSinceQueried) {
        String soql = utils.createSoql(AppLogFields, 'App_Log__c', new String[]{'LastModifiedDate >= :dateSinceQueried', '(Type__c = \'Error\' or Type__c = \'Exception\')'}, 'LastModifiedDate', null, null);
        return Database.query(soql + ' limit ' + Sf.settingsService.getInteger('LogzUploaderQueryLimit', 1000));
    }
}