SFDCProject/src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Appointment_Date_Time__c</fullName>
        <label>Appointment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Appointment_End_Date_Time__c</fullName>
        <label>Appointment  End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <formula>IF( ISBLANK( Opportunity__c ), TEXT(Lead__r.Channel__c ), TEXT( Opportunity__r.Channel_2__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Assigned_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event Assigned To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Appointments (Event_Assigned_To)</relationshipLabel>
        <relationshipName>Appointments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Created_Date_Time__c</fullName>
        <formula>Opportunity__r.Lead_Created_Date_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Created Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Costco_Cancellation_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Costco Cancellation Codes</label>
</CustomObject>

SFDCProject/src/objects/Costco_Lead_Org_Location_Test_Data__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Lead_Org_Id__c</fullName>
        <label>Lead Org Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Costco Lead Org Location Test Data</label>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Channel__c</fullName>
        <description>[Requested in TG-962, subtask of TG-904]</description>
        <label>Channel</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Created_Date_Time__c</fullName>
        <formula>Opportunity__r.Lead_Created_Date_Time__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Created Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposal_ID__c</fullName>
        <description>The proposal identification number.</description>
        <label>Proposal ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Purchased_Thru__c</fullName>
        <formula>TEXT(Opportunity__r.Purchased_Thru__c)</formula>
        <label>Purchased Thru</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom settings to all general settings for the appliication. These settings should be accessed via Sf.settingsService.</description>
    <fields>
        <fullName>Value1__c</fullName>
        <label>Value1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Settings</label>
</CustomObject>

SFDCProject/src/classes/CostcoSyncServiceTestClass.cls
@istest
public class CostcoSyncServiceTestClass{    
    static testmethod void CostcoSyncServiceTest(){
         insertSettings();
         String leadOrgLoc;
         Sf.settingsService.setBoolean('CostcoLeadSyncEnabled', true);        
         BaseClass base=new BaseClass();
         CostcoSyncServiceImpl cssi=new CostcoSyncServiceImpl();
         RestContext.request = new RestRequest();
         RestContext.response = new RestResponse();
         for(Costco_Lead_Org_Location_Test_Data__c cld:Costco_Lead_Org_Location_Test_Data__c.getAll().values()){
            leadOrgLoc=cld.Lead_Org_Id__c;
         }  
         if(leadOrgLoc==null){
            leadOrgLoc='0016000000ws0ZD';         
         }
         Lead lead = new Lead(FirstName='TEST',phone='1231231234',email='test33@yopmail.com',LastName='TEST Costco Ld',Company='TESTC',Lead_Type__c='Special Event',street='180 diamond st',city='San Francisco', state='CA',postalcode='94114',channel__c='Retail',custom_lead_source__c='Costco',Lead_Organization_Location_2__c=leadOrgLoc,Purchased_Thru__c='Costco');              
         //BaseClass.sendHttpRequest();
         Lead lead2=new Lead(lastname='Test2',company='Test');
         List<Lead> list_Lead=new List<Lead>();
         list_Lead.add(lead);
         list_Lead.add(lead2);
         insert list_Lead;
         Test.StartTest();        
         Map<String, String> cPar= cssi.createNewLeadRequestParms(lead,'','','');
         cssi.createUpdateCustomerRequestParms(lead);
         cssi.retrieveLeads();
         xmlReader xmlread=new xmlReader('<root><lead.id></lead.id></root>');
         cssi.createLeadUsingLeadApi(xmlread);  
         cssi.isCostcoLeadChanged(lead,lead);
         List<id> ids=new List<id>();
         ids.add(lead.id);    
         base.enqueueJobWithCheck(new CostcoLeadSyncJob((ids)));   
         SendLeadToCosctoButton.sendLead(lead.id);                             
         Test.StopTest();
         lead.status='Closed Lost'; 
         lead.purchased_thru__c=null;
         update lead;
                  
    }  
    static testmethod void TestMockWS(){
         insertSettings();
         CostcoSyncServiceImpl cssi=new CostcoSyncServiceImpl();
         Lead lead2=new Lead(lastname='Test2',company='Test');
         insert lead2;
         Test.StartTest();  
         Map<String,String> cPar=new Map<String,String>();        
          // Set mock callout class 
         Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());   
         cssi.costcoHttpPost('add_lead',cPar);     
         cssi.costcoHttpRequest('POST','add_lead',cPar);
         cssi.acknowledgeLead((String)lead2.id);
         cssi.retrieveLeads();
         cssi.getNewLeadIds();
         try{
         cssi.getAdcodeId();
         }
         catch(exception e){}
         cssi.handleAppointmentsTrigger();
         cssi.updateLeadsEstimateDate(new List<id>());
         cssi.handleProposalsTrigger();
         cssi.updateLeadsQuoteAmount(new List<id>());
         cssi.cancelLeadRequestParms(lead2,'1134');
         cssi.isCostcoCancelLeadChanged(lead2,lead2);       
         CostcoLeadSyncJob cs=new CostcoLeadSyncJob();                  
         Test.StopTest();
    } 
    static testmethod void TestOpportunity(){
    insertSettings();
    Opportunity optyObj1 = TestPRMLibrary.insertOpportunity('ResidentialAccount-3', 'Residential',
                                                                'ResOpty-3', 'Platinum');
        optyObj1.stageName='9. Closed Lost';
        optyObj1.Opportunity_Status__c='Competitor';
        optyObj1.External_Id__c='12324';
        optyObj1.Channel_2__c='Retail';
        optyObj1.Lead_Source_2__c='Costco';
        optyObj1.Lead_Created_Date_Time__c=system.now();
        update optyObj1;
        Proposal__C proposalObj = new Proposal__C();
        proposalObj.Name = 'Proposal-1';
        proposalObj.Opportunity__c = optyObj1.Id;
        proposalObj.Upfront_Payment__c = 1000;
        proposalObj.Proposal_ID__c = 2441242;
        proposalObj.System_Size_STC_DC__c = 1;
        proposalObj.Mode_Name__c = 'Mode-1';
        proposalObj.Date_Issued__c =  date.today();
        proposalObj.Sales_Rep_Email__c = 'test@gmail.com';    
        insert proposalObj;
        Contact contactObj1 = TestPRMLibrary.insertContact('PRMTestAccount1', 
                      PRMLibrary.PARTNER, 
                      'PRMTestLastName1',
                      'prmcontact1@sunrun.com');
        Appointment__c appointment=new Appointment__c();
        appointment.Event_Assigned_To__c=contactObj1.id;
        appointment.opportunity__c=optyObj1.id;
        appointment.Appointment_Date_Time__c=system.now();
        appointment.Appointment_End_Date_Time__c=system.now();            
        insert appointment;
        CostcoSyncServiceImpl cssi=new CostcoSyncServiceImpl();
        cssi.cancelLeadRequestParms(optyObj1,'1134');  
        cssi.updateLeadEstimateDateDummyRequestParms(proposalObj,'','');
        //cssi.updateLeadEstimateDateRequestParms(appointment,-2,4);
        CostcoOpptySyncJob co=new CostcoOpptySyncJob();
        CostcoLeadUpdateQuoteAmountJob cupq=new CostcoLeadUpdateQuoteAmountJob();
        CostcoLeadUpdateEstimateDateJob cued=new CostcoLeadUpdateEstimateDateJob();      
        
    }
    static testmethod void TestDisableCostco(){
        CostcoSyncServiceImpl cssi=new CostcoSyncServiceImpl();
        insert new Settings__c(Name='CostcoLeadSyncEnabled', Value1__c='false');
        cssi.syncOpptys(new List<id>{});
        cssi.updateLeadsEstimateDate(new List<id>{});
        cssi.updateLeadsQuoteAmount(new List<id>{});
        cssi.syncLeads(new list<id>{});
    }
     public static void insertSettings() {
        insert new Settings__c(Name='CostcoSyncServiceName', Value1__c='Solar Panel');
        insert new Settings__c(Name='CostcoSyncUserId', Value1__c='fcole');
        insert new Settings__c(Name='CostcoSyncPassword', Value1__c='Password1');
        insert new Settings__c(Name='CostcoSyncUrl', Value1__c='https://costcous.centah.com/xml.php');
        insert new Settings__c(Name='CostcoSyncAdcodeName', Value1__c='Brochure at Warehouse'); 
        insert new Settings__c(Name='CostcoLeadSyncEnabled', Value1__c='true');
        insert new Costco_Cancellation_Codes__c(name='lead123',key__c='Closed Lost',value__c='1134');
        insert new Costco_Cancellation_Codes__c(name='oppty123',key__c='9. Closed Lost+Competitor',value__c='1134');
     }
}