SFDCProject/src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Appointment_Date_Time__c</fullName>
        <label>Appointment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Appointment_Description__c</fullName>
        <label>Appointment Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Appointment_End_Date_Time__c</fullName>
        <label>Appointment  End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Appointment_Type__c</fullName>
        <label>Appointment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Visit Follow up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call Follow up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Audit Revisit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Field Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1hr Field Service visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2hr Field Service visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4hr Field Service visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8hr Field Service visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cancellation_Reason__c</fullName>
        <inlineHelpText>Why was the appointment not completed?</inlineHelpText>
        <label>Cancellation Reason</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Customer Rescheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Rep No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Rep Rescheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fake / Duplicate Appointment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Assigned_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Event Assigned To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Appointments (Event_Assigned_To)</relationshipLabel>
        <relationshipName>Appointments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Appointment Set</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment in Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Appointment_Type__c.object
<CustomObject>
    <fields>
        <fullName>Appointment_Type__c</fullName>
        <label>Appointment Type</label>
        <picklist>
            <picklistValues>
                <fullName>1hr Field Service visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2hr Field Service visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4hr Field Service visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8hr Field Service visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Visit Follow up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call Follow up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Audit Revisit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Field Service</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Appointment Type</label>
    <nameField>
        <displayFormat>ATP-{00000}</displayFormat>
        <label>Appointment Type</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/Trg_populate_events_aft_ins_aft_up_Test.cls
@isTest
private class Trg_populate_events_aft_ins_aft_up_Test {
    
    private static testmethod void test(){
        Account acc = BaseClassTest.createTestAccount();
        User us = New User(LastName='Smith',Alias ='John',Email='smith@yopmail.com',Username='smith@yopmail.com',Profileid ='00e60000000nGtn',EmailEncodingKey ='UTF-8', LocaleSidKey= 'en_US',TimeZoneSidKey= 'GMT',LanguageLocaleKey = 'en_US');
        insert us;
        Opportunity opp = new Opportunity(Name='TestOpportunity',StageName='Prospecting',salesrep__c=us.id,Accountid =acc.Id);
        insert opp;        
        Contact con = new Contact(LastName='Smith',Email='smith@yopmail.com',AccountId =acc.Id,Title='Sales Rep',Job_Function__c='Sales',SunRun_User__c=us.Id);
        insert con;
        Appointment__c app = new Appointment__c(opportunity__c = opp.Id ,Appointment_Date_Time__c=system.today(),Appointment_End_Date_Time__c=system.today(),Event_Assigned_To__c=con.Id,Status__c='Appointment Set',Appointment_Description__c='This is a site Visit');
        insert app;

        event ev = [Select AppointmentId__c from event where AppointmentId__c=:app.Id];
        system.assertEquals(app.Id,ev.AppointmentId__c);
        
        app.Appointment_Description__c = 'Updated appointment';
        update app;
        app.Status__c = 'Appointment Conmplete';
        update app;
        app.Appointment_Type__c = 'Site Audit';
        update app;
        
        app.Status__c = 'Appointment Cancelled';
        app.Cancellation_Reason__c = 'Customer Not Interested';
        update app;
        
    }
}