SFDCProject/src/objects/Asset_Information__c.object
<CustomObject>
    <description>Store the asset information</description>
    <fields>
        <fullName>Count__c</fullName>
        <description>Store the number of components</description>
        <label>Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <description>Store the Manufacturer of the component</description>
        <label>Manufacturer</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <description>Store the Model of the component</description>
        <label>Model</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProposalName__c</fullName>
        <label>Proposal Name</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Asset Informations</relationshipLabel>
        <relationshipName>Asset_Informations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of the component</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Inverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Microinverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Asset Information</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Asset Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Create_Service_Contract_Proposal_Stage__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Create Service Contract Proposal Stage</label>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Agreement_Term_Years__c</fullName>
        <label>Agreement Term (Years)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <description>The type of agreement proposed to the customer for Power Plan.</description>
        <label>Agreement Type</label>
        <picklist>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Owned - Full Upfront</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Owned - Bank Financed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Array_1_No_of_Panels__c</fullName>
        <description>Number of panels in Array 1</description>
        <label>Array 1 No. of Panels</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Array_1_Panel_Type__c</fullName>
        <description>The first array of panels on the given system.</description>
        <inlineHelpText>The first array of panels on the given system.</inlineHelpText>
        <label>Array 1 Panel Type</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Array_2_No_of_Panels__c</fullName>
        <description>Number of panels in the second array.</description>
        <label>Array 2 No. of Panels</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Array_2_Panel_Type__c</fullName>
        <description>The second array of panels used on the system.</description>
        <inlineHelpText>The second array of panels used on the system.</inlineHelpText>
        <label>Array 2 Panel Type</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Array_3_No_of_Panels__c</fullName>
        <description>Number of panels in array 3.</description>
        <label>Array 3 No. of Panels</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Array_3_Panel_Type__c</fullName>
        <description>The third array of panels on the system</description>
        <inlineHelpText>The third array of panels on the system</inlineHelpText>
        <label>Array 3 Panel Type</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Array_4_No_of_Panels__c</fullName>
        <description>Number of panels in array 4.</description>
        <label>Array 4 No. of Panels</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Array_4_Panel_Type__c</fullName>
        <description>Type of panels for array 4.</description>
        <label>Array 4 Panel Type</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Array_5_No_of_Panels__c</fullName>
        <label>Array 5 No. of Panels</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Array_5_Panel_Type__c</fullName>
        <label>Array 5 Panel Type</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Array_6_No_of_Panels__c</fullName>
        <label>Array 6 No. of Panels</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Array_6_Panel_Type__c</fullName>
        <label>Array 6 Panel Type</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Base_Lease_Payment_Amount__c</fullName>
        <label>Base Lease Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Buyout_per_Watt__c</fullName>
        <label>Buyout per Watt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EPC_Price__c</fullName>
        <description>The turnkey price to be paid to the installer.</description>
        <inlineHelpText>The turnkey price to be paid to the installer.</inlineHelpText>
        <label>EPC Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>EPC_Price_per_Watt__c</fullName>
        <label>EPC Price per Watt</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Est_Yr_1_Generation__c</fullName>
        <label>Est Yr 1 Generation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Rebate_Amount__c</fullName>
        <label>Estimated Rebate Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Full_System_Cost__c</fullName>
        <label>Full_System_Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Local_Rebate__c</fullName>
        <description>The amount for any local rebate, where applicable.</description>
        <label>Local Rebate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prepay_Amount__c</fullName>
        <label>Prepay Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prepay_Discount_Rate__c</fullName>
        <label>Prepay Discount Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Prepay_payment_for_RECs__c</fullName>
        <label>Prepay payment for RECs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Prepay_payment_for_electricity__c</fullName>
        <label>Prepay payment for electricity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_Per_kWh__c</fullName>
        <description>The cost of each kilowatt hour generated by the proposed system to the customer.</description>
        <inlineHelpText>The cost of each kWh generated by the proposed system to the customer.</inlineHelpText>
        <label>Price Per kWh</label>
        <precision>8</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Production_Estimate_Source_Adjust_Ratio__c</fullName>
        <label>Production Estimate Source Adjust Ratio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Production_Estimate_Source__c</fullName>
        <description>The source of information which generated the first year generation estimate</description>
        <inlineHelpText>The source of information which generated the first year generation estimate</inlineHelpText>
        <label>Production Estimate Source</label>
        <picklist>
            <picklistValues>
                <fullName>EPBB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PVWatts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunRun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sunrun_Credit_Status__c</fullName>
        <label>Sunrun Credit Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year_1_monthly_payment__c</fullName>
        <label>Year 1 monthly payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Yr_1_Avoided_Power_Cost__c</fullName>
        <label>Yr 1 Avoided Power Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_CreateServiceContractController.cls
@isTest(SeeAllData=true)
public class Test_CreateServiceContractController{

    static
    {
        //Create_Service_Contract_Proposal_Stage__c cscps1 = new Create_Service_Contract_Proposal_Stage__c(Name = 'Created');
        //insert cscps1;
    }


    //Working
        
    public static TestMethod void Test_CreateServiceContractController()
    {
            //DataSetup  
        Account a = new Account(name='Test Acct1');
        insert a;
        
        Opportunity oppty = new Opportunity();
        oppty.AccountId = a.Id;
        oppty.Name = 'NewCC Test';
        oppty.StageName = 'Qualified';
        oppty.CloseDate = Date.Today().addDays(18);
        insert oppty;
        //
		Proposal__c proposal = UnitTest_ServiceContractUtil.createProposal(oppty.Id);
		insert proposal;        
        
        ApexPages.StandardController controller = new ApexPages.StandardController(proposal);
        CreateServiceContractController serviceContractController = new CreateServiceContractController(controller);
        PageReference page = serviceContractController.create();
        //get object id from page reference
        String objectId = page.getURL().right(page.getURL().length() - 1);
        
        ServiceContract serviceContract = [select Id, Name, Yr_1_Avoided_Power_Cost__c, Proposal__c from ServiceContract where Id = :objectId];

        
        // Added by Ankita
        proposal.Sunrun_Credit_Status__c = null;    
        update proposal;
        
        ApexPages.StandardController controller1 = new ApexPages.StandardController(proposal);
        CreateServiceContractController serviceContractController1 = new CreateServiceContractController(controller1); 
        PageReference page1 = serviceContractController1.create();
        // 
            
    }    


    public static TestMethod void Test_CreateServiceContractControllerWithAssetInformation()
    {
            //DataSetup  
        Account a = new Account(name='Test Acct1');
        insert a;
        
        Opportunity oppty = new Opportunity();
        oppty.AccountId = a.Id;
        oppty.Name = 'NewCC Test';
        oppty.StageName = 'Qualified';
        oppty.CloseDate = Date.Today().addDays(18);
        insert oppty;
        //
		Proposal__c proposal = UnitTest_ServiceContractUtil.createProposal(oppty.Id);
		insert proposal;
		        
        Asset_Information__c assetInformation = new Asset_Information__c(Count__c = 5, Type__c = 'Panel', Manufacturer__c='Test Manu', Model__c = 'Test Model', ProposalName__c = proposal.Id);
        insert assetInformation;
                
        ApexPages.StandardController controller = new ApexPages.StandardController(proposal);
        CreateServiceContractController serviceContractController = new CreateServiceContractController(controller);
        PageReference page = serviceContractController.create();
    }    


    //Working
    public static TestMethod void Test_CreateServiceContractControllerMultipleTimes()
    {
            //DataSetup  
        Account a = new Account(name='Test Acct1');
        insert a;
        
        Opportunity oppty = new Opportunity();
        oppty.AccountId = a.Id;
        oppty.Name = 'NewCC Test';
        oppty.StageName = 'Qualified';
        oppty.CloseDate = Date.Today().addDays(18);
        insert oppty;
        //
		Proposal__c proposal = UnitTest_ServiceContractUtil.createProposal(oppty.Id);
		insert proposal;
		        
        Asset_Information__c assetInformation = new Asset_Information__c(Count__c = 5, Type__c = 'Panel', Manufacturer__c='Test Manu', Model__c = 'Test Model', ProposalName__c = proposal.Id);
        insert assetInformation;
                
        ApexPages.StandardController controller = new ApexPages.StandardController(proposal);
        CreateServiceContractController serviceContractController = new CreateServiceContractController(controller);
        PageReference page = serviceContractController.create();
        //get object id from page reference
        String objectId = page.getURL().right(page.getURL().length() - 1);
        
        ServiceContract serviceContract = [select Id, Name, Yr_1_Avoided_Power_Cost__c, Proposal__c from ServiceContract where Id = :objectId];
		
		Test.startTest();

        ApexPages.StandardController controller2 = new ApexPages.StandardController(proposal);
        CreateServiceContractController serviceContractController2 = new CreateServiceContractController(controller2);
        PageReference page2 = serviceContractController2.create();
        Test.stopTest();

    }        

    //Working method ...    
    public static TestMethod void Test_CreateServiceContractControllerWithInvalidProposalStatus()
    {
            //DataSetup  
        Account a = new Account(name='Test Acct1');
        insert a;
        
        Opportunity oppty = new Opportunity();
        oppty.AccountId = a.Id;
        oppty.Name = 'NewCC Test';
        oppty.StageName = 'Qualified';
        oppty.CloseDate = Date.Today().addDays(18);
        insert oppty;
        //
		Proposal__c proposal = UnitTest_ServiceContractUtil.createProposal(oppty.Id);
		insert proposal;        
        Asset_Information__c assetInformation = new Asset_Information__c(Count__c = 5,  Manufacturer__c='Test Manu', Model__c = 'Test Model', ProposalName__c = proposal.Id,Type__c = ServiceContractUtil.ASSET_TYPE_METER );
        insert assetInformation;
                
        ApexPages.StandardController controller = new ApexPages.StandardController(proposal);
        CreateServiceContractController serviceContractController = new CreateServiceContractController(controller);
        PageReference page = serviceContractController.create();
	}       
		// Added By Ankita
    public static TestMethod void Test_CreateServiceContractControllerWithIdStage()
    {
            //DataSetup  
        Account a = new Account(name='Test Acct1');
        insert a;
        
        Opportunity oppty = new Opportunity();
        oppty.AccountId = a.Id;
        oppty.Name = 'NewCC Test';
        oppty.StageName = 'Qualified';
        oppty.CloseDate = Date.Today().addDays(18);
        insert oppty;
        //
		Proposal__c proposal = UnitTest_ServiceContractUtil.createProposal(oppty.Id);
		insert proposal;
        
        proposal.Array_1_Panel_Type__c = 'TestPanelType1';
        proposal.Array_1_No_of_Panels__c = 1;
        proposal.Array_2_Panel_Type__c = 'TestPanelType2';
        proposal.Array_2_No_of_Panels__c = 2;
        proposal.Array_3_Panel_Type__c = 'TestPanelType3';
        proposal.Array_3_No_of_Panels__c = 3;
        proposal.Array_4_Panel_Type__c = 'TestPanelType4';
        proposal.Array_4_No_of_Panels__c = 4;
        proposal.Array_5_Panel_Type__c = 'TestPanelType5';
        proposal.Array_5_No_of_Panels__c = 5;
        proposal.Array_6_Panel_Type__c = 'TestPanelType6';
        proposal.Array_6_No_of_Panels__c = 6;    
        proposal.Name = 'TestProposal';  
        proposal.Agreement_Term_Years__c = 15;
        proposal.Agreement_Type__c= 'Test Agreement Type';
        proposal.Base_Lease_Payment_Amount__c = 101;
        proposal.Buyout_per_Watt__c = 102;
        proposal.EPC_Price__c = 103;
        proposal.EPC_price_per_watt__c = 104;
        proposal.Estimated_Rebate_Amount__c = 105;
        proposal.Est_Yr_1_Generation__c = 106;
        proposal.Full_System_cost__c = 107;
        proposal.Local_Rebate__c = 108;
        proposal.Prepay_Amount__c = 109;
        proposal.Prepay_Discount_Rate__c = 10;
        proposal.Prepay_payment_for_electricity__c = 110;
        proposal.Prepay_payment_for_RECs__c = 111;
        proposal.Price_per_kWh__c = 112;
        proposal.Production_Estimate_Source__c = 'Test Production Estimate Source';
        proposal.Production_Estimate_Source_Adjust_Ratio__c = 200;
        proposal.Product_Type__c = 'Test Product Type';
        proposal.Upfront_Payment__c = 4000;
        proposal.Year_1_monthly_payment__c =  5000;
        proposal.Yr_1_Avoided_Power_Cost__c = 6000;
        proposal.Sunrun_Credit_Status__c = EDPUtil.CREDIT_APPROVED;
        update proposal;     
        
         
        CreateServiceContractController serviceContractController = new CreateServiceContractController(proposal.Id,proposal.Stage__c);   
        PageReference page = serviceContractController.ReturnToProposal();
        String rv = serviceContractController.createServiceContract();
        CreateServiceContractController serviceContractController1 = new CreateServiceContractController();   
        String rv1 = serviceContractController1.createServiceContract();
            
        proposal.Sunrun_Credit_Status__c = null;    
        update proposal;
        
        CreateServiceContractController serviceContractController2 = new CreateServiceContractController(proposal.Id,proposal.Stage__c); 
        String rv2 = serviceContractController2.createServiceContract();
          
    }
}