SFDCProject/src/objects/Asset_Information__c.object
<CustomObject>
    <description>Store the asset information</description>
    <fields>
        <fullName>Count__c</fullName>
        <description>Store the number of components</description>
        <label>Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProposalName__c</fullName>
        <label>Proposal Name</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Asset Informations</relationshipLabel>
        <relationshipName>Asset_Informations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <description>Populated on Asset when a Proposal is created. Added as part of BSKY-6079 07/10/2015</description>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Asset Information</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Asset Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Contract_Pricing__c.object
<CustomObject>
    <description>Created as part of BSKY-6079 07/10/2015</description>
    <fields>
        <fullName>Asset_Type__c</fullName>
        <label>Asset Type</label>
        <picklist>
            <picklistValues>
                <fullName>Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Storage System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Microinverter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Contract Pricing</relationshipLabel>
        <relationshipName>Contract_Pricing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tax_on_Installation__c</fullName>
        <label>Tax on Installation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contract Pricing</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>Contract Pricing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Installation_Price__c</fullName>
        <label>Installation Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_on_Installation__c</fullName>
        <description>Added for BSKY-6079</description>
        <label>Tax on Installation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/ContractPricingUtil.cls
public class ContractPricingUtil {
    
    
    public static List<Asset_Information__c> getAssetInformationForProposalForPricing(String fieldsString, Id proposalId)
    {
        String assetInformationSelectStatement = 'select Id, Name' + fieldsString + ' from Asset_Information__c where ProposalName__r.Id = \'' + proposalId + '\'';      
        return (List<Asset_Information__c>)Database.query(assetInformationSelectStatement);          
    } 
    
    
    public static Contract_Pricing__c createContractPricing(Set<String> assetInformationFields, ServiceContract serviceContract, Asset_Information__c assetInformation)
    {
        Contract_Pricing__c contractPricing = new  Contract_Pricing__c (Service_Contract__c = serviceContract.Id);
        
        for (String assetInformationField: assetInformationFields) {
            String contractPricingField = AssetInfoToContractPricingGenerationUtil.getAssetInformationFieldMapTo(assetInformationField);
            Object assetInformationFieldValue = assetInformation.get(assetInformationField);
            Object contractPricingFieldValue = contractPricing.get(contractPricingField);
            if(assetInformationFieldValue  == null)
                contractPricing.put(contractPricingField, null);
            else
                contractPricing.put(contractPricingField, assetInformationFieldValue);
        }
   
        return contractPricing;
    }
    
     public static Contract_pricing__c createInstallationPricing( ServiceContract parentServiceContract, proposal__c proposalobj )
    {
     
        return new Contract_Pricing__c(Service_Contract__c = parentServiceContract.Id, Asset_Type__c = 'Installation', 	Total_Price__c = proposalobj.Installation_Price__c , Tax_on_Installation__c = proposalObj.Tax_on_Installation__c,  Count__c = 1 );

    }

}