SFDCProject/src/objects/Async_Process_Queue__c.object
<CustomObject>
    <description>Asynchronous Process Requests queue</description>
    <fields>
        <fullName>Request_End_Time__c</fullName>
        <description>End Date/Time for Asynchronous request processing.</description>
        <label>Request End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request_Start_Time__c</fullName>
        <description>Start Date/Time for Asynchronous request processing.</description>
        <label>Request Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <description>Asynchronous Request Status</description>
        <label>Request Status</label>
        <picklist>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Response_Details__c</fullName>
        <label>Response Details</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Async Process Queue</label>
    <nameField>
        <label>Async Process Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Async Process Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/leadUpdateLastClickQueueable.cls
public class leadUpdateLastClickQueueable extends BaseClass implements Queueable{

    public Set<Id> recIdSet {get;set;}
    public Set<Id> asyncReqIdSet {get;set;}
    
    public leadUpdateLastClickQueueable() {
        this(null, null);
    }
    
    public leadUpdateLastClickQueueable(Set<Id> recIdSet, Set<Id> asyncReqIdSet) {
        this.recIdSet = recIdSet;
        this.asyncReqIdSet = asyncReqIdSet; 
    }
      
    public void execute(QueueableContext ctx) {
        DateTime reqStartTime = Datetime.now(); 
         
        List<Async_Process_Queue__c> asyncReqList = [select Id, Request_Status__c, Response_Details__c, Request_Start_Time__c, Request_End_Time__c  
                                                       from Async_Process_Queue__c
                                                      where Id in :asyncReqIdSet];
        if(!recIdSet.isEmpty()){
            try{
                LeadDeDupServiceImpl.updateLastClickForDups(recIdSet, 'Lead');  
                LeadDeDupServiceImpl.updateAsyncProcessQueueRec(asyncReqList, reqStartTime, 'Success', 'Last Click for duplicate leads updated successesfully');

                String jobID = enqueueJobWithCheck(new opptyUpdateLastClickQueueable(recIdSet, asyncReqIdSet));
                if(jobID == null){
                    System.debug('Update Last Click request can not be submitted');
                    LeadDeDupServiceImpl.updateAsyncProcessQueueRec(asyncReqList, reqStartTime, 'Error', 'Failed to invoke opptyUpdateLastClickQueueable');
                }

            }catch(Exception e){
                String responseDetails = 'Last Click for duplicate leads update failed with Exception' + e;
                LeadDeDupServiceImpl.updateAsyncProcessQueueRec(asyncReqList, reqStartTime, 'Error', responseDetails);

                String jobID = enqueueJobWithCheck(new opptyUpdateLastClickQueueable(recIdSet, asyncReqIdSet));
                if(jobID == null){
                   System.debug('Update Last Click request can not be submitted');
                    LeadDeDupServiceImpl.updateAsyncProcessQueueRec(asyncReqList, reqStartTime, 'Error', 'Failed to invoke opptyUpdateLastClickQueueable');
                }

            }//end Catch

        }//End-if
        
    }//End Execute    

}