SFDCProject/src/objects/Contact_Preferences__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Preferences</relationshipLabel>
        <relationshipName>Contact_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Routing__c</fullName>
        <label>Lead Routing</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contact Preferences</label>
    <nameField>
        <displayFormat>CP-{000}</displayFormat>
        <label>Contact Preferences Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/UnitTest_Batch_LeadDistributionLogic.cls
@isTest(SeeAllData=true)
public with sharing class UnitTest_Batch_LeadDistributionLogic {
	static testmethod void UnitTest_Batch_LeadDistributionLogic(){
            Test.starttest();             
            Lead l=new Lead(lastname='TEst',company='TEst',channel__c='Event',Field_marketing_branch__c='TEst');
            insert l;
            List<Contact_Preferences__c> ContactPreferenceList=new List<Contact_Preferences__c>([select id from Contact_Preferences__c where contact__r.email=:userinfo.getUserEmail() and Lead_Routing__c='No']);
            if(!ContactPreferenceList.isempty()){
            	delete ContactPreferenceList;
            }           
            Batch_LeadDistributionLogic  batch=new Batch_LeadDistributionLogic();          
            ID batchprocessid =database.executeBatch(batch,10);
            String chron = '0 0 23 * * ?';        
         	system.schedule('Test Sched', chron, batch);
            Test.stopTest();
    }
}