SFDCProject/src/objects/CustomerCreditAutomationInfo__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Field_Value__c</fullName>
        <label>Field Value</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Customer Credit AutomationInfo</label>
</CustomObject>

SFDCProject/src/objects/Opportunity_Email_Status__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Days_In_Past_Limit__c</fullName>
        <label>No Of Days In Past Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Email Status</label>
</CustomObject>

SFDCProject/src/objects/Sync_Record__c.object
<CustomObject>
    <description>Many times when a record is modified, it needs to be synced to other places and we need to capture the status of the sync status and details for analysis or troubleshooting. If a record needs to be synced to multiple places, then we would end up in creating multiple fields in source object. Also sometimes we will not be able to update the object back due to various reasons. This object helps to keep track of such records and helps update the status with details.</description>
    <fields>
        <fullName>Action__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Indicates the action which this sync job does, within the module. for ex, ContractsSync or GetAccountTitleDetails etc,</inlineHelpText>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <inlineHelpText>Short message associated with processing the record. In case of exceptions this would contain the exception message.</inlineHelpText>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Module to which this sync record associated with. For ex., &apos;AwsSqsSync&apos; or &apos;CoreLogicSync&apos;</inlineHelpText>
        <label>Module</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <inlineHelpText>The record to which this sync queue record tracks.</inlineHelpText>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The status of the sync.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Be Synced</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <inlineHelpText>Any status that can be specified by the job specific logic. This is usually applicable if main status is Sync Not Applicable.</inlineHelpText>
        <label>Sub Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sync Record</label>
    <nameField>
        <displayFormat>SYR-{0000000000}</displayFormat>
        <label>Sync Record#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/SanthoshTempTestDoNotPushToProd.cls
@IsTest
public class SanthoshTempTestDoNotPushToProd {
    private static BaseClass utils = new BaseClass();
	private static BaseAwsService awsService = new BaseAwsService();
    private static FlexibleCalloutMock mock = new FlexibleCalloutMock(200, '');

	testmethod public static void testContractsTrigger() {
		insertSettings();
        
		Account acctWithQueue = new Account(Name='Foo', RecordTypeId=utils.getRecordTypeId('Account', 'Partner'), 
			Sqs_Queue_Name__c='Test', BillingCity='Dublin',
			Office_Location__c  = 'Headquarters',
			Stage__c = 'Confirmed',
			Active__c  = true);
        insert acctWithQueue;

		Account acctWoQueue = new Account(Name='Foo', RecordTypeId=utils.getRecordTypeId('Account', 'Partner'), 
			BillingCity='Dublin',
			Office_Location__c  = 'Headquarters',
			Stage__c = 'Confirmed',
			Active__c  = true);
        insert acctWoQueue;

        Opportunity opty1 = new Opportunity(Name='Test', StageName='Stage', CloseDate=Date.today());
        opty1.Lead_Gen_Partner__c = acctWithQueue.id;
        opty1.Sales_Partner__c = acctWithQueue.id;
        opty1.Partner_for_Lead_Passing__c = acctWithQueue.id;
        insert opty1;
        
        Opportunity opty2 = new Opportunity(Name='Test', StageName='Stage', CloseDate=Date.today());
        opty2.Lead_Gen_Partner__c = acctWoQueue.id;
        opty2.Sales_Partner__c = acctWoQueue.id;
        opty2.Partner_for_Lead_Passing__c = acctWoQueue.id;
        insert opty2;

        //With sync disabled, insert contract and it should not create sync records.
        ServiceContract contract = new ServiceContract(Opportunity__c=opty1.id);
        AwsSyncServiceImpl.recordsProcessedInThisTxn.clear();
        insert contract;
		System.assertEquals(0, querySyncRecords(contract.id).size());
		
		//Enable sync and then insert contract associated with account which doens't have queue
		//and ensure that sync should not happen.
		Sf.settingsService.setBoolean('AwsSqsContractsSyncEnabled', true);
        contract = new ServiceContract(Opportunity__c=opty2.id);
        AwsSyncServiceImpl.recordsProcessedInThisTxn.clear();
        insert contract;
		System.assertEquals(0, querySyncRecords(contract.id).size());
	
		//insert a contract and see that sync record created
		Sf.settingsService.setBoolean('AwsSqsContractsSyncEnabled', true);
        contract = new ServiceContract(Opportunity__c=opty1.id);
        AwsSyncServiceImpl.recordsProcessedInThisTxn.clear();
        insert contract;
		System.assertEquals(1, querySyncRecords(contract.id).size());
		delete querySyncRecords(contract.id);

        //update a contract with non-eligible field and see that sync record not created
		contract.Opportunity__c = opty1.id;
        contract.Agreement_Type__c  = 'Some Value';
        AwsSyncServiceImpl.recordsProcessedInThisTxn.clear();
        update contract;
		System.assertEquals(0, querySyncRecords(contract.id).size());

        //update a contract with eligible field and see that sync record not created
        contract.Status__c = 'Some new updated value';
        AwsSyncServiceImpl.recordsProcessedInThisTxn.clear();
        update contract;
		System.assertEquals(1, querySyncRecords(contract.id).size());
    }
   
    public static void insertSettings() {
        Sf.settingsService.setString('AwsAccessKey', 'accesskey'); 
        Sf.settingsService.setString('AwsSecretKey', 'secretkey'); 
        Sf.settingsService.setString('AwsSqsUrl', 'https://sqs.us-east-1.amazonaws.com/{QueueName}'); 
        Sf.settingsService.setString('AwsSqsLeadsSyncTriggerFields', 'Lead_Status__c,FirstName'); 
        Sf.settingsService.setString('AwsSqsOptysSyncTriggerFields', 'StageName,AccountId'); 
        Sf.settingsService.setString('AwsSqsAccountsSyncTriggerFields', 'Name'); 
        Sf.settingsService.setString('AwsSqsContactsSyncTriggerFields', 'FirstName'); 
        Sf.settingsService.setString('AwsSqsContractsSyncTriggerFields', 'Status__c '); 
        Sf.settingsService.setString('AwsSqsProposalsSyncTriggerFields', 'Status__c'); 
         
        //This is rquired as some opty trigger is looking for.
       	insert new Opportunity_Email_Status__c(Name='Site Audit Schedule', No_Of_Days_In_Past_Limit__c=5);
        insert new Opportunity_Email_Status__c(Name='Site Audit Complete', No_Of_Days_In_Past_Limit__c=5);

        //These are required to insert credit record
        insert new CustomerCreditAutomationInfo__c(Name='FICO_PASS', Field_Value__c='600');
        insert new CustomerCreditAutomationInfo__c(Name='FICO_FAIL', Field_Value__c='400');
        insert new CustomerCreditAutomationInfo__c(Name='FICO_CPASS', Field_Value__c='700');

        //When testing the aws sync, it always threw error cannot make
        //outbound call when uncommitted work is pending, even though
        //actual execution is guarded by Test start/stop which should
        //start a new tx. So end up bypassing the http call with mock
        //directly.
        BaseClass.testParams.put('HttpCalloutMock', mock);
   }
	
    public static Sync_Record__c querySyncRecord(Id syncRecordId) {
        return [select Id, Module__c, Action__c, Status__c, Sub_Status__c, Message__c from Sync_Record__c where Id = :syncRecordId limit 1];
    }

    public static List<Sync_Record__c> querySyncRecords(String sobjId) {
        return [select Id, Module__c, Action__c, Message__c from Sync_Record__c where Record_Id__c = :sobjId];
    }
}