SFDCProject/src/objects/Customer_Credit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Credit</relationshipLabel>
        <relationshipName>Customer_Credit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <label>Approved</label>
        <picklist>
            <picklistValues>
                <fullName>Passed Credit Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Pass &amp; signed up for ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prepaid: Full Payment received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Approval from partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approval Revoked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Home - Guarantee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPASS HI Credit criteria met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Conditional_Approval_Amount__c</fullName>
        <label>Conditional Approval Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Conditional_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conditional Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Credit</relationshipLabel>
        <relationshipName>Customer_Credit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Email__c</fullName>
        <externalId>true</externalId>
        <label>Customer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Date_Pulled__c</fullName>
        <label>Date Pulled</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <description>The date SunRun Submitted the credit check request to LeaseDimensions</description>
        <label>Date Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pending_Notes__c</fullName>
        <label>Pending Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pending_Reason__c</fullName>
        <label>Pending Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Cannot cross out or write on contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot verify sig. need printed name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete Conditional Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing pages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing payment method</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing sales rep signature or ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPASS: need to sign up for ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPASS Prepaid: need Full Payment or CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired credit check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed cr, need cr for other homeowner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major change order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minor change order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing sig. of homeowner who pass cr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Cond. Approval or Full Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Credit Check:</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need first 5 pages of trust:</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need Mortgage Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need signed Officer&apos;s Certificate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot verify sig, need printed name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Need change order form for correct addr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Customer Credit</label>
    <nameField>
        <displayFormat>CC-{0000000}</displayFormat>
        <label>Customer Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Credit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Generation_Assets__c.object
<CustomObject>
    <description>Generation Assets are energy generating facilities owned by SunRun</description>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Generation Assets</relationshipLabel>
        <relationshipName>Generation_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Generation Asset</label>
    <nameField>
        <label>Generation Assets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Generation Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Additional_Customer_Credit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Additional Customer Credit</label>
        <referenceTo>Customer_Credit__c</referenceTo>
        <relationshipLabel>Proposals (Additional Customer Credit)</relationshipLabel>
        <relationshipName>Proposals2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conditional_Approval_Amount__c</fullName>
        <label>Conditional Approval Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Conditional_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conditional Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credit_Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cash Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Approval from partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Pass &amp; signed up for ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approval Revoked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Home - Guarantee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Credit Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prepaid: Full Payment received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Customer_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Customer Credit Report</label>
        <referenceTo>Customer_Credit__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <label>Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Generation_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The generation asset that this proposal was used to issue</description>
        <inlineHelpText>The generation asset that this proposal was used to issue</inlineHelpText>
        <label>Generation Asset</label>
        <referenceTo>Generation_Assets__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Original_Proposal_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the proposal ID that the change order was created from</description>
        <label>Original Proposal ID</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pending_Notes__c</fullName>
        <label>Pending Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <description>Preferred Language</description>
        <formula>TEXT( Opportunity__r.Preferred_Language__c )</formula>
        <label>Preferred Language</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proposals (Primary Customer)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revised_Proposal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Revised Proposal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secondary_Customer_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Customer Credit Report</label>
        <referenceTo>Customer_Credit__c</referenceTo>
        <relationshipLabel>Proposals (Secondary Customer Credit Report)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/CreditCheckExtension.cls
/****************************************************************************
Author  : Peter Alexander Mandy (pmandy@sunrunhome.com)
Date    : August 07, 2012
Description: This code is used by the VF Page called CreditCheck
             It is passed two QueryString Parameters for the stdController id
             and for the proposal from which you initiated the search and drilldown 
             i.e. "/apex/CreditCheck?id={!CreditId}&ProposalId={!ProposalId}"
*****************************************************************************/
public without sharing class CreditCheckExtension {

	public Customer_Credit__c CCObj{get;set;}
	private String ApprovedStatus{get;set;}
	public String PendingReason{get;set;}
	public String PendingNotes{get;set;}
	public String ProposalID{get;set;}
	public String originalProposalId{get;set;}
	public Proposal__c parentProposalObj;
	
	private String OpptyId{get;set;}
	private String AcctId{get;set;}
	public Boolean bExpired{get;set;}
	public Id StartingContact{get;set;}
	public Id StartingAccount{get;set;}
	LeaseDimensions LD{get;set;}

	public Integer getRowHeight(){
		return 3;
	}
	public Integer getColumnWidth(){
		return 104;
	}
	
	public PageReference returnToCreditRecord(){
		PageReference pr = new PageReference('/' + this.CCObj.Id);
		pr.setRedirect(true);
		return pr;
	} 
	
	public PageReference CreditCheckRefresh(){	
	   LeaseDimensions LD = new LeaseDimensions();
	   String retval_usingConId = '';
	   String retval_usingCCId = '';
	   if(!Test.isRunningTest()){
	   	retval_usingConId = LD.refreshHomeownerCredit(this.CCObj.Contact__c);
	   }
	   System.Debug('refresh result value: ' + retval_usingConId);
	   if(retval_usingConId == 'SUCCESS')
	   {
	       ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'The credit report for ' + this.CCObj.Contact__r.Name + ' has been requested to be refreshed.'));
	   }   
	   else if(retval_usingConId != null && retval_usingConId.length() > 2 && retval_usingConId.Substring(0,3)=='306')
	   {
	   	   ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, retval_usingConId + ' - for Customer: ' + this.CCObj.Contact__r.Name));
	   }
	   else
	   {
			if(!Test.isRunningTest()){
				retval_usingCCId = LD.refreshHomeownerCredit(this.CCObj.Id);
   			}
	   	   if(retval_usingCCId == 'SUCCESS')
	   	   {
	   	   	   ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'The credit report for ' + this.CCObj.First_Name__c + ' ' + this.CCObj.Last_Name__c + ' has been requested to be refreshed.'));
	   	   }
	   	   else
	   	   {
	   	   	  String customernumber = this.CCObj.Contact__c;
	   	   	  if(this.CCObj.Contact__c == null)
	   	   	  {
	   	   	  	customernumber = this.CCObj.Id;
	   	   	  }
	   	      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, retval_usingCCId + 'Customer Number: ' + customernumber));
	   	   }
	   }
	   return null;
	}
	
	public CreditCheckExtension(){
		
	}
	
	public CreditCheckExtension(ApexPages.StandardController stdController){
	  this.CCObj = (Customer_Credit__c)stdController.getRecord();
	  initialize();
	}
	
	public void initialize(){
	  ApprovedStatus = this.CCObj.Approved__c;
	  PendingReason = this.CCObj.Pending_Reason__c;
	  PendingNotes =  this.CCObj.Pending_Notes__c;
	  ProposalID = ApexPages.CurrentPage().getparameters().get('ProposalId'); 
	  bExpired = false;
	  StartingContact = this.CCObj.Contact__c;
	  StartingAccount = this.CCObj.Account__c;
	  if(this.CCObj.Date_Pulled__c != null && Date.Today() > this.CCObj.Date_Pulled__c.addDays(CustomerCreditUtil.getCreditExpirationDays()))
	  {
	  	 bExpired = true;
	  }  
	  
	  for(Proposal__c p:[select id, Stage__c, Opportunity__c, Revised_Proposal__c, Original_Proposal_ID__c, Opportunity__r.AccountId, Conditional_Approval_Amount__c, Conditional_Approval__c from Proposal__c where id = :ProposalID])
	  {	
	  		this.CCObj.Account__c = p.Opportunity__r.AccountId;
			OpptyId = p.Opportunity__c;
			AcctId = p.Opportunity__r.AccountId;
			originalProposalId = (p.Original_Proposal_ID__c == null) ? p.Id : p.Original_Proposal_ID__c;
			parentProposalObj = p;
	  }
	  
	  System.Debug('Account Set for Reference: ' + this.CCObj.Account__c);
	}
	
	public PageReference submitNewCreditCheck(){
		LeaseDimensions LD = new LeaseDimensions();
		//validate email not exists
		for(Customer_Credit__c cc:[select id, Contact__c from Customer_Credit__c where Customer_Email__c = :this.CCObj.Customer_Email__c])
		{
	  	   ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'A Credit Check was already ran for: ' + this.CCObj.Customer_Email__c + ' Please click on the link to see the results: <a href="/' + cc.Id + '">Existing Credit Report</a>'));	   
		   return null;	
		}	
		//create Credit Report Record
		this.CCObj.Date_Submitted__c = System.Now();
		insert this.CCObj;	
		//call LD
		if(!Test.isRunningTest()){
			LD.CallCreateAndInvite(this.CCObj);
		}
		return null;
	}

	public PageReference resendInvitation(){
		LeaseDimensions LD = new LeaseDimensions();
		if(!Test.isRunningTest()){
			LD.resendToHomeowner(this.CCObj.Contact__c, this.CCObj.Contact__r.Preferred_Language__c);
		}
		return null;
	}
	
	public PageReference CancelCCEdit(){
		//If CC is tied to proposal then go back to that screen
		for(Proposal__c p:[select id from Proposal__c 
		                    where Id = :ProposalID 
		                      and (Current_Customer_Credit_Report__c = :this.CCObj.Id 
		                      		//OR Secondary_Customer_Credit_Report__c = :this.CCObj.Id 
		                      		//OR Additional_Customer_Credit__c = :this.CCObj.Id 
		                      	) LIMIT 1])
		{
		   PageReference prProposal = new PageReference('/' + ProposalID);
		   prProposal.setRedirect(true);
		   return prProposal;
		}
		PageReference prSearch = new PageReference('/apex/SearchCreditReports?id=' + ProposalID);
		prSearch.setRedirect(true);
		return prSearch;
	}
	
	public PageReference SaveAndUpdateProposal(){
		List<Proposal__c> pList = new List<Proposal__c>();
		if(this.CCObj.Contact__c == null)
		{
			this.CCObj.Account__c = null;
		}
		if(this.CCObj.id == null)
		{
			insert this.CCObj;
		}
		else
		{
				Set<Id> proposalIds = new Set<Id>();
				proposalIds.add(ProposalID);
				//proposalIds.add(originalProposalId);

				//
				//Check to see if Approved is not null and was null
				//UPDATE PROPOSAL DATA
				System.debug('originalProposalId: ' + originalProposalId);
				System.debug('ProposalID: ' + ProposalID);
				for(Proposal__c p:[select id, Stage__c, Opportunity__c, Revised_Proposal__c, Original_Proposal_ID__c, Conditional_Approval_Amount__c, Conditional_Approval__c, 
			   						Current_Customer_Credit_Report__c, Primary_Customer__r.email, Credit_Status__c,
			   						Generation_Asset__r.Name from Proposal__c where (id in :proposalIds)])
			   	{
			
					
					//if((parentProposalObj != null) && (p.ID != ProposalID)
					//	&& ((parentProposalObj.Revised_Proposal__c == true && parentProposalObj.Original_Proposal_ID__c == p.id)
					//		|| (p.Original_Proposal_ID__c == parentProposalObj.Id && p.Revised_Proposal__c == true) 
					//		|| (p.Original_Proposal_ID__c == parentProposalObj.Original_Proposal_ID__c && p.Revised_Proposal__c == true))){
					//	continue;	
					//}
					
					if(p.ID == ProposalID || p.Current_Customer_Credit_Report__c == null 
						|| p.Current_Customer_Credit_Report__c == this.CCObj.Id){
						p.Current_Customer_Credit_Report__c = this.CCObj.Id;
						p.Primary_Customer__c = this.CCObj.Contact__c;
						p.Credit_Status__c = this.CCObj.Approved__c;
			   		}

					if(p.Generation_Asset__r.Name != null && p.Generation_Asset__r.Name != '' && p.ID == ProposalID)
					{
						if(this.CCObj.SRH_Customer_Number__c == null || this.CCObj.SRH_Customer_Number__c == ''){
							this.CCObj.SRH_Customer_Number__c = p.Generation_Asset__r.Name;	
						}
					}
					pList.add(p);
			   }	
			   System.debug('pList: ' + pList);	   	

				System.Debug('Checking Pending Reason');
				//Check to see if PendingReason is not null or changed
				if ((PendingReason == '' && this.CCObj.Pending_Reason__c != '') || (this.CCObj.Pending_Reason__c != null && this.CCObj.Pending_Reason__c != PendingReason))
				{
			   		if(!pList.isEmpty())	
			   		{
			   	  		for(Proposal__c p: pList)
			      		{

							//if((parentProposalObj != null) && (p.ID != ProposalID)
							//	&& ((parentProposalObj.Revised_Proposal__c == true && parentProposalObj.Original_Proposal_ID__c == p.id)
							//		|| (p.Original_Proposal_ID__c == parentProposalObj.Id && p.Revised_Proposal__c == true) 
							//		|| (p.Original_Proposal_ID__c == parentProposalObj.Original_Proposal_ID__c && p.Revised_Proposal__c == true))){
							//	continue;	
							//}
							
							if(p.ID == ProposalID){
								p.Stage__c = 'Pending'; 
								p.Pending_Proposal_Reason__c = this.CCObj.Pending_Reason__c;
								p.Pending_Comments__c = this.CCObj.Pending_Comments__c;
								p.Pending_Notes__c = this.CCObj.Pending_Notes__c;
			      			}
			      		
			      			if(p.ID == ProposalID || p.Current_Customer_Credit_Report__c == null 
							|| p.Current_Customer_Credit_Report__c == this.CCObj.Id){
								p.Current_Customer_Credit_Report__c = this.CCObj.Id;
								p.Primary_Customer__c = this.CCObj.Contact__c;
								p.Credit_Status__c = this.CCObj.Approved__c;
							}
			      		}
			   		}

				}		
			
			//Update the Oppty Credit_Status__c too
			Set<Id> OppId = new Set<Id>();
			List<Opportunity> listOppty = new List<Opportunity>();
			if(!pList.isEmpty())
			{
				System.Debug('Pending Reason updated on Prop' + ProposalID);
				update pList;
				for(Proposal__c p:pList)
				{
					OppId.add(p.Opportunity__c);
				}
				if(!OppId.isEmpty())
				{
					for(Opportunity o:[select id, Credit_Status__c from Opportunity where id in :OppId])
					{
						o.Credit_Status__c = 'Approved';
						listOppty.add(o);
					}
				}			
			}
			if(!listOppty.isEmpty())
			{
				update listOppty;
			}
			//
			// Check if Contact exists, if yes, and not attached as OCR to Oppty, create. 
			// if contact not exists, create and add to OCR on Oppty to which Proposal belongs.

				try{
					String contactRoleStr = EDPUtil.OCR_ROLE_CREDIT;
					Id contactId;
					Boolean bOCRExists = false;	
					Boolean contactExistis = false;		
					OpportunityContactRole existingOptyRole;
					Id proposalContactId;
					for(Contact existingContact : [Select Id, accountId, name , firstname, lastName, email,
													(Select Id, role, opportunityId, contactId, contact.name, contact.email 
														from OpportunityContactRoles where opportunityId =:OpptyId)  from Contact 
													where accountId =:AcctId and email =:this.CCObj.Customer_Email__c ]){
						
						if(existingContact.OpportunityContactRoles != null && existingContact.OpportunityContactRoles.size() > 0){
							existingOptyRole = null;
							for(OpportunityContactRole optyContactRoleObj : existingContact.OpportunityContactRoles){
								if(optyContactRoleObj.role == EDPUtil.HOME_OWNER){
									proposalContactId = optyContactRoleObj.contactId;
									System.debug('optyContactRoleObj: ' + optyContactRoleObj);
								}
								if(optyContactRoleObj.role == contactRoleStr || optyContactRoleObj.role == EDPUtil.OTHER){
									existingOptyRole = optyContactRoleObj;
									proposalContactId = optyContactRoleObj.contactId;
									bOCRExists = true;
									if(optyContactRoleObj.role == EDPUtil.OTHER){
										optyContactRoleObj.role = contactRoleStr;
										update optyContactRoleObj;
									}
									break;
								}
							}			
						}
						contactExistis = true;
						contactId = existingContact.Id;
						if(proposalContactId != null){
							break;
						}
					}
					
					System.debug('contactExistis: ' + contactExistis);
					if(contactExistis == false){
						
						Contact c = createContact(AcctId, this.CCObj);
						insert c;	
						contactId = c.Id;							
						String proposalSOQLStr = ProposalUtil.getProposalSQLStr();
						proposalSOQLStr += ' where Id =:proposalId ' ;
						List<Proposal__c> proposalsList = Database.query(proposalSOQLStr);
						if(proposalsList.size() > 0){
							Proposal__C tempProposalObj = proposalsList[0];
							Map<Id, Proposal__c> proposalMap = new Map<Id, Proposal__c>();
							proposalMap.put(tempProposalObj.Id, tempProposalObj);
							ProposalUtil.optyAndContactSharingForProposals(proposalMap.values());
						}
					}

					if(!bOCRExists)
					{
						Id tempContactId = (proposalContactId != null) ? proposalContactId : contactId;
						insertOptyContactRole(OpptyId, tempContactId);
					}
										
					if(this.CCObj.Contact__c == null){
						Id tempContactId = (proposalContactId != null) ? proposalContactId : contactId;
						this.CCObj.Contact__c = contactId;
					}

				}catch(Exception e)
			    {
			       System.Debug('Error Message: ' + e.getMessage());
			       ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));  
			    }
			    	
			}
			System.debug('Before update ...');
			update this.CCObj;
			
			PageReference pr = new PageReference('/' + ProposalID);
			pr.setRedirect(true);
			return pr;
	}

	public static void insertOptyContactRole(Id OpptyId, Id contactId){
		OpportunityContactRole ocrNew = new OpportunityContactRole();
		ocrNew.OpportunityId = OpptyId;
		ocrNew.ContactId = contactId;
		ocrNew.Role = EDPUtil.OCR_ROLE_CREDIT;
		upsert ocrNew;
	}
	
	public static Contact createContact(Id AcctId, Customer_Credit__c CCObj){
		
		Contact c = new Contact();
		c.AccountId = AcctId;
		c.LastName =	CCObj.Last_Name__c;
		c.FirstName = CCObj.First_Name__c;
		c.Email = CCObj.Customer_Email__c;
		Account aForAddr;
		for(Account acct:[select id, BillingStreet, BillingState, BillingPostalCode, BillingCountry, BillingCity, Phone 
									From Account where Id = :c.AccountId])
		{
			aForAddr = acct;
		}
		
		System.Debug('Account for ADDR: ' + aForAddr);
		if(CCObj.Street__c == null || CCObj.Street__c == '')
		{
			c.MailingStreet = aForAddr.BillingStreet;
		}
		  else
		  {
		  	 c.MailingStreet = CCObj.Street__c;
		  }
		  if(CCObj.State__c == null || CCObj.State__c == '')
		  {
		     c.MailingState = aForAddr.BillingState;
		  }
		  else
		  {
		  	 c.MailingState = CCObj.State__c;
		  }
		  if(CCObj.Zip__c == null || CCObj.Zip__c == '')
		  {
		     c.MailingPostalCode = aForAddr.BillingPostalCode;
		  }
		  else
		  {
		  	 c.MailingPostalCode = CCObj.Zip__c;
		  }
		  if(CCObj.Country__c == null || CCObj.Country__c == '')
		  {
		     c.MailingCountry = aForAddr.BillingCountry;
		  }
		  else
		  {
		  	 c.MailingCountry = CCObj.Country__c;
		  }
		  if(CCObj.City__c == null || CCObj.City__c == '')
		  {
		     c.MailingCity = aForAddr.BillingCity;
		  }
		  else
		  {
		  	 c.MailingCity = CCObj.City__c;
		  }
		  if(CCObj.Home_Phone__c == null || CCObj.Home_Phone__c == '')
		  {
		     c.Phone = aForAddr.Phone;
		  }
		  else
		  {
		  	 c.Phone = CCObj.Home_Phone__c;
		  }
		  c.OtherPhone = CCObj.Other_Phone__c;
		  c.Birthdate = CCObj.DateOfBirth__c;
		  return c;
	}

}