SFDCProject/src/objects/Design_Option__c.object
<CustomObject>
    <fields>
        <fullName>KWH_KWP__c</fullName>
        <defaultValue>0</defaultValue>
        <label>kWh/kWp</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KWH__c</fullName>
        <defaultValue>0</defaultValue>
        <label>kWh</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KWP__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field will be populated from design tool.</description>
        <label>kWp</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Design_Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <description>This field will be populated from design tool.</description>
        <label>Module</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <description>This fields will be populated from design tools</description>
        <label>Serial Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Usage__c</fullName>
        <label>Usage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>costPerYearkWh__c</fullName>
        <label>Cost/Year (kWh)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Design Estimate</label>
    <nameField>
        <label>Design Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Design Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/PartnerDesignOption.cls
public with sharing class PartnerDesignOption {
	
	public static Integer PAGE_SIZE1 = 5;
	public Integer pageSize {get; set;}
	public List<Design_Option__c> desOptionObj;
	public Lead leadObj;
	
	public PartnerDesignOption(ApexPages.StandardController stdController) { 
        
        leadObj = (Lead)stdController.getRecord();
        System.debug('leadObj'+leadObj);
	}
	
	public ApexPages.StandardSetController con {
        get
        {
            if(con != null){
                    return con;
                }
            con = createSQOLConnection();
            pageSize = (pageSize == null || pageSize <= 0) ? PAGE_SIZE1 : pageSize;
            if(pageSize != null){
                con.setPageSize(pageSize);
            }  
            return con;
        }
        set;
    } 
    
    //Creates the SOQL connection to get the records
    private ApexPages.StandardSetController createSQOLConnection(){
        ApexPages.StandardSetController tempConnection;
              
        String soqlQuery;
        System.debug('leadObj.Id'+leadObj.Id);

        soqlQuery = 'Select costPerYearkWh__c,Serial_Number__c, Module__c, Lead__c , KWP__c, KWH_KWP__c,';
        soqlQuery += ' KWH__c, Usage__c From Design_Option__c ';
        soqlQuery += ' Where Lead__c =\''+leadObj.Id+'\'' ;
        soqlQuery += ' ORDER BY LastModifiedDate DESC limit 10000';
        
        System.debug('soqlQuery: ' + soqlQuery);
        
        tempConnection = new ApexPages.StandardSetController(Database.getQueryLocator(soqlQuery));
        return tempConnection;          
    }
    
    public List<Design_Option__c> getleadDesignOption(){

        List<Design_Option__c> allDesOpt = new List<Design_Option__c>();
        if(con != null) {
            allDesOpt = con.getRecords();
        }
        return allDesOpt;
    }    
        
    public Boolean hasNext{
        get
        {
            return con.getHasNext();
        }
        set;
    }
 
    public Boolean hasPrevious{
        get
        {
            return con.getHasPrevious();
        }
        set;
    }
 
    
    public Integer pageNumber{
        get
        {
            return con.getPageNumber();
        }
        set;
    }

    public void first(){
        con.first();
    }  
 
    public void last(){
        con.last();
    }
        
    public void previous(){
        con.previous();
    }

    public void next(){
        con.next();
    }   
  
}