SFDCProject/src/objects/Document_Classification__c.object
<CustomObject>
    <label>Document Classification</label>
    <nameField>
        <label>Document_Classification_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Partner_Document_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Document_Classification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Classification</label>
        <referenceTo>Document_Classification__c</referenceTo>
        <relationshipLabel>Partner Document Relationships</relationshipLabel>
        <relationshipName>Partner_Document_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Partner Document Relationship</label>
    <nameField>
        <label>Partner Document Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Document Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>ACH_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ACH Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <description>The type of agreement proposed to the customer for Power Plan.</description>
        <label>Agreement Type</label>
        <picklist>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Owned - Full Upfront</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Owned - Bank Financed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Conditional_Approval_Amount__c</fullName>
        <label>Conditional Approval Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Conditional_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conditional Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost_Stack__c</fullName>
        <label>Cost Stack</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cash Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Approval from partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Pass &amp; signed up for ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approval Revoked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Home - Guarantee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Credit Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prepaid: Full Payment received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Credit_team_notes__c</fullName>
        <label>Credit team notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current_Customer_Credit_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Customer Credit Report</label>
        <referenceTo>Customer_Credit__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Signoff_Date__c</fullName>
        <label>Customer Signoff</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Time_Ops_Received_Proposal_back__c</fullName>
        <label>Date/Time Ops Received Proposal back</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Finance_Type__c</fullName>
        <label>Finance Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bank Financed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Home_Type__c</fullName>
        <label>Home Type</label>
        <picklist>
            <picklistValues>
                <fullName>Detached single family home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertically-split duplex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Townhome / rowhome</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Install_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_on_Credit_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Name on Credit Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Original_Proposal_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the proposal ID that the change order was created from</description>
        <label>Original Proposal ID</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Financed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Financed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <description>Preferred Language</description>
        <formula>TEXT( Opportunity__r.Preferred_Language__c )</formula>
        <label>Preferred Language</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proposals (Primary Customer)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal_Source__c</fullName>
        <label>Proposal Source</label>
        <picklist>
            <picklistValues>
                <fullName>PT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals (Sales Partner)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sunrun_Credit_Status__c</fullName>
        <label>Sunrun Credit Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Solar_Prepay_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Total Solar Prepay Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/SR_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Classification__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Document Classification</label>
        <referenceTo>Document_Classification__c</referenceTo>
        <relationshipLabel>SR Attachments</relationshipLabel>
        <relationshipName>SR_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Source__c</fullName>
        <label>Document Source</label>
        <picklist>
            <picklistValues>
                <fullName>Proposal Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Upload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eSign</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Type_Name__c</fullName>
        <formula>Document_Classification__r.Document_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Envelop_Id__c</fullName>
        <externalId>true</externalId>
        <label>Envelop Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>SR_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal_Source__c</fullName>
        <label>Proposal Source</label>
        <picklist>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>SR_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SR Attachment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SR Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/ProposalBaseHandler.cls
public abstract class ProposalBaseHandler extends RestService implements RestRequestHandler {
    public static String HOMEOWNER_PRIMARY = 'Homeowner_Primary';
    public String getDocuSignInpersonSigningURL(String envelopId, Integer recipientId, String envelopString){
        String signingURL = '';
        eSignServiceNew.EnvResponse response = eSignServiceNew.getEmbeddedSigningURL(envelopId, recipientId, envelopString);
        if(response.errorCode != null && response.errorCode != ''){
            System.debug(response.errorCode + ': ' + response.message);
            throw createBusinessException(RestServiceDto.Unable_To_Process_Request, 'Unable to get the DocuSign inperson URL for the envelop [' + envelopId + '].');
        }       
        if(response.url != null && response.url != ''){
            signingURL = response.url;
        }
		return signingURL;
    }
    
    public Proposal__c getProposalByName(String proposalName){
        Set<String> proposalNames = new Set<String>();
        proposalNames.add(proposalName); 
        Map<String, Proposal__C> proposalMap = new Map<String, Proposal__C>();
        //ProposalUtil.getProposalMapByName(proposalNames);
        if(proposalNames.size() > 0 ){
			for(Proposal__c propObj : [Select Id, Opportunity__c, name, Stage__C, cost_stack__c, Total_Solar_Prepay_Required__c, Conditional_Approval__c, ACH_Required__c, Sunrun_Credit_Status__c,Agreement_Type__c,Sales_Partner__c,Finance_Type__c,
                                            Primary_Customer__c,Credit_Status__c, Credit_team_notes__c,  Current_Customer_Credit_Report__c, home_type__c, Customer_Signoff_Date__c,
                                            Conditional_Approval_Amount__c, Original_Proposal_ID__c, Partner_Financed__c, Original_Proposal_ID__r.Id, Install_Partner__c,
                                            Original_Proposal_ID__r.Conditional_Approval__c, Original_Proposal_ID__r.ACH_Required__c, Name_on_Credit_Verified__c, Date_Time_Ops_Received_Proposal_back__c,
                                            Original_Proposal_ID__r.Primary_Customer__c, Original_Proposal_ID__r.Credit_Status__c, Original_Proposal_ID__r.Name_on_Credit_Verified__c,
                                            Original_Proposal_ID__r.Credit_team_notes__c,Original_Proposal_ID__r.Current_Customer_Credit_Report__c, Original_Proposal_ID__r.Date_Time_Ops_Received_Proposal_back__c,
                                            Original_Proposal_ID__r.Conditional_Approval_Amount__c, Original_Proposal_ID__r.Partner_Financed__c, Original_Proposal_ID__r.Customer_Signoff_Date__c,
                                            Original_Proposal_ID__r.Sunrun_Credit_Status__c, Original_Proposal_ID__r.Total_Solar_Prepay_Required__c 
                                            from Proposal__c where name in :proposalNames]){
                proposalMap.put(propObj.Name, propObj);
            }           
        }
		return proposalMap.get(proposalName);
    }
    
    public Opportunity getOpportunity(String prospectId){
        Opportunity resultOpty;
        List<Opportunity> optyList = [Select Id, name from Opportunity where Prospect_Id__c =:prospectId];
        if(optyList != null && !optyList.isEmpty()){
            resultOpty = optyList[0];
        }
        return resultOpty;
    }
    
    public Map<String, Contact> getOptyContacts(Id optyId){
        Map<String, Contact> contactMap = new Map<String, Contact>();
        for(OpportunityContactRole roleObj : [Select Id, OpportunityId, contactId, role, isPrimary, contact.Id, contact.Name, contact.Email,
                                              contact.account.DocuSign_Host_Name__c, contact.account.DocuSign_Host_Email__c,
                                              contact.Preferred_Language__c, contact.Contact_Number__c, contact.Sales_Registration_Number__c, 
                                              contact.phone from OpportunityContactRole where OpportunityId = :optyId order by contact.Name asc]){
                                                  if(roleObj.role == 'Homeowner' && roleObj.isprimary == true){
                                                      contactMap.put(HOMEOWNER_PRIMARY, roleObj.contact);
                                                  }else if(!String.isEmpty(roleObj.role)){
                                                      contactMap.put(roleObj.role, roleObj.contact);                        
                                                  } 
                                              }
        return contactMap;  
    }
    
    public SR_Attachment__c getSRAttachmentWithEnvelopId(Id proposalId, Id documentTypeId){
        SR_Attachment__c result;
        String blackBirdStr = ProposalUtil.BLACK_BIRD;
        String soqlStr = SRAttachmentManager.getSRAttachmentSOQL();
        soqlStr += '  WHERE Proposal__c =:proposalId ' ;
        soqlStr += '  AND active__c = true ' ;
        //soqlStr += '  AND proposal_source__c =:blackBirdStr ' ;
        soqlStr += '  AND Document_Classification__c = :documentTypeId ';
        soqlStr += '  AND   Envelop_Id__c != null and Envelop_Id__c != \'\' ';
        
        System.debug('documentTypeId: ' + documentTypeId);
        System.debug('proposalId: ' + proposalId);
        System.debug('soqlStr: ' + soqlStr);
        
        List<SR_Attachment__c> srAttachmentList = Database.query(soqlStr);
        if(!srAttachmentList.isEmpty()){
            result = srAttachmentList[0];
        }
        System.debug('SR Attachment: ' + result);
        return result;
    }
    
    public String getS3FolderNameByDocumentType(String parentId, String documentType){
    	return 'QUALIFICATION_PHOTO';
    }

	public List<SR_Attachment__c> getSRAttachments(String proposalName, String documentType, Set<String> srIds) {
		String proposalsoql = createSoqlWithAuditFields(getProposalFieldMapping().values(), 'Proposal__c', 'Name = :proposalName');
       	List<SObject> proposalSObjects = Database.query(proposalsoql);
        if (proposalSObjects.isEmpty()) {
            throw createBusinessException(RestServiceDto.Error_NotFound, 'Proposal with specified Proposal Number [' + proposalName + '] is not found');
        }
        Proposal__c proposalObj = (Proposal__c) proposalSObjects.get(0);
		
		Id proposalId = proposalObj.Id;
		String documentSource = EDPUtil.PROPOSAL_TOOL_SOURCE;

		String soql = '';
		soql = SRAttachmentManager.getSRAttachmentSOQL();
		soql += ' where proposal__c =:proposalId and active__c = true and document_source__c != :documentSource  ' ;
		if(!String.isEmpty(documentType)){
			documentType = EncodingUtil.urlDecode(documentType, 'UTF-8');
			soql += ' and Document_Type_Name__c =:documentType ';
		}
		if(srIds != null && !srIds.isEmpty()){
			soql += ' and Id in :srIds ';
		}
		List<SObject> sobjs = Database.query(soql);
		return sobjs;
    }

	public void prepareSRAttachmentResponse(List<SR_Attachment__c> srAttachments, RestServiceDto.Request req, RestServiceDto.Response resp) {
		Map<String, String> fieldMappings = getSRAttachmentFieldMapping();
		resp.jsonWriter = new JsonWriter(true);
		Integer i = 0;
		for(SR_Attachment__c srAttachmentObj : srAttachments){
			resp.jsonWriter.with(i);
			if(srAttachmentObj.active__c == true){
				SRAttachmentWrapper srAttachmentWrapperObj = new SRAttachmentWrapper(srAttachmentObj);
				resp.jsonWriter.write('url', srAttachmentWrapperObj.signedURL);
			}
		    for (String restField : fieldMappings.keySet()) {
		    	resp.jsonWriter.writeIfNotNull(restField, getValue(srAttachmentObj, fieldMappings.get(restField)));
		    }
			resp.jsonWriter.write('createdDate', srAttachmentObj.CreatedDate);
		    resp.jsonWriter.write('lastModifiedDate', srAttachmentObj.LastModifiedDate);
			resp.jsonWriter.endWith();
			i++;   	
		}
	}


    public Map<String, String> getSRAttachmentFieldMapping() {
		return RestServiceDto.getFieldMapping('Proposal Api', 'SR_Attachment__c');        
    }    
    
    public Map<String, String> getProposalFieldMapping() {
		return RestServiceDto.getFieldMapping('Proposal Api', 'Proposal__c');        
    }
	
	public Partner_Document_Relationship__c getPartnerDocumentRelationship(List<Partner_Document_Relationship__c> partnerDocumentRelationships, String partnerType){
		Partner_Document_Relationship__c result;
		if(partnerDocumentRelationships != null){
			for(Partner_Document_Relationship__c tempObj : partnerDocumentRelationships){
				if(tempObj.partner_type__c == partnerType){
					result = tempObj;
					break;
				}
				if(tempObj.partner_type__c == EDPUtil.FULL_SERVICE){
					result = tempObj;
				}
			}
		}
		return result;
	} 
}