SFDCProject/src/objects/Document_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Allow_To_Over_Write__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow To Over-Write</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <externalId>true</externalId>
        <label>Document Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Document Classification</label>
    <nameField>
        <label>Document_Classification_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/PartnerDetail__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>PartnerUserId__c</fullName>
        <label>PartnerUserId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>PartnerDetail</label>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Change_Order_With_New_Proposal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CO With New Proposal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposal_ID__c</fullName>
        <description>The proposal identification number.</description>
        <label>Proposal ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/SR_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DocuSign_Status__c</fullName>
        <label>DocuSign Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wet Signed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Classification__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Document Classification</label>
        <referenceTo>Document_Classification__c</referenceTo>
        <relationshipLabel>SR Attachments</relationshipLabel>
        <relationshipName>SR_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>SR_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>SR_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SR Attachment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SR Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_FileUploaderComponentOpp.cls
@isTest(SeeAllData=true)
public class Test_FileUploaderComponentOpp {
    public static testMethod void TestFileUploaderComponent(){
        
        Id userId = PartnerDetail__c.getValues('ApexTestAccount').PartnerUserId__c;
        User partnerUser = [Select id, name, email from User where Id =:userId];
        //Test.startTest();
        List<Document_Classification__c> docClassList = new List<Document_Classification__c>();
        
        Document_Classification__c docClassRec1 = new Document_Classification__c();
        docClassRec1.Name = 'Test Customer Agreement';
        docClassRec1.Document_Name__c = 'Test Customer Agreement';
        docClassRec1.Allow_To_Over_Write__c = true;
        docClassList.add(docClassRec1);
        
        Document_Classification__c docClassRec2 = new Document_Classification__c();
        docClassRec2.Name = 'Test Customer Agreement1';
        docClassRec2.Document_Name__c = 'Test Customer Agreement1';
        docClassRec2.Allow_To_Over_Write__c = false;
        docClassList.add(docClassRec2);
        
        insert(docClassList);
        
        //System.runAs(partnerUser){
        
        Opportunity optyObj1 = TestPRMLibrary.insertOpportunity('ResidentialAccount-3', 'Residential',
                                                                'ResOpty-3', 'Platinum');   
        List<Proposal__c> proposalList = new List<Proposal__c>();
        Proposal__c proposalObj1 = new Proposal__c();
        proposalObj1.Name = 'P87A13E7174V1BN-H';
        proposalObj1.Opportunity__c = optyObj1.Id;
        proposalObj1.Upfront_Payment__c = 1000;
        proposalObj1.Proposal_ID__c = 2441242;
        proposalObj1.System_Size_STC_DC__c = 1;
        proposalObj1.Mode_Name__c = 'Mode-1';
        proposalObj1.Date_Issued__c =  date.today();
        proposalObj1.Sales_Rep_Email__c = 'test@gmail.com';
        proposalList.add(proposalObj1);

        Proposal__c proposalObj2 = new Proposal__c();
        proposalObj2.Name = 'Proposal-2';
        proposalObj2.Opportunity__c = optyObj1.Id;
        proposalObj2.Upfront_Payment__c = 1000;
        proposalObj2.Proposal_ID__c = 2441242;
        proposalObj2.System_Size_STC_DC__c = 1;
        proposalObj2.Mode_Name__c = 'Mode-2';
        proposalObj2.Date_Issued__c =  date.today();
        proposalObj2.Sales_Rep_Email__c = 'test2@gmail.com';
        proposalObj2.Change_Order_With_New_Proposal__c = true;
        proposalList.add(proposalObj2); 
        // insert proposalList;
        
        
        List<SR_Attachment__c> srAttachmentList = new List<SR_Attachment__c>();
        SR_Attachment__c srAttachmentObj1;
        List<Proposal__C> lstProposal = [select Id from Proposal__C limit 1];
        String envelopId1 = '';
        String proposalIdStr = lstProposal[0].Id;
        Map<String, String> newAttachments = new Map<String, String>();
        //Create SR Attachment

        
        srAttachmentObj1 = UnitTest_ProposalUtil.CreateSRAttachment('Customer Agreement', envelopId1, proposalIdStr, 
                                                                    'TestFile01.pdf', EDPUtil.PROPOSAL_TOOL_SOURCE);
        srAttachmentObj1.DocuSign_Status__c = EDPUtil.COMPLETED;
        srAttachmentObj1.Active__c = true;
        srAttachmentObj1.Opportunity__c  = optyObj1.Id;
        srAttachmentList.add(srAttachmentObj1);

        envelopId1 = '';
        srAttachmentObj1 = UnitTest_ProposalUtil.CreateSRAttachment('EPC', envelopId1, proposalIdStr, 
                                                                    'TestFile02.pdf', EDPUtil.PROPOSAL_TOOL_SOURCE);
        srAttachmentObj1.DocuSign_Status__c = EDPUtil.COMPLETED;
        srAttachmentObj1.Active__c = true;
        srAttachmentObj1.Opportunity__c  = optyObj1.Id;
        srAttachmentList.add(srAttachmentObj1);

        envelopId1 = '5335SDFF-43643-GSGA341';
        srAttachmentObj1 = UnitTest_ProposalUtil.CreateSRAttachment('Utility Bill', envelopId1, proposalIdStr, 
                                                                    'TestFile03.pdf', EDPUtil.MANUAL_UPLOAD_SOURCE);
        srAttachmentObj1.DocuSign_Status__c = EDPUtil.WET_SIGNED;
        srAttachmentObj1.Active__c = true;
        srAttachmentObj1.Opportunity__c  = optyObj1.Id;
        srAttachmentList.add(srAttachmentObj1);     
        newAttachments.put(srAttachmentObj1.Document_Classification__c, 'TestFile03.pdf');

        envelopId1 = '7335SDFF-43643-GSGA342';
        srAttachmentObj1 = UnitTest_ProposalUtil.CreateSRAttachment('Large System Contract Approval Request', envelopId1, proposalIdStr, 
                                                                    'TestFile04.pdf', EDPUtil.MANUAL_UPLOAD_SOURCE);
        newAttachments.put(srAttachmentObj1.Document_Classification__c, 'TestFile04.pdf');
        srAttachmentObj1.DocuSign_Status__c = EDPUtil.COMPLETED;
        srAttachmentObj1.Active__c = true;
        
        srAttachmentObj1.Opportunity__c  =optyObj1.Id;
        srAttachmentList.add(srAttachmentObj1);         
        insert srAttachmentList;


        
       
        
        //ApexPages.StandardController stdcon = new ApexPages.StandardController(proposalObj1);
        ApexPages.StandardController stdcon = new ApexPages.StandardController(optyObj1);
        FileUploader FileUploaderObj1 = new FileUploader(stdcon);
        FileUploader FileUploaderObj = new FileUploader();
        Id relatedObjectId = FileUploaderObj.relatedObjectId;
        
        FileUploaderComponentOpp FileUploaderComponentObj = New FileUploaderComponentOpp();
        
        //FileUploaderComponentObj.relatedObject = 'a08g0000000J8Ao';
        FileUploaderComponentObj.relatedObject = optyObj1.id;
        
        FileUploaderComponentObj.getBaseURL();
        FileUploaderComponentObj.getDocumentTypes();
        FileUploaderComponentObj.getExistingSRAttachments();
        FileUploaderComponentObj.getDocumentClasification();

        FileUploaderComponentOpp.ExistingAttachmentsResponse ExistingAttachmentsResponseObj = new FileUploaderComponentOpp.ExistingAttachmentsResponse();
        FileUploaderComponentOpp.UpsertRequest UpsertRequestObj = new FileUploaderComponentOpp.UpsertRequest();
        FileUploaderComponentOpp.SRUpsertResponse SRUpsertResponseObj = new FileUploaderComponentOpp.SRUpsertResponse();
        
        //String relatedObjectId1 = 'a08g0000000J8Ao';
        String relatedObjectId1 = optyObj1.id;
        //Map<String, String> newAttachments = new Map<String, String>();
        newAttachments.put(docClassRec1.id, 'Filename1');
        newAttachments.put(docClassRec2.id, 'Filename2');   
    
        FileUploaderComponentOpp.checkexistingSRAttachments(relatedObjectId1, newAttachments); 
        
        String proposalName = optyObj1.id;
        String objectName = optyObj1.id;
        String mimeType = 'pdf';
        String sObjectType = '';
        FileUploaderComponentOpp.getS3ProxyInfoForPut(sObjectType, proposalName, objectName, mimeType);
        
        string test = 'Test';
        //FileUploaderComponent.deleteSelectedRecords(test);
        
        String strDocType = 'Utility';
        FileUploaderComponentOpp.DocSignStatus(strDocType);
        
        String parentObjectId = optyObj1.id;
        String fileName = 'TestFilename';
        String amazonS3FileName = 'TestFilename20130523903';
        String contactDocumentType = 'Utility'; 
        String contactDocumentTypeName = 'Utility';
        String fileSize = '3000';
        String contactDocumentWetSign = 'Signed';
        FileUploaderComponentOpp.upsertSRAttachment(parentObjectId, fileName, amazonS3FileName, contactDocumentType, contactDocumentTypeName, fileSize, contactDocumentWetSign);
        FileUploaderComponentObj.getExistingSRAttachments();
        FileUploaderComponentOpp.UpsertRequest UR = new FileUploaderComponentOpp.UpsertRequest();
        UR.relatedObjectId = 'ab';
        UR.fileName = 'ab';
        UR.amazonS3FileName = 'ab';
        UR.documentType = 'ab';
        UR.documentTypeName = 'ab';
        UR.size = 'ab';
        UR.wetSign = 'ab';
        UR.conentType = 'ab';
        
       // }
       // Test.stopTest();
    }
}