SFDCProject/src/objects/Document_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Document_Name__c</fullName>
        <externalId>true</externalId>
        <label>Document Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Document Classification</label>
    <nameField>
        <label>Document_Classification_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Change_Order_Information__c</fullName>
        <label>Change Order Information</label>
        <picklist>
            <picklistValues>
                <fullName>CUSTOMER_CHANGE_ORDER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPC_CHANGE_ORDER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FULL_PROPOSAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO_SIGNATURES_REQUIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SALES_PARTNER_CHANGE_ORDER</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Install_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposal_Source__c</fullName>
        <label>Proposal Source</label>
        <picklist>
            <picklistValues>
                <fullName>PT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals (Sales Partner)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/SR_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DocuSign_Status__c</fullName>
        <label>DocuSign Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wet Signed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Classification__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Document Classification</label>
        <referenceTo>Document_Classification__c</referenceTo>
        <relationshipLabel>SR Attachments</relationshipLabel>
        <relationshipName>SR_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Name_On_File_Server__c</fullName>
        <label>Document Name on File Server</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Source__c</fullName>
        <label>Document Source</label>
        <picklist>
            <picklistValues>
                <fullName>Proposal Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Upload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eSign</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Envelop_Id__c</fullName>
        <externalId>true</externalId>
        <label>Envelop Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>SR_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Proposal_Name__c</fullName>
        <label>Parent Proposal Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal_Source__c</fullName>
        <label>Proposal Source</label>
        <picklist>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>SR_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wet_Sign_Status__c</fullName>
        <description>This Field used to Specify the status whether signature is required or not</description>
        <label>Wet Signature Status</label>
        <picklist>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SR Attachment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SR Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/DocusignApiTest.cls
@isTest(SeeAllData=true)
public class DocusignApiTest {
	private static BaseClass utils = new BaseClass();
    
    testmethod public static void testDocuSignInpersonUrl() {

		insertSettings();
        
		//Test required parameter (proposal id) test
		BaseApiTest.setRequest('/v2/eSign/inPersonUrl');
		BaseApiTest.setParam('envelopeId', '1234567');
		BaseApiTest.setParam('recipient', '1');
		BaseApiTest.setParam('proposalId', 'PK1234567890-A');
		DocusignApiInpersonUrlEndpoint.httpGet();
        
        //Insert a proposal and try to get it.
		Account acct = new Account(Name='Foo', RecordTypeId=utils.getRecordTypeId('Account', 'Partner'), 
			BillingCity='Dublin',
			Office_Location__c  = 'Headquarters',
			Stage__c = 'Confirmed',
			Active__c  = true);
        insert acct;
        
        Opportunity opty1 = new Opportunity(Name='Test', StageName='Stage', CloseDate=Date.today());
        insert opty1;

        //With sync disabled, insert proposal and it should not create sync records.
        Proposal__c proposal = new Proposal__c(Mode_Name__c='Mode', Opportunity__c=opty1.id,
			Sales_Rep_Email__c='test@yopmail.com', stage__c='Created', Date_Issued__c=Date.today(), System_Size_STC_DC__c=10.0, Upfront_Payment__c=00.0);
        insert proposal;
        proposal = (Proposal__c) utils.queryAllFields(proposal.id);
        
        System.debug('proposal: ' + proposal);
		Document_Classification__c classificationObj = [Select Id, Document_Name__c from Document_Classification__c where Document_Name__c = 'Customer Agreement'];
        SR_Attachment__c srAttachment = new SR_Attachment__c(proposal__c=proposal.Id, Document_Name_On_File_Server__c='Test.PDF', 
															active__c=true,size__c = '1 MB', Document_Name__c='Test.PDF', 
        													Envelop_Id__c = '73D3C540-6164-46C6-B669-AE07622FB239',DocuSign_Status__C = 'Sent',
        													Document_Classification__c=classificationObj.Id, Wet_Sign_Status__c= '',
        													Document_Source__c ='eSign', Parent_Proposal_Name__c=proposal.Name);
        insert srAttachment;		
		
	 	Test.startTest();
			Test.setMock(HttpCalloutMock.class, new DocuSignInpersonUrlMockResponse());		
			BaseApiTest.setRequest('/v2/eSign/inPersonUrl');
			BaseApiTest.setParam('envelopeId', '73D3C540-6164-46C6-B669-AE07622FB239');
			BaseApiTest.setParam('recipient', '1');
			BaseApiTest.setParam('proposalId', proposal.name);
	        DocusignApiInpersonUrlEndpoint.httpGet();
			JsonReader reader = BaseApiTest.assertSuccessResponse();
			System.debug('reader: ' + reader);
			System.assertNotEquals(null, reader.getString('url'));
		Test.stopTest();

    }
	

    testmethod public static void testDocuSignInitiateInpersonSignature() {
        insertSettings();
        
		//Test required parameter (proposal id) test
		BaseApiTest.setRequest('/v2/eSign', '{"action" : "initiate","documentType" : "Customer Agreement","proposalId" : "PK1234-J","eSignatureType" : "INPERSON"}');
		DocusignApiESignEndpoint.httpPost();
		BaseApiTest.assertErrorResponse(400, RestServiceDto.Error_InvalidRequest);
        
        //Insert a proposal and try to get it.
		Account acct = new Account(Name='Foo', RecordTypeId=utils.getRecordTypeId('Account', 'Partner'), 
			BillingCity='Dublin',
			Office_Location__c  = 'Headquarters',
			Stage__c = 'Confirmed',
			Active__c  = true);
        insert acct;
        
        Opportunity opty1 = new Opportunity(Name='Test', StageName='Stage', CloseDate=Date.today());
        insert opty1;

        //With sync disabled, insert proposal and it should not create sync records.
        Proposal__c proposal = new Proposal__c(Mode_Name__c='Mode', Opportunity__c=opty1.id,
			Sales_Rep_Email__c='test@yopmail.com', stage__c='Created', Date_Issued__c=Date.today(), System_Size_STC_DC__c=10.0, Upfront_Payment__c=00.0);
        insert proposal;
        proposal = (Proposal__c) utils.queryAllFields(proposal.id);
        
        System.debug('proposal: ' + proposal);
		Document_Classification__c classificationObj = [Select Id, Document_Name__c from Document_Classification__c where Document_Name__c = 'Customer Agreement'];
        SR_Attachment__c srAttachment = new SR_Attachment__c(proposal__c=proposal.Id, Document_Name_On_File_Server__c='Test.PDF', DocuSign_Status__C = 'Sent',
															active__c=true,size__c = '1 MB', Document_Name__c='Test.PDF', Envelop_Id__c = '',
															Document_Classification__c=classificationObj.Id, Wet_Sign_Status__c= '',Proposal_Source__C= ProposalUtil.BLACK_BIRD,
        													Document_Source__c ='Proposal Tool', Parent_Proposal_Name__c=proposal.Name);
        insert srAttachment;		
		BaseApiTest.setRequest('/v2/eSign', '{"action" : "initiate","documentType" : "Customer Agreement","proposalId" : "'+ proposal.name + '","eSignatureType" : "INPERSON"}');
		DocusignApiESignEndpoint.httpPost();
		JsonReader reader = BaseApiTest.assertSuccessResponse();
		System.debug('reader: ' + reader);
		System.assertNotEquals(null, reader.getString('envelopeId'));
	}


    testmethod public static void testDocuSignVoidESignature1() {
        insertSettings();
        
		//Test required parameter (proposal id) test
		BaseApiTest.setRequest('/v2/eSign', '{"action" : "void","documentType" : "Customer Agreement","proposalId" : "PK12345-H","eSignatureType" : "EMAIL"}');
		DocusignApiESignEndpoint.httpPost();
		//BaseApiTest.assertErrorResponse(500, RestServiceDto.Unable_To_Process_Request);
        
        //Insert a proposal and try to get it.
		Account acct = new Account(Name='Foo', RecordTypeId=utils.getRecordTypeId('Account', 'Partner'), 
			BillingCity='Dublin',
			Office_Location__c  = 'Headquarters',
			Stage__c = 'Confirmed',
			Active__c  = true);
        insert acct;
        Opportunity opty1 = new Opportunity(Name='Test', StageName='Stage', CloseDate=Date.today());
        insert opty1;

        Proposal__c proposal = new Proposal__c(Mode_Name__c='Mode', Opportunity__c=opty1.id,
												Sales_Rep_Email__c='test@yopmail.com', stage__c=EDPUtil.PENDING_TASK_COMPLETED, 
												Sales_Partner__c=Label.Sunrun_Inc_Id, Install_Partner__c=Label.Sunrun_Inc_Id,
												Change_Order_Information__c=ProposalUtil.FULL_PROPOSAL,
												Proposal_Source__C= ProposalUtil.BLACK_BIRD,
												Date_Issued__c=Date.today(), System_Size_STC_DC__c=10.0, Upfront_Payment__c=00.0);
        insert proposal;
        proposal = (Proposal__c) utils.queryAllFields(proposal.id);
        
        System.debug('proposal: ' + proposal);
		Document_Classification__c classificationObj = [Select Id, Document_Name__c from Document_Classification__c where Document_Name__c = 'Customer Agreement'];
        SR_Attachment__c srAttachment = new SR_Attachment__c(proposal__c=proposal.Id, Document_Name_On_File_Server__c='Test.PDF', 
															active__c=true, size__c = '1 MB', Document_Name__c='Test.PDF', 
        													Envelop_Id__c = '73D3C540-6164-46C6-B669-AE07622FB239',DocuSign_Status__C = 'Sent',
        													Document_Classification__c=classificationObj.Id, Wet_Sign_Status__c= '',
        													Proposal_Source__C= ProposalUtil.BLACK_BIRD,
															Document_Source__c ='eSign', Parent_Proposal_Name__c=proposal.Name);
        
        insert srAttachment;		
		BaseApiTest.setRequest('/v2/eSign', '{"action" : "void","documentType" : "Customer Agreement","proposalId" : "'+ proposal.name + '","eSignatureType" : "EMAIL"}');
		DocusignApiESignEndpoint.httpPost();
		JsonReader reader = BaseApiTest.assertSuccessResponse();
    }

    testmethod public static void testDocuSignVoidESignature2() {
        insertSettings();

        //Insert a proposal and try to get it.
		Account acct = new Account(Name='Foo', RecordTypeId=utils.getRecordTypeId('Account', 'Partner'), 
			BillingCity='Dublin',
			Office_Location__c  = 'Headquarters',
			Stage__c = 'Confirmed',
			Active__c  = true);
        insert acct;
        
        Opportunity opty1 = new Opportunity(Name='Test', StageName='Stage', CloseDate=Date.today());
        insert opty1;

        //With sync disabled, insert proposal and it should not create sync records.
        Proposal__c proposal = new Proposal__c(Mode_Name__c='Mode', Opportunity__c=opty1.id,
												Sales_Rep_Email__c='test@yopmail.com', stage__c=EDPUtil.SR_DECLINED, 
												Change_Order_Information__c=ProposalUtil.FULL_PROPOSAL,
												Sales_Partner__c=Label.Sunrun_Inc_Id, Install_Partner__c=Label.Sunrun_Inc_Id,
												Proposal_Source__C= ProposalUtil.BLACK_BIRD,
												Date_Issued__c=Date.today(), System_Size_STC_DC__c=10.0, Upfront_Payment__c=00.0);
        insert proposal;
        proposal = (Proposal__c) utils.queryAllFields(proposal.id);
        
        System.debug('proposal: ' + proposal);
		Document_Classification__c classificationObj = [Select Id, Document_Name__c from Document_Classification__c where Document_Name__c = 'Customer Agreement'];
        SR_Attachment__c srAttachment = new SR_Attachment__c(proposal__c=proposal.Id, Document_Name_On_File_Server__c='Test.PDF', 
															active__c=true, size__c = '1 MB', Document_Name__c='Test.PDF', 
        													Envelop_Id__c = '73D3C540-6164-46C6-B669-AE07622FB239',DocuSign_Status__C = 'Sent',
        													Document_Classification__c=classificationObj.Id, Wet_Sign_Status__c= '',
        													Proposal_Source__C= ProposalUtil.BLACK_BIRD,
															Document_Source__c ='eSign', Parent_Proposal_Name__c=proposal.Name);
        
        insert srAttachment;		
		BaseApiTest.setRequest('/v2/eSign', '{"action" : "void","documentType" : "Customer Agreement","proposalId" : "'+ proposal.name + '","eSignatureType" : "EMAIL"}');
		DocusignApiESignEndpoint.httpPost();
    }

	testmethod public static void testDocuSignEsignInputs() {
        insertSettings();
		Account acct = new Account(Name='Foo', RecordTypeId=utils.getRecordTypeId('Account', 'Partner'), 
			BillingCity='Dublin',
			Office_Location__c  = 'Headquarters',
			Stage__c = 'Confirmed',
			Active__c  = true);
        insert acct;
        
        Opportunity opty1 = new Opportunity(Name='Test', StageName='Stage', CloseDate=Date.today());
        insert opty1;

        //With sync disabled, insert proposal and it should not create sync records.
        Proposal__c proposal = new Proposal__c(Mode_Name__c='Mode', Opportunity__c=opty1.id,
												Sales_Rep_Email__c='test@yopmail.com', stage__c=EDPUtil.SR_DECLINED, 
												Change_Order_Information__c=ProposalUtil.FULL_PROPOSAL,
												Sales_Partner__c=Label.Sunrun_Inc_Id, Install_Partner__c=Label.Sunrun_Inc_Id,
												Proposal_Source__C= ProposalUtil.BLACK_BIRD,
												Date_Issued__c=Date.today(), System_Size_STC_DC__c=10.0, Upfront_Payment__c=00.0);
        insert proposal;
        proposal = (Proposal__c) utils.queryAllFields(proposal.id);
        
		BaseApiTest.setRequest('/v2/eSign', '{"action" : "","documentType" : "Customer Agreement","proposalId" : "'+ proposal.name + ',","eSignatureType" : "EMAIL"}');
		DocusignApiESignEndpoint.httpPost();
		BaseApiTest.assertErrorResponse(400, RestServiceDto.Error_RequiredFieldsMissing);

		BaseApiTest.setRequest('/v2/eSign', '{"action" : "Initiate","documentType" : "","proposalId" : "'+ proposal.name + ',"eSignatureType" : "EMAIL"}');
		DocusignApiESignEndpoint.httpPost();
		BaseApiTest.assertErrorResponse(400, RestServiceDto.Error_InvalidRequest);
		
		BaseApiTest.setRequest('/v2/eSign', '{"action" : "Initiate","documentType" : "Customer Agreement","proposalId" : "","eSignatureType" : "EMAIL"}');
		DocusignApiESignEndpoint.httpPost();
		BaseApiTest.assertErrorResponse(400, RestServiceDto.Error_RequiredFieldsMissing);

		BaseApiTest.setRequest('/v2/eSign', '{"action" : "Initiate","documentType" : "Customer Agreement","proposalId" : "'+ proposal.name + ',","eSignatureType" : ""}');
		DocusignApiESignEndpoint.httpPost();
		BaseApiTest.assertErrorResponse(400, RestServiceDto.Error_InvalidRequest);

        System.debug('proposal: ' + proposal);
		Document_Classification__c classificationObj = [Select Id, Document_Name__c from Document_Classification__c where Document_Name__c = 'Customer Agreement'];
        SR_Attachment__c srAttachment = new SR_Attachment__c(proposal__c=proposal.Id, Document_Name_On_File_Server__c='Test.PDF', 
															active__c=true, size__c = '1 MB', Document_Name__c='Test.PDF', 
        													Envelop_Id__c = '73D3C540-6164-46C6-B669-AE07622FB239',DocuSign_Status__C = 'Sent',
        													Document_Classification__c=classificationObj.Id, Wet_Sign_Status__c= '',
        													Proposal_Source__C= ProposalUtil.BLACK_BIRD,
															Document_Source__c ='eSign', Parent_Proposal_Name__c=proposal.Name);
        
        insert srAttachment;
		BaseApiTest.setRequest('/v2/eSign', '{"action" : "Initiate","documentType" : "Customer Agreement","proposalId" : "'+ proposal.name + ',","eSignatureType" : "Inperson"}');
		DocusignApiESignEndpoint.httpPost();
		BaseApiTest.assertErrorResponse(400, RestServiceDto.Error_InvalidRequest);
	}
	
    static void insertSettings() {
        RestServiceDto.insertFieldMapping('Proposal Api', 'Proposal__c', 'salesRepEmail=Sales_Rep_Email__c');
    }
}