SFDCProject/src/objects/Document_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Document_Name__c</fullName>
        <externalId>true</externalId>
        <label>Document Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Document Classification</label>
    <nameField>
        <label>Document_Classification_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EDP_Phase__c</fullName>
        <label>EDP_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>EDP Phase-0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDP Phase-1</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Install_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposal_ID__c</fullName>
        <description>The proposal identification number.</description>
        <label>Proposal ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals (Sales Partner)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/SR_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DocuSign_Status__c</fullName>
        <label>DocuSign Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wet Signed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Classification__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Document Classification</label>
        <referenceTo>Document_Classification__c</referenceTo>
        <relationshipLabel>SR Attachments</relationshipLabel>
        <relationshipName>SR_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Name_On_File_Server__c</fullName>
        <label>Document Name on File Server</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Source__c</fullName>
        <label>Document Source</label>
        <picklist>
            <picklistValues>
                <fullName>Proposal Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Upload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eSign</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Envelop_Id__c</fullName>
        <externalId>true</externalId>
        <label>Envelop Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>SR_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>SR_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>SR Attachments</relationshipLabel>
        <relationshipName>SR_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wet_Sign_Status__c</fullName>
        <description>This Field used to Specify the status whether signature is required or not</description>
        <label>Wet Signature Status</label>
        <picklist>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SR Attachment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SR Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/UnitTest_ProposalUtil.cls
@isTest(SeeAllData=true)
public class UnitTest_ProposalUtil {
    
	public static void disableExternalServices(){
		/*
	 	Sf.settingsService.setString('AddressStandardizationForAcctsEnabled', 'false'); 
	 	Sf.settingsService.setString('AddressStandardizationForLeadsEnabled', 'false'); 
	 	Sf.settingsService.setString('AmbassadorRealtimeSyncEnabled', 'false'); 
	 	Sf.settingsService.setString('AwsOptysSqsSyncEnabled', 'false'); 
	 	Sf.settingsService.setString('AwsOptysSqsRealtimeSyncEnabled', 'false'); 
	 	Sf.settingsService.setString('AwsLeadsSqsSyncEnabled', 'false'); 
	 	Sf.settingsService.setString('AwsLeadsSqsRealtimeSyncEnabled', 'false'); 
	 	Sf.settingsService.setString('SobjectAuditCaptureEnabled', 'false'); 
	 	*/
	 	Sf.settingsService.setString('AwsSqsLeadsSyncEnabled', 'false'); 
	 	Sf.settingsService.setString('AwsSqsOptysSyncEnabled', 'false'); 
	 	Sf.settingsService.setString('AwsSqsContractsSyncEnabled', 'false'); 
	 	Sf.settingsService.setString('AwsSqsProposalsSyncEnabled', 'false'); 
	 	Sf.settingsService.setString('AwsSqsPaymentsSyncEnabled', 'false'); 
	 	Sf.settingsService.setString('AwsSqsCreditsSyncEnabled', 'false'); 

	}
    
    public static dsfs__DocuSign_Status__c CreateDocuSignStatus(String envelopId, String status) {
        dsfs__DocuSign_Status__c docuSignStatusObj = new dsfs__DocuSign_Status__c();
        docuSignStatusObj.dsfs__DocuSign_Envelope_ID__c = envelopId;
        docuSignStatusObj.dsfs__Envelope_Status__c = status;
        return  docuSignStatusObj;
    }

    public static dsfs__DocuSign_Recipient_Status__c CreateDocuSignRecipientStatus(String docuSignStatusId, String envelopId, String recipientId, 
                                                                                    String recipientEmail, String status) {
        dsfs__DocuSign_Recipient_Status__c docuSignRecipientStatusObj = new dsfs__DocuSign_Recipient_Status__c();
        docuSignRecipientStatusObj.dsfs__Envelope_Id__c = envelopId;
        docuSignRecipientStatusObj.dsfs__DocuSign_Recipient_Id__c = recipientId;
        docuSignRecipientStatusObj.dsfs__DocuSign_Recipient_Email__c = recipientEmail;
        docuSignRecipientStatusObj.dsfs__Recipient_Status__c = status;
        docuSignRecipientStatusObj.dsfs__Parent_Status_Record__c = docuSignStatusId;
        return  docuSignRecipientStatusObj;
    }
    

    public static Proposal__c createProposal(String accountName, String firstName, String lastName, 
                                            String customerEmail, String opptyName, String ProposalName, 
                                            Integer proposalId, Decimal proposalLimit, String modeValue,
                                            String salesRepEmail, String salesPartnerId, String installPartnerId,
                                            Account accountObj, Contact primaryContact, Contact secondaryContact, 
                                            Opportunity oppotyObj){
        
        System.debug('salesRepEmail: ' + salesRepEmail);
        System.debug('salesPartnerId: ' + salesPartnerId);
        System.debug('installPartnerId: ' + installPartnerId);
        
        Proposal__C proposalObj = new Proposal__C();
        accountObj = TestPRMLibrary.insertAccount(accountName, 'Residential');
        primaryContact = TestPRMLibrary.insertContact(accountObj.Id, 'Residential', firstName+ '-1', lastName+'-1', 'first.' + customerEmail);
        secondaryContact = TestPRMLibrary.insertContact(accountObj.Id, 'Residential', firstName+ '-2', lastName+'-2', 'second.' + customerEmail);
        oppotyObj = TestPRMLibrary.insertOpportunity(accountObj.Id, opptyName, 'Platinum');

        proposalObj.Name = ProposalName;
        proposalObj.Opportunity__c = oppotyObj.Id;
        proposalObj.Upfront_Payment__c = 1000;
        proposalObj.Proposal_ID__c = proposalId;
        proposalObj.System_Size_STC_DC__c = proposalLimit;
        proposalObj.Mode_Name__c = modeValue;
        proposalObj.Date_Issued__c =  date.today();
        proposalObj.Sales_Rep_Email__c = salesRepEmail; 
        proposalObj.Sales_Partner__c = salesPartnerId;
        proposalObj.Install_Partner__c = installPartnerId;
        proposalObj.EDP_Phase__c = 'EDP Phase-1';
        System.debug('salesPartnerId: ' + salesPartnerId);
        System.debug('installPartnerId: ' + installPartnerId);
        return proposalObj;
    }

 
    public static SR_Attachment__c CreateOptySRAttachment(Id optyId) {
        SR_Attachment__c srAttachmentObj = new SR_Attachment__c();
        srAttachmentObj.Active__c = true;
        srAttachmentObj.Opportunity__c = optyId;
        srAttachmentObj.DocuSign_Status__c = '';
        srAttachmentObj.Envelop_Id__c = '';
        srAttachmentObj.Wet_Sign_Status__c = '';
        srAttachmentObj.Document_Classification__c = '';
        return srAttachmentObj;
    }

    
    public static SR_Attachment__c CreateSRAttachment(Id proposalId) {
        SR_Attachment__c srAttachmentObj = new SR_Attachment__c();
        srAttachmentObj.Active__c = true;
        srAttachmentObj.Proposal__c = proposalId;
        srAttachmentObj.DocuSign_Status__c = '';
        srAttachmentObj.Envelop_Id__c = '';
        srAttachmentObj.Wet_Sign_Status__c = '';
        srAttachmentObj.Document_Classification__c = '';
        return srAttachmentObj;
    }


    public static SR_Attachment__c CreateSCSRAttachment(String documentTypeName, String optyId,String documentName, String documentSource) {
        Map<String, Document_Classification__c> documentClassificationMap = EDPDocumentSettings.getDocumentSettingsInformation();
        System.debug('documentClassificationMap: ' + documentClassificationMap);
        Document_Classification__c documentClassificationObj = documentClassificationMap.get(documentTypeName);
        SR_Attachment__c srAttachmentObj = new SR_Attachment__c();
        srAttachmentObj.Active__c = true;
        srAttachmentObj.DocuSign_Status__c = '';
        srAttachmentObj.Wet_Sign_Status__c = '';
        srAttachmentObj.Document_Classification__c = documentClassificationObj.Id;
        srAttachmentObj.Document_Source__c = documentSource;
        srAttachmentObj.Document_Name__c = documentName;
        srAttachmentObj.Document_Name_On_File_Server__c = documentName;
        srAttachmentObj.Service_Contract__c = optyId;
        return srAttachmentObj;
    }

    public static SR_Attachment__c CreateOptySRAttachment(String documentTypeName, String optyId,String documentName, String documentSource) {
        Map<String, Document_Classification__c> documentClassificationMap = EDPDocumentSettings.getDocumentSettingsInformation();
        System.debug('documentClassificationMap: ' + documentClassificationMap);
        Document_Classification__c documentClassificationObj = documentClassificationMap.get(documentTypeName);
        SR_Attachment__c srAttachmentObj = new SR_Attachment__c();
        srAttachmentObj.Active__c = true;
        srAttachmentObj.DocuSign_Status__c = '';
        srAttachmentObj.Wet_Sign_Status__c = '';
        srAttachmentObj.Document_Classification__c = documentClassificationObj.Id;
        srAttachmentObj.Document_Source__c = documentSource;
        srAttachmentObj.Document_Name__c = documentName;
        srAttachmentObj.Document_Name_On_File_Server__c = documentName;
        srAttachmentObj.Opportunity__c = optyId;
        return srAttachmentObj;
    }

    public static SR_Attachment__c CreateSRAttachment(String documentTypeName, String envelopId, String proposalId, 
                                                    String documentName, String documentSource) {
        Map<String, Document_Classification__c> documentClassificationMap = EDPDocumentSettings.getDocumentSettingsInformation();
        System.debug('documentClassificationMap: ' + documentClassificationMap);
        Document_Classification__c documentClassificationObj = documentClassificationMap.get(documentTypeName);
        SR_Attachment__c srAttachmentObj = new SR_Attachment__c();
        srAttachmentObj.Active__c = true;
        srAttachmentObj.DocuSign_Status__c = '';
        srAttachmentObj.Wet_Sign_Status__c = '';
        srAttachmentObj.Document_Classification__c = documentClassificationObj.Id;
        srAttachmentObj.Document_Source__c = documentSource;
        srAttachmentObj.Envelop_Id__c = envelopId;
        srAttachmentObj.Document_Name__c = documentName;
        srAttachmentObj.Document_Name_On_File_Server__c = documentName;
        srAttachmentObj.proposal__C = proposalId;
        return srAttachmentObj;
    }
    
    public static Proposal__C getProposalObject(String optyId, String proposalName, Integer proposalId, Decimal proposalLimit,
                                                String modeValue, String salesRepEmail){
        Proposal__C proposalObj1 = new Proposal__C();
        proposalObj1.Name = proposalName;
        proposalObj1.Opportunity__c = optyId;
        proposalObj1.Upfront_Payment__c = 1000;
        proposalObj1.Proposal_ID__c = proposalId;
        proposalObj1.System_Size_STC_DC__c = proposalLimit;
        proposalObj1.Mode_Name__c = modeValue;
        proposalObj1.Date_Issued__c =  date.today();
        proposalObj1.Sales_Rep_Email__c = salesRepEmail;
        proposalObj1.EDP_Phase__c = 'EDP Phase-1';
        return proposalObj1;        
    }
    

   
    
    

}