SFDCProject/src/objects/Document_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Document_Name__c</fullName>
        <externalId>true</externalId>
        <label>Document Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Document Classification</label>
    <nameField>
        <label>Document_Classification_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Partner_Document_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Customer_signature_required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer signature required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Document_Classification__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Document Classification</label>
        <referenceTo>Document_Classification__c</referenceTo>
        <relationshipLabel>Partner Document Relationships</relationshipLabel>
        <relationshipName>Partner_Document_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mandatory_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mandatory Document</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_signature_required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner signature required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SR_Ops_signature_required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SR Ops signature required</label>
        <type>Checkbox</type>
    </fields>
    <label>Partner Document Relationship</label>
    <nameField>
        <label>Partner Document Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Document Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Install_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals (Sales Partner)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/SR_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>DocuSign_Error_Code__c</fullName>
        <label>DocuSign Error Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocuSign_Error_Message__c</fullName>
        <label>DocuSign Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DocuSign_Status__c</fullName>
        <label>DocuSign Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wet Signed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Classification__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Document Classification</label>
        <referenceTo>Document_Classification__c</referenceTo>
        <relationshipLabel>SR Attachments</relationshipLabel>
        <relationshipName>SR_Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type_Name__c</fullName>
        <formula>Document_Classification__r.Document_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Document Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Envelop_Id__c</fullName>
        <externalId>true</externalId>
        <label>Envelop Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>SR_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>SR_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SR Attachment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SR Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/DocusignApiPutESignHandler.cls
public class DocusignApiPutESignHandler extends ProposalBaseHandler{

	override public String getApiName() {
        return 'eSign';
    }

	public void validateRequest(RestServiceDto.Request req) {
        List<String> requriedFields = new List<String>();
        requriedFields.add('proposalId');
        requriedFields.add('action');
		validateRequiredFields(requriedFields, req);
	}

    override public void handleRequest(RestServiceDto.Request req, RestServiceDto.Response resp) {
		String testMode = req.jsonReader.getString('testMode');
		resp.jsonWriter = new JsonWriter(true);
		
		validateRequest(req);
			
		String proposalName = req.jsonReader.getString('proposalId');
		String action = req.jsonReader.getString('action');
		String documentType = req.jsonReader.getString('documentType');
		String eSignOption = req.jsonReader.getString('eSignatureType');

		Map<String, Document_Classification__c> documentClassificationMap = EDPDocumentSettings.getDocumentClassificationByName();
		Proposal__c proposalObj = getProposalByName(proposalName);
		
		if(documentClassificationMap == null || !documentClassificationMap.containskey(documentType)){
        	throw createBusinessException(RestServiceDto.Error_InvalidRequest, 'Invalid document type ['+ documentType +']');
		}

		if(action != 'initiate' && action != 'void'){
			throw createBusinessException(RestServiceDto.Error_InvalidRequest, 'Invalid action ['+ action +']. Valid action values are \'initiate\', \'void\'');
		}
		if(eSignOption != 'INPERSON' && eSignOption != 'EMAIL'){
			throw createBusinessException(RestServiceDto.Error_InvalidRequest, 'Invalid eSignatureType ['+ eSignOption +']. Valid eSignatureType values are \'INPERSON\', \'EMAIL\'');
		}

		if(proposalObj == null){
			throw createBusinessException(RestServiceDto.Error_InvalidRequest, 'Invalid proposalId ['+ proposalName +']');
		}
					
		Document_Classification__c docClassificationObj = documentClassificationMap.get(documentType);
		if(action == 'initiate'){
			initiateESignature(proposalObj, docClassificationObj, eSignOption ,resp);
		}else if(action == 'void'){
			voidESignature(proposalObj, docClassificationObj, resp);
		}

    }
    
    public void voidESignature(Proposal__c proposalObj, Document_Classification__c docClassificationObj, RestServiceDto.Response resp){
		
		SR_Attachment__c srAttachmentObj = getSRAttachmentWithEnvelopId(proposalObj.Id, docClassificationObj.Id);
		if(srAttachmentObj == null || srAttachmentObj.Envelop_Id__c == null || 
			srAttachmentObj.Envelop_Id__c == '' || srAttachmentObj.DocuSign_Status__c == 'Voided'){
            throw createBusinessException(RestServiceDto.Error_ValidationError,  'No eSignatures are pending for the Proposal [' + proposalObj.name + '] ');               
		}		
		String voidResult = validateAndExecuteVoidRequest(srAttachmentObj);
		System.debug('voidResult: ' + voidResult);
		if(voidResult != null){
			resp.jsonWriter.write('Void Result', voidResult);   
		}
		   	
    }

	public String validateAndExecuteVoidRequest(SR_Attachment__c srAttachment){
		String result = 'SUCCESS';
		Set<String> proposalStagesAllowedForVoid = new Set<String>();
        Set<String> proposalStagesNotAllowedForVoid = new Set<String>();
        Set<String> proposalStagesForConditionalVoid = new Set<String>();
        
        proposalStagesNotAllowedForVoid.add(EDPUtil.REPLACED_BY);
        proposalStagesNotAllowedForVoid.add(EDPUtil.WITH_DRAWN);
        proposalStagesNotAllowedForVoid.add(EDPUtil.SR_OPS_APPROVED);
        proposalStagesNotAllowedForVoid.add(EDPUtil.SR_DECLINED);
        proposalStagesNotAllowedForVoid.add(EDPUtil.EXPIRED);
        
        proposalStagesAllowedForVoid.add(EDPUtil.CREATED);
        proposalStagesAllowedForVoid.add(EDPUtil.ON_HOLD);
        proposalStagesAllowedForVoid.add(EDPUtil.PENDING);
        proposalStagesAllowedForVoid.add(EDPUtil.READY_FOR_SUBMISSION);

        proposalStagesForConditionalVoid.add(EDPUtil.SUBMITTED);
        proposalStagesForConditionalVoid.add(EDPUtil.SR_OPS_RECEIVED);
        proposalStagesForConditionalVoid.add(EDPUtil.SR_OPS_REVIEWED);
        proposalStagesForConditionalVoid.add(EDPUtil.CREDIT_REVIEW);
        proposalStagesForConditionalVoid.add(EDPUtil.CREDIT_APPROVED);
        proposalStagesForConditionalVoid.add(EDPUtil.SR_SIGNOFF_REVIEW);
        proposalStagesForConditionalVoid.add(EDPUtil.PENDING_TASK_COMPLETED);
        
        Set<String> modes = new Set<String>();
        modes.add(EDPUtil.READ);
        modes.add(EDPUtil.EDIT);
		System.debug('srAttachment.proposal__r.stage__c: ' + srAttachment.proposal__r.stage__c);
		Contact contactObj = PRMContactUtil.getLoginUserAccountAndContact();
        if(!String.isEmpty(srAttachment.proposal__r.stage__c)  && contactObj != null && contactObj.Id != null){
            if(proposalStagesForConditionalVoid.contains(srAttachment.proposal__r.stage__c)){
                Map<String, Document_Classification__c> documentClassificationMap;
                documentClassificationMap = EDPDocumentSettings.getDocumentClassificationByCategroy(null,EDPDocumentSettings.MANDATORY_REQUIREMENTS,
                                                                                                    modes, srAttachment.proposal__r.Sales_Partner__c, 
                                                                                                    srAttachment.proposal__r.Install_Partner__c);
                Document_Classification__c documentClassificationObj = documentClassificationMap.get(srAttachment.Document_Type_Name__c);
                
                System.debug('documentClassificationObj: ' + documentClassificationObj);
                Partner_Document_Relationship__c ptrDocRelObj;
                if(documentClassificationObj != null && documentClassificationObj.Partner_Document_Relationships__r != null 
                    && documentClassificationObj.Partner_Document_Relationships__r.size() > 0){
                    ptrDocRelObj = documentClassificationObj.Partner_Document_Relationships__r[0];
                }
                System.debug('ptrDocRelObj: ' + ptrDocRelObj);
                if(ptrDocRelObj != null && ptrDocRelObj.Mandatory_Document__c == true){
                    String errorMessage = 'The proposal is under review and eSign requests can\'t be voided at this time';
					throw createBusinessException(RestServiceDto.Error_ValidationError, errorMessage);                    
                }
            }else if(proposalStagesNotAllowedForVoid.contains(srAttachment.proposal__r.stage__c) || 
                !proposalStagesAllowedForVoid.contains(srAttachment.proposal__r.stage__c)){
                String errorMessage = 'Invalid proposal stage to void the selected document';
				throw createBusinessException(RestServiceDto.Error_ValidationError, errorMessage);               
            } 
        }
		
		if(!Test.isRunningTest()){
			result = eSignServiceNew.voidEnvelopId(srAttachment);
		}else{
			result = 'SUCCESS';
		}
		
		if(result != 'SUCCESS'){
			throw createBusinessException(RestServiceDto.Unable_To_Process_Request, result);        			
		}
		
		try{
			srAttachment.Envelop_Id__c = '';
			srAttachment.DocuSign_Status__c = 'Voided';
			srAttachment.DocuSign_Error_Code__c  = '';
			srAttachment.DocuSign_Error_Message__c = '';
	    	update srAttachment;		
	
			Proposal__c proposalObj = srAttachment.proposal__r;
	        if(ProposalUtil.canUpdateProposalSignedStatus(proposalObj, srAttachment.Document_Type_Name__c) == true){
	            proposalObj.signed__c = false;
	            update  proposalObj;
	        }
		}catch(Exception expObj){
			throw createBusinessException(RestServiceDto.Unable_To_Process_Request, expObj.getMessage()); 
		}
		return result;
	}
	
	public void initiateESignature(Proposal__c proposalObj, Document_Classification__c docClassificationObj, String eSignOption, RestServiceDto.Response resp){

		Contact primaryContact;
		Contact secondaryContact;
		Contact partnerContact;
		String sunrunRecipientName = '';
		String sunrunRecipientEmail = '';
		String hostName = '';
		String hostEmail = '';

		Set<String> docuSignStatus = new Set<String>();
		docuSignStatus.add(EDPUtil.VOIDED);
		docuSignStatus.add(EDPUtil.NOT_SENT);

		String proposalId = proposalObj.Id;
		Map<String, Contact> contactMap = getOptyContacts(proposalObj.Opportunity__c);

		SR_Attachment__c srAttachment = DocuSignUtil.getSRAttachment(proposalObj.Id, docClassificationObj.Document_Name__c);
		if(srAttachment != null && srAttachment.Envelop_Id__c != null && srAttachment.Envelop_Id__c != '' && !docuSignStatus.contains(srAttachment.DocuSign_Status__c)){
			throw createBusinessException(RestServiceDto.Error_ValidationError, 'eSignature request is in progress or completed for the requested document');
		}
		
		String partnerType = EDPUtil.getPartnerType(proposalObj, proposalObj.Sales_Partner__c);
		List<Partner_Document_Relationship__c> partnerDocumentRelationships =  docClassificationObj.Partner_Document_Relationships__r;
		System.debug('partnerDocumentRelationships: ' + partnerDocumentRelationships);
		System.debug('contactMap: ' + contactMap);
		if(partnerDocumentRelationships != null && partnerDocumentRelationships.size() > 0){
			Partner_Document_Relationship__c ptrRelationshipObj = getPartnerDocumentRelationship(partnerDocumentRelationships, partnerType);
			if(ptrRelationshipObj != null && ptrRelationshipObj.SR_Ops_signature_required__c == true){
				sunrunRecipientName = Label.SunRun_DocuSign_User;
				sunrunRecipientEmail = Label.SunRun_DocuSign_Email;					
			}
				
			System.debug('ptrRelationshipObj: ' + ptrRelationshipObj);
			if(ptrRelationshipObj != null && ptrRelationshipObj.Partner_signature_required__c == true){
				Contact loginContact = PRMContactUtil.getLoginUserAccountAndContact();
				System.debug('loginContact: ' + loginContact);
				if(PRMContactUtil.isPartnerContact(loginContact)){
					partnerContact = loginContact;
					hostName = (loginContact.account.DocuSign_Host_Name__c != null) ? loginContact.account.DocuSign_Host_Name__c : '';
					hostEmail = (loginContact.account.DocuSign_Host_Email__c != null) ? loginContact.account.DocuSign_Host_Email__c : '' ;
				}
			}
			if(ptrRelationshipObj != null && ptrRelationshipObj.Customer_signature_required__c == true && contactMap != null){
				if(contactMap.containsKey(HOMEOWNER_PRIMARY)){
					primaryContact = contactMap.get(HOMEOWNER_PRIMARY);
				}else{
					List<Contact> contacts = contactMap.values();
					if(contacts != null && !contacts.isEmpty()){
						primaryContact = contacts[0];
					}
				}					
			}
		}
		
		eSignServiceNew.EnvResponse response;
		if(!Test.isRunningTest()){
			System.debug('hostName: ' + hostName);
			System.debug('hostEmail: ' + hostEmail);
			System.debug('primaryContact: ' + primaryContact);
			System.debug('partnerContact: ' + partnerContact);
			response = eSignServiceNew.sendDocumentsToDocusign(proposalId, docClassificationObj.Document_Name__c, eSignOption, 
																						hostName,hostEmail, primaryContact, secondaryContact, partnerContact, 
																						sunrunRecipientName,sunrunRecipientEmail);
		}else{
			response = new eSignServiceNew.EnvResponse();
			response.envelopeId = '73D3C540-6164-46C6-B669-AE07622FB239';
		}
		
		System.debug('response: ' + response);
		if(String.isEmpty(response.errorCode)){
			resp.jsonWriter.write('envelopeId', response.envelopeId);   
		}else{
			throw createBusinessException(RestServiceDto.Unable_To_Process_Request, response.message);
		}			
	}

}