SFDCProject/src/objects/Facility_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Generation_Asset__c</fullName>
        <label>Generation Asset</label>
        <referenceTo>Generation_Assets__c</referenceTo>
        <relationshipLabel>Facility Configurations</relationshipLabel>
        <relationshipName>Facility_Configurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_Panels__c</fullName>
        <label>Number of Panels</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Panel_Type__c</fullName>
        <label>Panel Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Facility Configuration</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Facility Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Configurations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Generation_Assets__c.object
<CustomObject>
    <description>Generation Assets are energy generating facilities owned by SunRun</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Generation Assets</relationshipLabel>
        <relationshipName>R00N60000001ZOSVEA4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cash_Grant_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cash Grant Pre-Buy Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City where home is located</description>
        <label>City</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cust_Ref_Num__c</fullName>
        <description>Customer number that can be used for outside reference, with partners or customers</description>
        <displayFormat>SRC{YY}{000000}03A</displayFormat>
        <label>Cust Ref Num</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Customer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer contact for this gen asset.</description>
        <inlineHelpText>The customer contact for this gen asset.</inlineHelpText>
        <label>Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Generation Assets</relationshipLabel>
        <relationshipName>Generation_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Home_Address__c</fullName>
        <description>Address for this SunRun home</description>
        <label>Home Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Install_Partner__c</fullName>
        <inlineHelpText>Partner on the install; we use this field here in order to calc the milestone payments correctly</inlineHelpText>
        <label>Install Partner</label>
        <picklist>
            <picklistValues>
                <fullName>1st Light Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A1 Solar Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acro Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Solar Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akeena Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alteris Renewables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Solar - New Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arise Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona Solar Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASI Heating Air &amp; Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Astralux Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonterra Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clean Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY Solar Inc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cotuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTEC Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eco Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green Home Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greenspring Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>groSolar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harmon Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HelioPower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HelioPower Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horizon Solar Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Imagine Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infinity Solar Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Islandwide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verengo</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Sunrun_owned_Modules__c</fullName>
        <label>Number of Sunrun-Owned Panels</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Generation Assets</relationshipLabel>
        <relationshipName>R00N60000001ZOT9EAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SR_Signoff__c</fullName>
        <description>Date SunRun signed off on the customer Agreement</description>
        <inlineHelpText>Date SunRun signed off on the customer Agreement</inlineHelpText>
        <label>SR Signoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SmartTurn_M1_StatusCode__c</fullName>
        <label>SmartTurn M1 StatusCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SmartTurn_Message__c</fullName>
        <label>SmartTurn Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <defaultValue>&quot;CA&quot;</defaultValue>
        <description>State where home is located</description>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Size_DC__c</fullName>
        <label>System Size DC</label>
        <precision>14</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Welcome_Call__c</fullName>
        <inlineHelpText>Date we placed welcome call to customer, confirmed contact info, billing preferences</inlineHelpText>
        <label>Welcome Call</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zip_6__c</fullName>
        <formula>Account_Name__r.Zip_6__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zip+6</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Zip Code</description>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Generation Asset</label>
    <nameField>
        <label>Generation Assets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Generation Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDCProject/src/classes/CallOut2SmartTurn_M1Submit.cls
public with sharing class CallOut2SmartTurn_M1Submit {

    public final Case currentRecord;
    public Case caseRec {get;set;}
    public Generation_Assets__c assetRec {get;set;}
    public String errorPageDetails {get;set;}

    public CallOut2SmartTurn_M1Submit (ApexPages.StandardController stdController) 
    {
        this.currentRecord = (Case) stdController.getRecord();
        if (caseRec == null)
        {
            caseRec = [Select Id, RecordTypeId, Status, Generation_Asset__c, Milestone_Proof_Type__c, SmartTurn_M1_StatusCode__c, SmartTurn_Message__c  From Case Where Id = :currentRecord.Id];
        }
        
        if (assetRec == null && caseRec.Generation_Asset__c != null)
        {
            assetRec = [Select ID, Name, Cust_Ref_Num__c, Home_Address__c, City__c, State__c, Zip__c, Install_Partner__c, Cash_Grant_Eligible__c, 
            				SmartTurn_M1_StatusCode__c, SmartTurn_Message__c, Number_of_Sunrun_owned_Modules__c,
            				(Select Panel_Type__c, Number_of_Panels__c  From Facility_Configurations__r)
            				From Generation_Assets__c Where Id = :caseRec.Generation_Asset__c];
        }
        errorPageDetails = System.currentPageReference().getParameters().get('msg') ;
        if (errorPageDetails == null)
            errorPageDetails = '';
    }

    public PageReference submitM1()
    {
        String crlf = '\r\n';
        
		Facility_Configuration__c[] panelList = assetRec.Facility_Configurations__r;
		
//		if ((panelList == null || panelList.size() <= 0) || caseRec.Milestone_Proof_Type__c != 'M1 Proof' || 
//			caseRec.Status != 'M1 Proof Approved' || caseRec.SmartTurn_M1_StatusCode__c == 'SUCCESS' || assetRec.Cash_Grant_Eligible__c == false)
		if ((panelList == null || panelList.size() <= 0) || caseRec.Milestone_Proof_Type__c != 'M1 Proof' || 
			caseRec.Status != 'M1 Proof Approved' || assetRec.Cash_Grant_Eligible__c == false)
		{
			errorPageDetails += 'The following validations failed before Submitting M1 details to SmartTurn: ' + crlf  + crlf; 

			if (assetRec.Cash_Grant_Eligible__c == false)
			{
				errorPageDetails += 'Cash Grant Pre-Buy Eligible is NOT checked in the Generation Asset'  + crlf + crlf;
			}		
			if (panelList == null || panelList.size() <= 0)
			{
				errorPageDetails += 'Facility Configuration (Panel Details) not found for the Generation Asset'  + crlf + crlf;
			}		
			if (caseRec.SmartTurn_M1_StatusCode__c == 'SUCCESS')
			{
				errorPageDetails += 'M1 already Submitted to SmartTurn for this Generation Asset'  + crlf + crlf;
			}		
			if (caseRec.Milestone_Proof_Type__c != 'M1 Proof')
			{
				errorPageDetails += 'Only M1 Proofs can be submitted to SmartTurn using this option'  + crlf + crlf;
			}		
			if (caseRec.Status != 'M1 Proof Approved')
			{
				errorPageDetails += 'Case is not in M1 Proof Approved Status.'  + crlf;
			}		
		}

        if (errorPageDetails == '')
        {
	        SmartTurn_OccamService.OccamService smartTurnService = new SmartTurn_OccamService.OccamService();
	        smartTurnService.timeout_x = 60000;
	        
	        SmartTurn_OccamTypes.OccamPasswordCredential soInCredential = new SmartTurn_OccamTypes.OccamPasswordCredential();
	        soInCredential.UserId = Label.Sunrun_DSG_Email;
	        soInCredential.Password = Label.Sunrun_DSG_Password;
	
	        List<SmartTurn_SalesOrderTypes.SalesOrder> soList = new List<SmartTurn_SalesOrderTypes.SalesOrder>(); 
	        List<SmartTurn_SalesOrderTypes.SalesOrderItem> itemList = new List<SmartTurn_SalesOrderTypes.SalesOrderItem>();
	        
	        SmartTurn_FlexFieldTypes.CustomField[] custFieldList = new SmartTurn_FlexFieldTypes.CustomField[1];
	        SmartTurn_FlexFieldTypes.CustomFields custFields = new SmartTurn_FlexFieldTypes.CustomFields();
			SmartTurn_FlexFieldTypes.CustomField custField = new SmartTurn_FlexFieldTypes.CustomField();
			
			custField.name = 'SRH #';
			custField.textValue = assetRec.Name;
			custFieldList[0] = custField;
			
	        custFields.field = custFieldList;


	        SmartTurn_OccamTypes.Address shipTo = new SmartTurn_OccamTypes.Address(); 
	        
	        shipTo.addressLine1 =  assetRec.Home_Address__c;
	        shipTo.city = assetRec.City__c;
	        shipTo.state = assetRec.State__c;
	        shipTo.postalCode = assetRec.Zip__c;
	
	        SmartTurn_OccamTypes.Quantity itemQty= new SmartTurn_OccamTypes.Quantity();
	        itemQty.value = 1.00;
	        itemQty.unitAbbreviation = 'ea';
	
	        SmartTurn_SalesOrderTypes.SalesOrder soRec = new SmartTurn_SalesOrderTypes.SalesOrder();
	        soRec.externalNumber = assetRec.Name;
	        soRec.type_x = 'EXTERNAL';
	        soRec.date_x = date.today();
	        soRec.dateDue = date.today();
	        soRec.customerName = assetRec.Install_Partner__c;
	        soRec.shipToContact = assetRec.Cust_Ref_Num__c;
	        soRec.useShipToAsBillAddress = false;
	        soRec.ShipTo = shipTo;
	        soRec.priority = assetRec.Name;
//	        soRec.soCustomFields = custFields;
	        System.debug('\n\n*** panelList.size '  + panelList.size() + '***\n\n');
	        	       	        
            SmartTurn_SalesOrderTypes.SalesOrderItem soItem = new SmartTurn_SalesOrderTypes.SalesOrderItem();         	       	        
	        for (Facility_Configuration__c panelRec : panelList)
	        {
		        soItem.itemMasterId = panelRec.Panel_Type__c;
		        soItem.orderedQuantity = itemQty;

	        	Decimal panelQty = panelRec.Number_of_Panels__c;

	        	if (panelQty == null || panelQty <= 0)
	        	{
	        		panelQty = 1;
	        	}	        	
	        }
	        
                // BSKY-441: Added for Sunrun-owned Panels (and fixed for BSKY-513)
	            if(assetRec.Number_of_Sunrun_owned_Modules__c != null && assetRec.Number_of_Sunrun_owned_Modules__c > 0)
	            {
	        	   Integer iCount = 0;
	        	   for ( iCount=0; iCount < assetRec.Number_of_Sunrun_owned_Modules__c; iCount++ ) 
	        	   {
	        		  itemList.add(soItem);		
	        	   }
	        	}	        	        
	        
	        System.debug('\n\n*** itemList.size '  + itemList.size() + '***\n\n');
	
	        soRec.item = itemList;
	
	        soList.add(soRec);
	        
	        List<SmartTurn_OccamTypes.UploadResponse> smartTurnSOSaveResponse = null;
	        
	        if (!Test.isRunningTest())
        	{
		        smartTurnSOSaveResponse = smartTurnService.saveSalesOrder(soInCredential, soList);
        	}
	        if (smartTurnSOSaveResponse != null)
	        {
	            System.debug('\n\n*** smartTurnSOSaveResponse.status '  + smartTurnSOSaveResponse[0].status + '***\n\n');
	            
	            if (smartTurnSOSaveResponse[0].status == 'SUCCESS')
	            {
	                errorPageDetails = 'Successfully submitted M1 details to SmartTurn';
	                caseRec.SmartTurn_M1_StatusCode__c = 'SUCCESS';
	                caseRec.SmartTurn_Message__c = null;
	                assetRec.SmartTurn_M1_StatusCode__c = 'SUCCESS';
	                assetRec.SmartTurn_Message__c = null;
	                update caseRec;
	                update assetRec;
	            }
	            else
	            {
	                String[] errorList = smartTurnSOSaveResponse[0].error;
	                String errorCheck = 'A Sales Order with the external id "' + smartTurnSOSaveResponse[0].externalRefId + '" already exists and the Sales Order is not canceled.';
	                
	                if (errorList[0] == errorCheck)
					{
						List<SmartTurn_OccamTypes.UploadResponse> smartTurnOverWriteSOResponse = smartTurnService.overwriteSalesOrder(soInCredential, soList);
			    
			            if (smartTurnOverWriteSOResponse[0].status == 'SUCCESS')
			            {
			                errorPageDetails = 'Successfully submitted M1 details to SmartTurn';
			                caseRec.SmartTurn_M1_StatusCode__c = 'SUCCESS';
			                caseRec.SmartTurn_Message__c = null;
			                assetRec.SmartTurn_M1_StatusCode__c = 'SUCCESS';
			                assetRec.SmartTurn_Message__c = null;
			                update caseRec;
			                update assetRec;
			            }
						else
						{
							String[] errorList2 = smartTurnOverWriteSOResponse[0].error;
			                errorPageDetails = 'Error from SmartTurn : ' + errorList2[0];
			                caseRec.SmartTurn_M1_StatusCode__c = 'FAILURE';
			                caseRec.SmartTurn_Message__c = errorList2[0];
			                assetRec.SmartTurn_M1_StatusCode__c = 'FAILURE';
			                assetRec.SmartTurn_Message__c = errorList2[0];
			                update caseRec;
			                update assetRec;
						}
					}
	                else
	                {
		                errorPageDetails = 'Error from SmartTurn : ' + errorList[0];
		                caseRec.SmartTurn_M1_StatusCode__c = 'FAILURE';
		                caseRec.SmartTurn_Message__c = errorList[0];
		                assetRec.SmartTurn_M1_StatusCode__c = 'FAILURE';
		                assetRec.SmartTurn_Message__c = errorList[0];
		                update caseRec;
		                update assetRec;
	                }	                
	            }
	        }
	        else
	        {
	            caseRec.SmartTurn_M1_StatusCode__c = 'FAILURE';
	            caseRec.SmartTurn_Message__c = 'No response from SmartTurn';
	            
	            assetRec.SmartTurn_M1_StatusCode__c = 'FAILURE';
	            assetRec.SmartTurn_Message__c = 'No response from SmartTurn';
	            
	            update caseRec;
	            update assetRec;
	        }
        	
        }
        PageReference retPage = Page.CallOut2SmartTurn_Submit_M1_Conf;
        retPage.setRedirect(true);
        retPage.getParameters().put('id',caseRec.id);
        retPage.getParameters().put('msg', errorPageDetails);
        return retPage;
    }
    
   static testmethod void testCallOut2SmartTurn_M1Submit(){
    //
    Account a = new Account(name='Test Source',Zip_6__c='12345123456');
    insert a;
    //
    Opportunity Opp = new Opportunity();
    Opp.Name = 'TestOppty';
    Opp.StageName = 'Qualified';
    Opp.CloseDate = Date.Today().addDays(18);    
    Opp.AccountId = a.Id;
    insert Opp; 
    //Contact
    List<Contact> listCon = new List<Contact>();
    Contact con = new Contact();
    con.AccountId = a.Id;
    con.LastName = 'Smith';
    con.FirstName = 'Smitty';
    con.Email = 'Smith@smitty.com.xyz';
    insert con;
    //
    List<Generation_Assets__c> listGA = new List<Generation_Assets__c>();
    Generation_Assets__c ga = new Generation_Assets__c();
    ga.Opportunity_Name__c = Opp.Id;
    ga.Name = '99999';
    ga.Home_Address__c = '123 Main St';
    ga.City__c = 'Sunrunville';
    ga.Zip__c = '12345';
    ga.Customer_Contact__c = con.Id;
    ga.Account_Name__c = a.Id;
    ga.Welcome_Call__c = Date.Today();
    ga.SR_Signoff__c = Date.Today().addDays(-19);   
    ga.Home_Address__c = '160 Happy Path';
    ga.City__c = 'San Clownita';
    ga.State__c = 'CA';
    ga.Zip__c = '99999';
    ga.Install_Partner__c = 'Verengo';
    ga.Cash_Grant_Eligible__c = true;
    ga.SmartTurn_M1_StatusCode__c = '';
    ga.SmartTurn_Message__c = '';
    ga.Number_of_Sunrun_owned_Modules__c = 10;
    ga.System_Size_DC__c = 2.45;
    listGA.add(ga);
    Generation_Assets__c ga2 = new Generation_Assets__c();
    ga2.Opportunity_Name__c = Opp.Id;
    ga2.Name = '99999';
    ga2.Home_Address__c = '123 Main St';
    ga2.City__c = 'Sunrunville';
    ga2.Zip__c = '12345';
    ga2.Customer_Contact__c = con.Id;
    ga2.Account_Name__c = a.Id;
    ga2.Welcome_Call__c = Date.Today();
    ga2.SR_Signoff__c = Date.Today().addDays(-19);   
    ga2.Home_Address__c = '160 Happy Path';
    ga2.City__c = 'San Clownita';
    ga2.State__c = 'CA';
    ga2.Zip__c = '99999';
    ga2.Install_Partner__c = 'Verengo';
    ga2.Cash_Grant_Eligible__c = false;
    ga2.SmartTurn_M1_StatusCode__c = '';
    ga2.SmartTurn_Message__c = '';
    ga2.Number_of_Sunrun_owned_Modules__c = 0;
    ga2.System_Size_DC__c = 0.0;
    listGA.add(ga2);    
    insert listGA;      
    //
    Facility_Configuration__c fc = new Facility_Configuration__c();
    fc.Generation_Asset__c = ga.id;
    fc.Panel_Type__c = 'LG245M1C-G2';
    fc.Number_of_Panels__c = 10;
    insert fc;
    //
    RecordType rt = [select id from RecordType where sObjectType = 'Case' and Name = 'Milestone Proof' LIMIT 1];
    //
    List<Case> listCase = new List<Case>();
    Case c = new Case();
    c.Status = 'M1 Proof Approved';
    c.Generation_Asset__c = ga.id;
    c.Milestone_Proof_Type__c = 'M1 Proof';
    c.SmartTurn_M1_StatusCode__c = '';
    c.SmartTurn_Message__c = '';
    c.RecordTypeId = rt.id;
    listCase.add(c);
    Case c2 = new Case();
    c2.Status = 'M2 Meter Test Approved';
    c2.Generation_Asset__c = ga2.id;
    c2.Milestone_Proof_Type__c = 'M2 Proof';
    c2.SmartTurn_M1_StatusCode__c = '';
    c2.SmartTurn_Message__c = '';
    c2.RecordTypeId = rt.id;
    listCase.add(c2);    
    //
    insert listCase;
    //
    ApexPages.StandardController sc = new ApexPages.StandardController(c);
    CallOut2SmartTurn_M1Submit CO2STM1S = new CallOut2SmartTurn_M1Submit(sc);
    //
    PageReference pr = CO2STM1S.submitM1();
    //
    ApexPages.StandardController sc2 = new ApexPages.StandardController(c2);
    CallOut2SmartTurn_M1Submit CO2STM1S2 = new CallOut2SmartTurn_M1Submit(sc2);
    //
    PageReference pr2 = CO2STM1S2.submitM1();
    //
   }    
}