SFDCProject/src/objects/FS_Dispatch__c.object
<CustomObject>
    <description>Captures information about each instance of a Field Service Dispatch - when a resource is sent to an on-site visit</description>
    <fields>
        <fullName>Case_Priority__c</fullName>
        <formula>text(FS_Parent_Case__r.Priority)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Priority</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <formula>text(FS_Parent_Case__r.Reason )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Reason</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_City__c</fullName>
        <description>City of the Generation Asset</description>
        <formula>FS_Service_Contract__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Customer_Name__c</fullName>
        <description>First and last name of the Case Contact</description>
        <formula>TRIM(  FS_Service_Contract__r.Contact.FirstName  &amp; &quot; &quot; &amp; FS_Service_Contract__r.Contact.LastName )</formula>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Dispatch_State__c</fullName>
        <description>The current state of the FS Dispatch</description>
        <inlineHelpText>Select the current state of the FS Dispatch</inlineHelpText>
        <label>Dispatch State</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Findings Reported</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Findings Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Findings Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FS_Gen_Asset_State__c</fullName>
        <formula>FS_Service_Contract__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Partner_Tracking_ID__c</fullName>
        <description>External ID used by the partner for tracking their FS Dispatches</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the tracking ID that is being used by the Dispatch Partner in their system.</inlineHelpText>
        <label>Partner Tracking ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Selected_Partner_Name__c</fullName>
        <description>The name of the Dispatch Partner Account selected</description>
        <label>Selected Partner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FS_Service_Contract_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract Event</label>
        <referenceTo>Service_Contract_Event__c</referenceTo>
        <relationshipLabel>FS Dispatches</relationshipLabel>
        <relationshipName>FS_Dispatches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FS_Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>FS Dispatches</relationshipLabel>
        <relationshipName>FS_Dispatches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FS_Time_Dispatched__c</fullName>
        <description>Time and date stamp for the latest transition of this FS Dispatch State to &quot;Dispatched&quot;</description>
        <inlineHelpText>Enter the time and date for the latest transition of this FS Dispatch State to &quot;Dispatched&quot;</inlineHelpText>
        <label>Time Dispatched</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FS_Time_Submitted__c</fullName>
        <description>Time and date stamp for the latest transition of this FS Dispatch State to &quot;Dispatch Findings Submitted&quot;</description>
        <inlineHelpText>Enter the time and date for the latest transition of this FS Dispatch State to &quot;Dispatch Findings Submitted&quot;</inlineHelpText>
        <label>Time Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subreason__c</fullName>
        <formula>text( FS_Parent_Case__r.Subset_Reasons__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subreason</label>
        <type>Text</type>
    </fields>
    <label>FS Dispatch</label>
    <nameField>
        <displayFormat>FSD-{000000}</displayFormat>
        <label>Dispatch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FS Dispatches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDCProject/src/classes/FSDispatchesSearch.cls
public with sharing class FSDispatchesSearch {
   
        public FS_Dispatch__c  dispatchObj;
        private string CustomernameLike = '%%';
        private string CityLike = '%%';
        private string DispatchIDLike = '%%';
        private string DispatchstateLike ='%%';
        private string CasereasonLike = '%%';
        private string PartnerTrackingIdLike = '%%';
        private Boolean bAllView = false;        
    
        public String viewName{get;set;} 
        public String searchvalue{get;set;}
        public String searchcolumnname{get;set;}
        public boolean displayFSDispatchName{get;set;}
        public Date partnerGoLiveDate {get;set;}
        public Date partnerContactGoLiveDate {get;set;}
        public String loginProfileId {get;set;}
        public String partnerType {get;set;}
        private List<FSDispatches> dispatchList;
        public Id loginPartnerAccountId {get;set;}
        public Id loginContactId {get;set;}
        public Boolean isOpsProfile {get;set;}
        public String urlPrefix {get;set;}

        public FSDispatchesSearch(){

            urlPrefix = '/partner';
            String baseURL = EDPUtil.getBaseURL();
            if(baseURL != null && !baseURL.contains(urlPrefix)){
            urlPrefix = '';
        }
        
        displayFSDispatchName = false;
        isOpsProfile = false;
        Contact contactObj = PRMContactUtil.getLoginUserAccountAndContact();
        if (contactObj !=null){
            loginPartnerAccountId = contactObj.account.Id;
            loginContactId = contactObj.Id;
            partnerType = contactObj.Account.Partner_Type__c;
            partnerGoLiveDate = contactObj.Account.EDP_Go_Live_Date__c;
            partnerContactGoLiveDate = contactObj.EDP_Go_Live_Date__c;
        }
        loginProfileId = UserInfo.getProfileId();
        }
   
   // the current sort direction. defaults to asc
       public String sortDir {
        // To set a Direction either in ascending order or descending order.
                                get  { if (sortDir == null) {  sortDir = 'asc'; } return sortDir;}
        set;
      }

    // the current field to sort by. defaults to last name
      public String sortField {
        // To set a Field for sorting.
                                get  { if (sortField == null) {sortField = 'Name'; } return sortField;  }
        set;
      } 
              
     public PageReference doSearch()
     {
        if(searchValue != null && searchValue !='' && searchValue.Length() < 2) {
            String errorMessage = CustomErrorMessages.MINIMUM_SEARCH_STRING;
            Exception expObj = new FSException(errorMessage);
            expObj.setMessage(errorMessage);
            ApexPages.addMessages(expObj);
            return null;
        }
         con = null;    
         con = createSQOLConnection();
                con.setPageSize(25);
                return null;
         
     }
     public ApexPages.standardSetController con {
        get {
            if (con!= null) {
               return con;
            }
            con =  createSQOLConnection();
            con.setPageSize(25);
            return con; 
        }
     set;
    }  
     public class  FSDispatches{
         public FSDispatches() {
      }   
     public FS_Dispatch__c dispatchObj{get;set;}
     }
     
       //Following is to get the list of FSDispatches based on the View and Search String 
     public List<FSDispatches> getFSDispatches(){
              dispatchList = new List<FSDispatches>();
                if(con != null){
                   List<FS_Dispatch__C> tempFSDispatches = con.getRecords();
                   dispatchList =  populateFSDispatchList(tempFSDispatches);           
            }
            return dispatchList;
      }
        
        private List<FSDispatches> populateFSDispatchList(List<FS_Dispatch__c> fsdispatchList){
            List<FSDispatches> tempFSDispatchList = new List<FSDispatches>();
            FSDispatches tempFSDispatches = null;
            for(FS_Dispatch__c dispatchObj : fsdispatchList){
                tempFSDispatches = new FSDispatches();
                tempFSDispatches.dispatchObj  = dispatchObj;
                tempFSDispatchList.add(tempFSDispatches);
            }
            return tempFSDispatchList;
         } 
      
          public List<SelectOption> getViews() {
            List<SelectOption> Views = new List<SelectOption>();
                 Views.add(new SelectOption('ALL', 'ALL'));
                 Views.add(new SelectOption('ACTIVE', 'ACTIVE'));
              // Views.add(new SelectOption('ACTIVE(REC)', 'ACTIVE(REC)'));      
                 Views.add(new SelectOption('NEW', 'NEW'));
                  return Views;
        }
     
       //Search Option  Picklist
    
     public List<SelectOption> getSearchBy() {
            List<SelectOption> searchBy = new List<SelectOption>();
                  searchBy.add(new SelectOption('Customer Name', 'Customer Name'));
                  searchBy.add(new SelectOption('City','City'));
                  searchBy.add(new SelectOption('Dispatch ID','Dispatch ID'));
                  searchBy.add(new SelectOption('Dispatch state', 'Dispatch State'));
                  searchBy.add(new SelectOption('Case Reason', 'Case Reason'));
                  searchBy.add(new SelectOption('Partner Tracking Id','Partner Tracking ID'));
                  return searchBy;
    }       
      
     public pageReference clearSearchValue() {
            searchValue = '';
            return null;
            
    }
    //Following is to build SOQL connection
       private ApexPages.StandardSetController createSQOLConnection() {
               ApexPages.StandardsetController tempConnection;
               String soqlQuery;
               String opsProfileId = Label.Partner_Ops_Profile;
               System.debug('opsProfileId: ' + opsProfileId);
                           
               String userName = UserInfo.getName();
               soqlQuery = getSelectionQuery();
                
         System.debug('soqlQuery: ' + soqlQuery);
         
         tempConnection = new ApexPages.StandardSetController(Database.getQueryLocator(soqlQuery));        
         return  tempConnection;
       }    
          //TO Build the query based on selected view and enetered search string
       private String getSelectionQuery () {
           CustomernameLike = '%%';
           cityLike = '%%';
           DispatchIDLike = '%%';
           DispatchstateLike = '%%';
           CasereasonLike  = '%%';
           PartnerTrackingIdLike='%%';
           String soqlQuery = '';
           String userId = UserInfo.getUserId();
           String userName = UserInfo.getName(); 
           String searchCondition = '';
           System.debug(SearchValue);
           bAllView = false;
           
           if(searchValue != null && searchValue != '' ) {
              if(searchColumnName == 'Customer Name'){
                 system.debug('search value Customername..'+searchValue);
                 CustomernameLike = '%'+ searchvalue + '%';
                 SearchCondition = ' (FS_Customer_Name__c like :CustomernameLike) ';
                 SearchCondition += ' AND ';                
                 SearchCondition += getSearchConditionByViewName(userId,userName); 
            }
            else if(searchColumnName == 'City') {
                    system.debug('search value city..'+searchValue);
                    CityLike = '%' + searchvalue + '%';
                    SearchCondition = ' (FS_City__c like :CityLike) ';
                    SearchCondition += ' AND ';                
                    SearchCondition += getSearchConditionByViewName(userId,userName);
             }       
             else if(searchColumnName == 'Dispatch ID') {
                    system.debug('search value dispatch name..' +searchValue);
                    DispatchIDLike = '%' + searchvalue +'%';
                    SearchCondition = ' (Name like :DispatchIDLike) ';
                    SearchCondition += ' AND ';                
                    SearchCondition += getSearchConditionByViewName(userId,userName);
             } 
             else if(searchColumnName == 'Dispatch State') {
                    system.debug('search value dispatch state..' +searchValue);
                    DispatchStateLike = '%' + searchvalue +'%';
                    SearchCondition = ' (FS_Dispatch_State__c like :DispatchStateLike) ';
                    SearchCondition += ' AND ';                
                    SearchCondition += getSearchConditionByViewName(userId,userName);
             } 
             else if(searchColumnName == 'Case Reason') {
                    system.debug('search value Case reason..' +searchValue);
                    CaseReasonLike = '%' + searchvalue +'%';
                    SearchCondition = ' (Case_Reason__c like :CasereasonLike) ';
                    SearchCondition += ' AND ';                
                    SearchCondition += getSearchConditionByViewName(userId,userName);
             } 
             else if(searchColumnName == 'Partner Tracking ID') {
                    system.debug('search value PartnerTrackingId..' +searchValue);
                    PartnerTrackingIdLike = '%' + searchvalue +'%';
                    SearchCondition = ' (FS_Partner_Tracking_ID__c like :PartnerTrackingIdLike) ';
                    SearchCondition += ' AND ';                
                    SearchCondition += getSearchConditionByViewName(userId,userName);
             }
              }
            else {
                  searchCondition = getSearchConditionByViewName(userId,userName);
                
             }
            
            soqlQuery = 'select ID, FS_Customer_Name__c,Name,FS_City__c,FS_Gen_Asset_State__c,Case_Reason__c,';
            soqlQuery +=  'Subreason__c,FS_Selected_Partner_Name__c, Case_Priority__c,FS_Partner_Tracking_ID__c,';
            soqlQuery +=  'FS_Dispatch_State__c,FS_Time_Dispatched__c,FS_Time_Submitted__c, FS_Service_Contract__c, FS_Service_Contract_Event__c from FS_Dispatch__c '; 
            if (!bAllView){
                soqlQuery += ' where '; 
            }
            else if(bAllView && searchValue != null && searchValue != ''){
                soqlQuery += ' where ';
                searchCondition = searchCondition.substring(0, searchCondition.indexOf(' AND '));
            }    
            soqlQuery += searchCondition; 
            
            // simply toggle the direction
            sortDir = sortDir.equals('asc') ? 'desc' : 'asc';
        
            if (sortField==null || sortField ==''){
                soqlQuery += ' ORDER BY CreatedDate DESC limit 10000 ';
            }
            else{
                soqlQuery += ' ORDER BY ' + sortField + ' ' + sortDir + ' limit 10000 ';
                //soqlQuery += ' ORDER BY CreatedDate DESC limit 10000 ';
            }
            system.debug (soqlquery); 
            
                                            
             return soqlQuery;
            } 
           //Following is to get the selected views
         public Pagereference userActions(){
                 System.debug('ViewName Sample: ' + viewName);
                 Pagereference pageRef = null;
                 searchValue = null;
                 if(viewName == null || viewName == ''){
                 return null;
                 }else{
                 System.debug('ViewName Sample: ' + viewName);
                 pageRef = getFSdispatchSelectedView();
                 return pageRef;         
        }
                
    }

    //Following is to get the list of prposals for the selected views
     public PageReference getFSdispatchSelectedView() {
        con = null;
        con = createSQOLConnection();   
        con.setPageSize(25);
        return null;
     }   
         
         public Boolean hasNext{
        get
        {
            return con.getHasNext();
        }
        set;
    }
 

    public Boolean hasPrevious{
        get
        {
            return con.getHasPrevious();
        }
        set;
    }
 
    
    public Integer pageNumber{
        get
        {
            return con.getPageNumber();
        }
        set;
    }

    public void first(){
        con.first();
    }  
 
    public void last(){
        con.last();
    }
        
    public void previous(){
        con.previous();
    }

    public void next(){
        con.next();
    }  
    
     private String getSearchConditionByViewName(String userId, String userName){
        String SearchCondition = '';
        bAllView = False;
        if(viewName == null || viewName == '') {
          // viewName = 'ALL';  //CommentedBy Suneetha "BSKY-6106"
           viewName = 'ACTIVE';
        }   
        if(viewName == 'ACTIVE'){          
            displayFSDispatchName = true;
            SearchCondition += ' FS_Dispatch_State__c IN (\'Dispatch Accepted\',\'Dispatch Findings Rejected\') ';  
             system.debug('Searchcondition******' + searchCondition);  
         }
         
      /*  else if(viewName == 'ACTIVE(REC)'){          
           displayFSDispatchName = true;
           SearchCondition += ' FS_Dispatch_State__c IN (\'Dispatch Accepted\',\'Dispatch Findings Rejected\') ';  
           system.debug('Searchcondition******' + searchCondition);  
         }*/
         
        else if(viewName == 'ALL'){          
                displayFSDispatchName = true;
                bAllView = True;            
               //SearchCondition += ' FS_Dispatch_State__c = \'Dispatched\' ';  
                system.debug('Searchcondition******' + searchCondition);  
         }
           else if(viewName == 'NEW'){          
                 displayFSDispatchName = true;
                 SearchCondition += ' FS_Dispatch_State__c IN (\'Dispatched\') ';
          }
         
          return SearchCondition;
    
        } 
             
 // }
   public class FSException extends Exception {}
  
   }