SFDCProject/src/objects/Generation_Assets__c.object
<CustomObject>
    <description>Generation Assets are energy generating facilities owned by SunRun</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City where home is located</description>
        <label>City</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Address__c</fullName>
        <description>Address for this SunRun home</description>
        <label>Home Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SR_Signoff__c</fullName>
        <description>Date SunRun signed off on the customer Agreement</description>
        <inlineHelpText>Date SunRun signed off on the customer Agreement</inlineHelpText>
        <label>SR Signoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Welcome_Call__c</fullName>
        <inlineHelpText>Date we placed welcome call to customer, confirmed contact info, billing preferences</inlineHelpText>
        <label>Welcome Call</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Zip Code</description>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Generation Asset</label>
    <nameField>
        <label>Generation Assets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Generation Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDCProject/src/classes/testGenAssetWelcomeCall.cls
@isTest
private class testGenAssetWelcomeCall {

    static testMethod void testWelcomeCallDays() {
        Generation_Assets__c assetRec = new Generation_Assets__c();
        assetRec.Name = 'Test Gen Asset';
        assetRec.Home_Address__c = '100 Main St';
        assetRec.City__c = 'City';
        assetRec.Zip__c = '00001';
        assetRec.SR_Signoff__c = Date.today().addDays(-20);
        assetRec.Welcome_Call__c = Date.today();
        
        insert assetRec;
        
        assetRec.SR_Signoff__c = Date.today().addDays(-10);
        update assetRec;
    }
}