SFDCProject/src/objects/Generation_Assets__c.object
<CustomObject>
    <description>Generation Assets are energy generating facilities owned by SunRun</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Generation Assets</relationshipLabel>
        <relationshipName>R00N60000001ZOSVEA4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer contact for this gen asset.</description>
        <inlineHelpText>The customer contact for this gen asset.</inlineHelpText>
        <label>Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Generation Assets</relationshipLabel>
        <relationshipName>Generation_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Mailing_Address__c</fullName>
        <description>This field was created by DSG purely for searching purposed in the milestone portal, it allows you to search for a project by any portion of the address, including city or zip</description>
        <formula>Home_Address__c + &quot;, &quot; + City__c +&quot;, &quot;+ State__c + &quot;, &quot; + Zip__c</formula>
        <label>Customer Mailing Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Address__c</fullName>
        <description>Address for this SunRun home</description>
        <label>Home Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Install_Partner__c</fullName>
        <inlineHelpText>Partner on the install; we use this field here in order to calc the milestone payments correctly</inlineHelpText>
        <label>Install Partner</label>
        <picklist>
            <picklistValues>
                <fullName>1st Light Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A1 Solar Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acro Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advanced Solar Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Akeena Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alteris Renewables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Solar - New Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arise Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona Solar Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASI Heating Air &amp; Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Astralux Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonterra Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clean Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY Solar Inc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cotuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTEC Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eco Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green Home Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greenspring Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>groSolar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harmon Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HelioPower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HelioPower Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horizon Solar Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Imagine Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infinity Solar Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Islandwide</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Generation Asset</label>
    <nameField>
        <label>Generation Assets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Generation Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDCProject/src/objects/Install_Audit__c.object
<CustomObject>
    <fields>
        <fullName>Auditor_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auditor Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Install Audits</relationshipLabel>
        <relationshipName>Install_Audits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Denied_Reason__c</fullName>
        <label>Denied Reason</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Generation_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Generation Asset</label>
        <referenceTo>Generation_Assets__c</referenceTo>
        <relationshipLabel>Install Audits</relationshipLabel>
        <relationshipName>Install_Audits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Install_Audit_Type__c</fullName>
        <label>Audit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Onsite</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Remote</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Install Audits</relationshipLabel>
        <relationshipName>Install_Audits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Install Audit</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Install Audits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDCProject/src/objects/SunRun_Audit_Data__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Sunrun_Audit_Email_Signature_Address__c</fullName>
        <label>Sunrun Audit Email Signature Address</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sunrun_Audit_Email_Signature_Name__c</fullName>
        <label>Sunrun Audit Email Signature Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sunrun_Audit_Email_Signature_Title__c</fullName>
        <label>Sunrun Audit Email Signature Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SunRun Audit Data</label>
</CustomObject>

SFDCProject/src/classes/AuditEmailTemplateController.cls
global class AuditEmailTemplateController {

global AuditEmailTemplateController(){           
           PhotoSubmitDate = (DateTime.now().addDays(7)).format('MMMM dd, yyyy');
           SiteSubmitDate = (DateTime.now().addDays(21)).format('MMMM dd, yyyy'); 
           
           SunRun_Audit_Data__c auditEmailSetting = [select Sunrun_Audit_Email_Signature_Address__c, Sunrun_Audit_Email_Signature_Name__c, 
                                                            Sunrun_Audit_Email_Signature_Title__c from SunRun_Audit_Data__c where Name = 'Audit Email Signature'];
                                                            
           SignatureName = auditEmailSetting.Sunrun_Audit_Email_Signature_Name__c;
           SignatureTitle = auditEmailSetting.Sunrun_Audit_Email_Signature_Title__c;
           SignatureAddress = auditEmailSetting.Sunrun_Audit_Email_Signature_Address__c;
           
           AuditURL = System.Label.PartnerPortalSiteUrl + '/installaudit?id=';
           //AuditURL = 'https://intdev-sunrunhome.cs17.force.com/partner/installaudit?id=' + ia.Id;
           string strOrgId = UserInfo.getOrganizationId();
           string orgInst = URL.getSalesforceBaseUrl().getHost();
           SunrunURL = URL.getSalesforceBaseUrl().getProtocol() + '://' + orgInst; //+ '/servlet/servlet.ImageServer?id=' + lstDocument[0].Id + '&oid=' + strOrgId;
}

/*global Install_Audit__c getInstallAudit(){
       return [select id, Auditor_Contact__r.Name, Generation_Asset__r.Name,
                Generation_Asset__r.Account_Name__r.Name, Generation_Asset__r.Home_Address__c,
                Generation_Asset__r.Install_Partner__c, Denied_Reason__c, Install_Audit_Type__c,
                Generation_Asset__r.Customer_Contact__r.Name
           from Install_Audit__c where Id = :InstallAuditId];   
}
*/
global Install_Audit__c getInstallAudit(){
       return [select id, Auditor_Contact__r.Name, Service_Contract__r.Name,
                Service_Contract__r.Account.Name, Service_Contract__r.Home_Address__c,
                Service_Contract__r.Install_Partner__c, Denied_Reason__c, Install_Audit_Type__c,
                Service_Contract__r.Contact.Name,Service_Contract__r.Customer_Mailing_Address__c
           from Install_Audit__c where Id = :InstallAuditId];   
}

global Id InstallAuditId { get; set; }
global Install_Audit__c ia { get; set; }

global String PhotoSubmitDate{get;set;}
global String SiteSubmitDate{get;set;}
global String SignatureName{get;set;}
global String SignatureTitle{get;set;}
global String SignatureAddress{get;set;}
global String AuditURL{get;set;}
global String SunrunURL{get; set;}
}