SFDCProject/src/objects/Generation_Assets__c.object
<CustomObject>
    <description>Generation Assets are energy generating facilities owned by SunRun</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Generation Assets</relationshipLabel>
        <relationshipName>R00N60000001ZOSVEA4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City where home is located</description>
        <label>City</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer contact for this gen asset.</description>
        <inlineHelpText>The customer contact for this gen asset.</inlineHelpText>
        <label>Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Generation Assets</relationshipLabel>
        <relationshipName>Generation_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Home_Address__c</fullName>
        <description>Address for this SunRun home</description>
        <label>Home Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Zip Code</description>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Generation Asset</label>
    <nameField>
        <label>Generation Assets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Generation Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDCProject/src/objects/Quick_Case_Template__c.object
<CustomObject>
    <fields>
        <fullName>Case_Origin__c</fullName>
        <label>Case Origin</label>
        <picklist>
            <controllingField>Case_Record_Type__c</controllingField>
            <picklistValues>
                <fullName>Call Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call Outbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Outbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GetSatisfaction Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunRun Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SunRun Automated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <label>Case Reason</label>
        <picklist>
            <controllingField>Case_Record_Type__c</controllingField>
            <picklistValues>
                <fullName>Account Credits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autopay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing &amp; Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections/Dispute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSLB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design / ENGR Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documentation Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENG: Contracted Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPC Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expected Production Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet Operations Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inaccurate Facility Inputs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation &amp; PTO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metering</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Record_Type__c</fullName>
        <description>Case Record Type for the case</description>
        <inlineHelpText>Select the Case Record Type for the case to be created.</inlineHelpText>
        <label>Case Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>FS Ticket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Coordinator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FS_Initial_Diagnosis__c</fullName>
        <description>FS Initial Diagnosis to be used for creating the new case.</description>
        <inlineHelpText>Enter the FS Initial Diagnosis to be used for creating the new case.</inlineHelpText>
        <label>FS Initial Diagnosis</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispute with Utility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispute with Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reported to AG, BBB, Gov&apos;t, or Press</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Litigious</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Private_Customer_Care_Description__c</fullName>
        <description>[Requested in SFDC-675]</description>
        <inlineHelpText>[Requested in SFDC-675]</inlineHelpText>
        <label>Private Customer Care Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subset_Reason__c</fullName>
        <label>Subset Reason</label>
        <picklist>
            <controllingField>Case_Reason__c</controllingField>
            <picklistValues>
                <fullName>&quot;The Right Stuff&quot; Webinar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd Party Solar Stats</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH Timeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AC power outage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional System Clarification/Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aesthetics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aggregation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreement Terms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Increase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>As-built system different from design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Autopay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aziumth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Roof for Solar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Method</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Method Switch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing System Error One-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing System Error Widespread</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broken panel(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quick Case Template</label>
    <nameField>
        <label>Quick Case Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quick Case Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/quickCase.cls
public with sharing class quickCase 
{
    public final Generation_Assets__c genAsset;
    public List<qCaseWrapper> qCaseTemplates = new List<qCaseWrapper>();
    public String srchCaseReason {get;set;}
    public String caseReason {get;set;}
    public String privateCustomerCareDesc{get;set;}
    public String caseSubsetReason {get;set;}
    public String caseOrigin {get;set;}
    public String caseSubject {get;set;}
    public String caseDescription {get;set;}
    public String casePriority{get;set;}
    public String fsTicket {get;set;}
    public String recTypeName {get;set;}    
    public String fsInitialDiagnosis {get;set;}
    public String sortField {get; set;}
    public String previousSortField {get; set;}
    public Boolean pageLoad {get; set;}
	List<Quick_Case_Template__c> qCaseTemplateList;
        
    public quickCase(ApexPages.StandardController stdController) 
    {
        this.genAsset = (Generation_Assets__c)stdController.getRecord();
        fsTicket = ApexPages.currentPage().getParameters().get('fsTicket');
        if (fsTicket == null)
        {
            fsTicket = '';
        }
        pageLoad = true;
    }

    public class qCaseWrapper
    {
        public Quick_Case_Template__c qCaseTemplateRec{get; set;}
        public Boolean recSelected {get; set;}

        public qCaseWrapper(Quick_Case_Template__c qCaseTemplate)
        {
            qCaseTemplateRec = qCaseTemplate;
            recSelected = false;
        }
    }

    public List<qCaseWrapper> getqCaseTemplates() 
    {
        if ((qCaseTemplates == null || qCaseTemplates.size() <= 0) && pageLoad)
        {
        	pageLoad = false;
//            Quick_Case_Template__c[] qCaseTemplateList;
			system.debug('fsTicket : ' + fsTicket);
            if (fsTicket != null && fsTicket != '')
            {
                qCaseTemplateList = [Select Name, Priority__c, Private_Customer_Care_Description__c, Case_Origin__c, Case_Reason__c, Description__c, Subject__c, Subset_Reason__c,FS_Initial_Diagnosis__c,Case_Record_Type__c From Quick_Case_Template__c where Case_Record_Type__c = 'FS Ticket'];
            }
            else
            {
                qCaseTemplateList = [Select Name, Priority__c, Private_Customer_Care_Description__c, Case_Origin__c, Case_Reason__c, Description__c, Subject__c, Subset_Reason__c,FS_Initial_Diagnosis__c,Case_Record_Type__c From Quick_Case_Template__c where Case_Record_Type__c != 'FS Ticket'];
            }
            for(Quick_Case_Template__c qCaseTemplateRec : qCaseTemplateList)
            {
                qCaseTemplates.add(new qCaseWrapper(qCaseTemplateRec));
            }    
        }
        return qCaseTemplates;
    }

    public PageReference refreshTemplates() 
    {
        if (srchCaseReason != null)
        {
            qCaseTemplateList.clear();
            
            if (srchCaseReason != '---All---')
            {
	            if (fsTicket != null && fsTicket != '')
	            {
	                qCaseTemplateList = [Select Name, Priority__c, Private_Customer_Care_Description__c, Case_Origin__c, Case_Reason__c, Description__c, Subject__c, Subset_Reason__c,FS_Initial_Diagnosis__c,Case_Record_Type__c From Quick_Case_Template__c where Case_Record_Type__c = 'FS Ticket' And Case_Reason__c = :srchCaseReason];
	            }
	            else
	            {
	                qCaseTemplateList = [Select Name, Priority__c, Private_Customer_Care_Description__c, Case_Origin__c, Case_Reason__c, Description__c, Subject__c, Subset_Reason__c,FS_Initial_Diagnosis__c,Case_Record_Type__c From Quick_Case_Template__c where Case_Record_Type__c != 'FS Ticket' And Case_Reason__c = :srchCaseReason];
	            }
            }
            else
            {
	            if (fsTicket != null && fsTicket != '')
	            {
	                qCaseTemplateList = [Select Name, Priority__c, Private_Customer_Care_Description__c, Case_Origin__c, Case_Reason__c, Description__c, Subject__c, Subset_Reason__c,FS_Initial_Diagnosis__c,Case_Record_Type__c From Quick_Case_Template__c where Case_Record_Type__c = 'FS Ticket'];
	            }
	            else
	            {
	                qCaseTemplateList = [Select Name, Priority__c, Private_Customer_Care_Description__c, Case_Origin__c, Case_Reason__c, Description__c, Subject__c, Subset_Reason__c,FS_Initial_Diagnosis__c,Case_Record_Type__c From Quick_Case_Template__c where Case_Record_Type__c != 'FS Ticket'];
	            }
            }
            qCaseTemplates.clear();
            for(Quick_Case_Template__c qCaseTemplateRec : qCaseTemplateList)
            {
                qCaseTemplates.add(new qCaseWrapper(qCaseTemplateRec));
            }    
        }
        return null;
    }

    public PageReference GetSelectedTemplate()
    {
        caseReason = '';
        caseSubsetReason = '';
        caseOrigin = '';
        caseSubject = '';
        casePriority = '';
        recTypeName = '';
        fsInitialDiagnosis = '';
        privateCustomerCareDesc = '';
        for(qCaseWrapper qCaseTemplateWrapperRec : qCaseTemplates)
        {
            if(qCaseTemplateWrapperRec.recSelected == true)
            {
                caseReason = qCaseTemplateWrapperRec.qCaseTemplateRec.Case_Reason__c;
                caseSubsetReason = qCaseTemplateWrapperRec.qCaseTemplateRec.Subset_Reason__c;
                caseOrigin = qCaseTemplateWrapperRec.qCaseTemplateRec.Case_Origin__c;
                privateCustomerCareDesc = qCaseTemplateWrapperRec.qCaseTemplateRec.Private_Customer_Care_Description__c;
                caseSubject = qCaseTemplateWrapperRec.qCaseTemplateRec.Subject__c;
                caseDescription = qCaseTemplateWrapperRec.qCaseTemplateRec.Description__c;
                casePriority = qCaseTemplateWrapperRec.qCaseTemplateRec.Priority__c;
                recTypeName = qCaseTemplateWrapperRec.qCaseTemplateRec.Case_Record_Type__c;
                fsInitialDiagnosis = qCaseTemplateWrapperRec.qCaseTemplateRec.FS_Initial_Diagnosis__c;
                break;
            }
        }
        return null;
    }

    public PageReference createCase()
    {
        try
        {
            Generation_Assets__c genAssetRec = [Select Account_Name__c, Customer_Contact__c From Generation_Assets__c Where Id = :genAsset.Id];
            System.debug('Record type : ' + recTypeName);

            Case caseRec = new Case();
            RecordType stdRecType = [Select Id from RecordType where Name = :recTypeName and SobjectType = 'Case']; 
            
            caseRec.RecordTypeId = stdRecType.Id;
            caseRec.AccountId = genAssetRec.Account_Name__c;
            caseRec.ContactId = genAssetRec.Customer_Contact__c;
            caseRec.Generation_Asset__c = genAsset.Id;
            caseRec.Reason = caseReason;
            caseRec.Subset_Reasons__c = caseSubsetReason;
            caseRec.Origin = caseOrigin;
            caseRec.Customer_Care_Description__c = privateCustomerCareDesc;
            caseRec.Subject = caseSubject;
            caseRec.Status = 'Open';
            caseRec.Description = caseDescription;
            caseRec.FS_Initial_Diagnosis__c = fsInitialDiagnosis;
            caseRec.Priority = casePriority;
            insert caseRec;
            
            PageReference casePage = new ApexPages.StandardController(caseRec).view();
            casePage.setRedirect(true);
            return casePage;
        }
        catch(Exception ex)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,ex.getMessage()));
            return null;
        }
    }
    
    public List<SelectOption> getCaseReasons() 
    {
        Schema.DescribeFieldResult fieldResult = Quick_Case_Template__c.Case_Reason__c.getDescribe();
        
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption( '---All---', '---All---'));
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        } 
        return options;    
    }    
 
	public void doSort()
	{

        String order = 'asc';
        /*This checks to see if the same header was click two times in a row, if so
        it switches the order.*/
        if(previousSortField == sortField){
            order = 'desc';
            previousSortField = null;
        }else{
            previousSortField = sortField;
        }
        //To sort the table we simply need to use this one line, nice!
        superSort.sortList(qCaseTemplateList,sortField,order);
        qCaseTemplates.clear();
        for(Quick_Case_Template__c qCaseTemplateRec : qCaseTemplateList)
        {
            qCaseTemplates.add(new qCaseWrapper(qCaseTemplateRec));
        }    
        
	}
     
    
    public static testMethod void quickCaseTest()
    {
        Test.startTest();
        
        Account accountRec = new Account();
        accountRec.Name = 'Test Class';
        insert accountRec;
 
        Contact contactRec = new Contact();
        contactRec.FirstName = 'DSG';
        contactRec.LastName = 'Test';
        contactRec.AccountId = accountRec.Id;
        insert contactRec;
     
        Generation_Assets__c genAssetRec = new Generation_Assets__c();
        genAssetRec.Account_Name__c = accountRec.Id;
        genAssetRec.Customer_Contact__c = contactRec.Id;
        genAssetRec.Name = 'DSG Test';
        genAssetRec.Home_Address__c = '123 Main Street';
        genAssetRec.City__c = 'Los Gatos';
        genAssetRec.Zip__c = '95032';
        insert genAssetRec;
 
        ApexPages.StandardController stdCont = new ApexPages.StandardController(genAssetRec);
        quickCase qCaseTestController = new quickCase(stdCont);
        qCaseTestController.getCaseReasons();
 		qCaseTestController.srchCaseReason = '---All---';
 		qCaseTestController.fsTicket = '';
        List<qCaseWrapper> qCaseTemplates = qCaseTestController.getqCaseTemplates();
        qCaseTestController.refreshTemplates();
		qCaseTestController.sortField = 'Case_Reason__c';
//		qCaseTestController.doSort();
        for(qCaseWrapper qCaseWrapperRec : qCaseTemplates)
        {
            qCaseWrapperRec.recSelected = true;
            break;
        }
        qCaseTestController.qCaseTemplates = qCaseTemplates;
        qCaseTestController.GetSelectedTemplate();
        qCaseTestController.createCase();

 		qCaseTestController.fsTicket = 'FST';
 		qCaseTestController.getCaseReasons();
 		qCaseTestController.srchCaseReason = 'Metering';
        qCaseTemplates = qCaseTestController.getqCaseTemplates();
		qCaseTestController.refreshTemplates();        
		qCaseTestController.sortField = 'Case_Reason__c';
//		qCaseTestController.doSort();
        for(qCaseWrapper qCaseWrapperRec : qCaseTemplates)
        {
            qCaseWrapperRec.recSelected = true;
            break;
        }
		qCaseTestController.qCaseTemplates = qCaseTemplates;
        qCaseTestController.GetSelectedTemplate();
        qCaseTestController.createCase();

        Test.stopTest();
    }
}