SFDCProject/src/objects/Generation_Assets__c.object
<CustomObject>
    <description>Generation Assets are energy generating facilities owned by SunRun</description>
    <fields>
        <fullName>Customer_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer contact for this gen asset.</description>
        <inlineHelpText>The customer contact for this gen asset.</inlineHelpText>
        <label>Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Generation Assets</relationshipLabel>
        <relationshipName>Generation_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Cancelled__c</fullName>
        <description>Date the customer cancelled</description>
        <label>Date Cancelled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <label>Promotion</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Stimulus 3-mo Free Jan-Mar09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 - month free promo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - month free promo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - month free promo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50 off promo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$100 off promo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referral_Input__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral_Input__c</referenceTo>
        <relationshipLabel>Generation Assets</relationshipLabel>
        <relationshipName>Generation_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SR_Signoff__c</fullName>
        <description>Date SunRun signed off on the customer Agreement</description>
        <inlineHelpText>Date SunRun signed off on the customer Agreement</inlineHelpText>
        <label>SR Signoff</label>
        <type>Date</type>
    </fields>
    <label>Generation Asset</label>
    <nameField>
        <label>Generation Assets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Generation Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDCProject/src/objects/Promotion__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Referral_Input__c.object
<CustomObject>
    <description>We are collecting the referred by and referred to in this object. In some cases, we will have the account id and contact id, and in some we will not, hence the other fields such as first name, last name etc.</description>
    <fields>
        <fullName>Customer_Contact__c</fullName>
        <formula>Service_Contract__r.Contact.LastName  + &apos;, &apos; +  Service_Contract__r.Contact.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipName>Referrals_Input</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals (New Customers Contacts)</relationshipLabel>
        <relationshipName>Referrals_Input</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{0000000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/ReferralMetricsController.cls
public without sharing class ReferralMetricsController {

public Double numcust{get;set;}
public Double numcustreferring{get;set;}
public Double percentreferring{get;set;}
public Set<Id> CustomerIds{get;set;}
public Set<Id> ReferringCustomerIds{get;set;}
public Promotion__c therange{get;set;}

public void ReferralMetricsController(){}

public void init(){
	numcust = 0.0;
	numcustreferring = 0.0;
	Set<Id> setCustomerIds = new Set<Id>();
	Set<Id> setReferringCustomerIds = new Set<Id>();
	therange = new Promotion__c();
	//
	String fDate = ApexPages.CurrentPage().getparameters().get('fromDate');
    String tDate = ApexPages.CurrentPage().getparameters().get('toDate');
    //
    if(fDate != null && tDate != null)
    {
       therange.Start_Date__c = date.newInstance(Integer.valueOf(fDate.substring(0,4)), Integer.valueOf(fDate.substring(5,7)), Integer.valueOf(fDate.substring(8))); 
       therange.End_Date__c = date.newInstance(Integer.valueOf(tDate.substring(0,4)), Integer.valueOf(tDate.substring(5,7)), Integer.valueOf(tDate.substring(8)));
    }
    else
    {  
       therange.Start_Date__c = date.newInstance(2000,1,1);
       therange.End_Date__c = date.newInstance(2050,1,1);
    }    
	/*
	  AggregateResult[] gacust = [select count(customer_Contact__c) custcount
	                             from Generation_Assets__c 
	                            where SR_Signoff__c <> null 
	                              and Date_Cancelled__c =  null];
   
      for(AggregateResult ar: gacust)
      {
         numcust = Double.ValueOf(ar.get('custcount'));     
      }  
    */
   
   for(Generation_Assets__c ga:[select customer_Contact__c
	                             from Generation_Assets__c 
	                            where SR_Signoff__c <> null 
	                              and Date_Cancelled__c =  null])
   {
	  if(!setCustomerIds.Contains(ga.Customer_Contact__c))
	  {
	  	numcust++;
	  	setCustomerIds.add(ga.Customer_Contact__c);
	  }	  
   }    
   CustomerIds = setCustomerIds;

   for(Referral_Input__c ri:[Select Id, Source_Contact_Id__c, CreatedDate 
                               FROM Referral_Input__c 
                              where Source_Contact_Id__c in :CustomerIds
                                ])
   {
   	   if(!setReferringCustomerIds.Contains(ri.Source_Contact_Id__c))
   	   {
   	   	  if(ri.CreatedDate >= therange.Start_Date__c && ri.CreatedDate <= therange.End_Date__c)
   	   	  {
   	         numcustreferring++;
   	         setReferringCustomerIds.add(ri.Source_Contact_Id__c);
   	   	  }
   	   }   	
   }
   percentreferring = (numcustreferring/numcust)*100;

}

public pageReference refreshData() {
  PageReference pr = new PageReference('/apex/ReferralMetrics?fromDate=' + String.ValueOf(therange.Start_Date__c).substring(0,10) + '&toDate=' + String.ValueOf(therange.End_Date__c).substring(0,10));
  pr.setRedirect(true);
  return pr;
}

}