SFDCProject/src/objects/Milestone_Proof_Partner_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Emails_To_Notify_Milestone_Proof_Upload__c</fullName>
        <inlineHelpText>Enter the email address to be notified. Use comma to separate more than one email address.</inlineHelpText>
        <label>Emails To Notify Milestone Proof Upload</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Notify_Milestone_Proof_Upload__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notify Milestone Proof Upload</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Milestone Proof Partner Preferences</relationshipLabel>
        <relationshipName>Milestone_Proof_Partner_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone Proof Partner Preference</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Milestone Proof Partner Preference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Proof Partner Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/milestoneProofPartnerPreferences.cls
public class milestoneProofPartnerPreferences {
	
	User userRec {get;set;} 
	public Milestone_Proof_Partner_Preference__c partnerPreference; 
	
	public milestoneProofPartnerPreferences()
	{
		userRec = [Select Contact.AccountId From User WHERE Id = :Userinfo.getUserid()];
	}

    public Milestone_Proof_Partner_Preference__c getPartnerPreference()
    {
        if(partnerPreference == null) 
        {
			Milestone_Proof_Partner_Preference__c[] partnerPreferenceList = [Select Id, Partner_Account__c, Notify_Milestone_Proof_Upload__c, Emails_To_Notify_Milestone_Proof_Upload__c 
							From Milestone_Proof_Partner_Preference__c Where Partner_Account__c = :userRec.Contact.AccountId Limit 1];

			if (partnerPreferenceList == null || partnerPreferenceList.size() <= 0)
        	{
				partnerPreference = new Milestone_Proof_Partner_Preference__c();
        	}
        	else
        	{
        		partnerPreference = partnerPreferenceList[0]; 	
        	}
        }
        
        return partnerPreference;   
        
    }	
	
	public PageReference savePreferences()
	{
		if (partnerPreference.Id == null)
		{
			partnerPreference.Partner_Account__c = userRec.Contact.AccountId;
			insert partnerPreference;
		}
		else
		{
			update partnerPreference;
		}
		ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Preferences Saved'));
		return null;
	}
	
    public static testMethod void milestoneProofPreferencesTest()
    {
        Test.startTest();
        milestoneProofPartnerPreferences testMileStoneProofPref = new milestoneProofPartnerPreferences();
        testMileStoneProofPref.getPartnerPreference();
        testMileStoneProofPref.savePreferences();
 		Test.stopTest();       
    }
	
}