SFDCProject/src/objects/Notes__c.object
<CustomObject>
    <description>This is a Related List on Proposal page to contain Notes</description>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Notes by Partner Users</description>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>Proposal_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{0}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Any notes pertaining to the homeowner&apos;s proposal.</description>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sunrun_Credit_Status__c</fullName>
        <label>Sunrun Credit Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/testOpptyTriggers.cls
/**
Peter Alexander Mandy
10232012 101129
 */
@isTest
private class testOpptyTriggers {

    static testMethod void myUnitTest() {
        //
        Account accountRec = new Account();
        accountRec.Name = 'Test Account Oppties';
        insert accountRec;
        //
        Contact contactRec = new Contact();
        contactRec.FirstName = 'TestAcct';
        contactRec.LastName = 'TestAcctOppty';
        contactRec.AccountId = accountRec.Id;
        insert contactRec;
        //
        ID ProfileID = [ Select id from Profile where UserType = 'PowerPartner' LIMIT 1].id;
        //
        User u1 = new User( email='test-user@fakeemail.com', contactid = contactRec.id, profileid = ProfileID, 
                UserName='test-user11@fakeemail.com', alias='tusr11', CommunityNickName='tusr11', 
                TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', 
                LanguageLocaleKey='en_US', FirstName = 'Test', LastName = 'User',Title = 'Key User' );
        insert u1;
        //
        Opportunity Opp = new Opportunity();
        Opp.Name = 'TestOpptyTriggers';
        Opp.StageName = 'Qualified';
        Opp.CloseDate = Date.Today().addDays(18);    
        Opp.AccountId = accountRec.Id;
        Opp.Sales_Representative__c = contactRec.Id;
        Opp.Notes__c = 'test';
        insert Opp;
        Opportunity Opp1 = new Opportunity();
        Opp1.Name = 'TestOpptyTriggers';
        Opp1.StageName = 'SR Approved';
        Opp1.CloseDate = Date.Today().addDays(18);    
        Opp1.AccountId = accountRec.Id;
        Opp1.Sales_Representative__c = contactRec.Id;
        Opp1.Notes__c = 'abcxyz';
        insert Opp1;
        Opportunity Opp2 = new Opportunity();
        Opp2.Name = 'TestOpptyTriggers';
        Opp2.StageName = 'Qualified';
        Opp2.CloseDate = Date.Today().addDays(18);    
        Opp2.AccountId = accountRec.Id;
        Opp2.Sales_Representative__c = contactRec.Id;
        Opp2.Partner_Notes__c = 'pqrs';
         insert Opp2;
         Opportunity Opp3 = new Opportunity();
        Opp3.Name = 'TestOpptyTriggers';
        Opp3.StageName = 'Qualified';
        Opp3.CloseDate = Date.Today().addDays(18);    
        Opp3.AccountId = accountRec.Id;
        Opp3.Sales_Representative__c = contactRec.Id;
        Opp3.Partner_Notes__c = 'pqrs';
         insert Opp3;
         
         Proposal__c pro = New Proposal__c();
            pro.Upfront_Payment__c = 70000;
            pro.System_Size_STC_DC__c = 25;
            pro.Sales_Rep_Email__c = 'testrep@yopmail.com';
            pro.Name = 'Testproposal';
            pro.Opportunity__c = Opp.Id;
            pro.Date_Issued__c = date.today();
            pro.Mode_Name__c  = 'Modetest';
            pro.Stage__c  = 'SR Approved';
            pro.Sunrun_Credit_Status__c = 'SR Credit Approved';
            insert pro;
            Proposal__c pro1 = New Proposal__c();
            pro1.Upfront_Payment__c = 70000;
            pro1.System_Size_STC_DC__c = 25;
            pro1.Sales_Rep_Email__c = 'testrep@yopmail.com';
            pro1.Name = 'Testproposal';
            pro1.Opportunity__c = Opp3.Id;
            pro1.Date_Issued__c = date.today();
            pro1.Mode_Name__c  = 'Modetest';
            pro1.Stage__c  = 'Voided';
            pro1.Sunrun_Credit_Status__c = 'SR Credit Approved';
            insert pro1;
        Opp.StageName = 'Unqualified';
        update Opp;  
            
         Notes__c note = New Notes__c();
         note.Opportunity__c = Opp1.Id;
         note.Proposal__c = pro.Id;
         note.Notes__c = 'abcxyz';
         insert note;
         Notes__c note2 = New Notes__c();
         note2.Opportunity__c = Opp2.Id;
         note2.Proposal__c = pro.Id;
         note2.Notes__c = 'pqrs';
         insert note2; 
         Opp1.Notes__c = 'tea';
         update Opp1;
         Opp2.Partner_Notes__c= 'coffee';
         update Opp2;
        
    }
}