SFDCProject/src/objects/Offer__c.object
<CustomObject>
    <description>This object is created to contain information specific to &quot;Offer&quot; type of Promotion.</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{0000000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_trg_Offer_after_insert.cls
@istest(seeAllData=true)
public with sharing class Test_trg_Offer_after_insert{
     static testMethod void Test_trg_Offer_after_insert(){
        Test.starttest();
       Account acc = new Account(name='Test13',billingpostalcode='9000',billingstate='CA'); 
       insert acc;        
       Lead l=new Lead(IsConverted=Boolean.valueOf('false'),Channel__c='TV',Web_Lead_From_Stage__c='Created',Company='a',  LastName='a');
       insert l;              
       Opportunity opp = new Opportunity(name='Test123',Accountid=acc.id,stagename='Created',CloseDate=system.today());
       insert opp;                   
       Offer__c ofc=new Offer__c(Lead__c=l.id);
       ofc.Opportunity__c=opp.id;
       insert ofc;
    test.stopTest();
     }
}