SFDCProject/src/objects/Partner_Contract__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Select the partner who this contract applies to</description>
        <inlineHelpText>Select the partner who this contract applies to</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Contracts</relationshipLabel>
        <relationshipName>Partner_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Select the date from which this contract is effective</description>
        <inlineHelpText>Select the date from which this contract is effective</inlineHelpText>
        <label>Effective From</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sign_Date__c</fullName>
        <description>Select the date when this contract was signed</description>
        <inlineHelpText>Select the date when this contract was signed</inlineHelpText>
        <label>Sign Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Partner Contract</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/SunRunValidateProfiles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of profiles used for deleting Account, Contact and Contract Objects.</description>
    <label>SunRunValidateProfiles</label>
</CustomObject>

SFDCProject/src/classes/TestPartnerContract.cls
@istest
private class TestPartnerContract {
	
	static  testmethod void testNewPartnerContract(){
		Account testAccount = TestPRMLibrary.insertAccount('TestPartnerContrac1', PRMLibrary.PARTNER);
		Partner_Contract__c contractObj = new  Partner_Contract__c();
		contractObj.Account__c = testAccount.Id;
		Date dateobj = DateTime.now().date();
		contractObj.Sign_Date__c = dateobj;
		contractObj.Effective_Date__c = dateobj;
		insert contractObj;
		System.assertNotEquals(contractObj.Id, null);	
		
		// Delete custom setting data
	    Id userProfileId = UserInfo.getProfileId();
        Profile profileObj = [Select Id, name from Profile where id = :userProfileId];
        List<SunRunValidateProfiles__c> listSRVP = new List<SunRunValidateProfiles__c>();        
		for(SunRunValidateProfiles__c SRVP:[select id, name from SunRunValidateProfiles__c where Name = :profileObj.Name LIMIT 1])
		{
			listSRVP.add(SRVP);
		}
		delete listSRVP;
				
		Boolean exceptionResult = false;
		try{
			delete contractObj;
		}catch(Exception exceptionObj){
			exceptionResult = true;
		}

		Account deleteAccount = TestPRMLibrary.insertAccount('PRMDeleteTest', PRMLibrary.PARTNER);
		exceptionResult = false;
		try{
			delete deleteAccount;
		}catch(Exception exceptionObj){
			exceptionResult = true;
		}

	}
	
}