SFDCProject/src/objects/PartnerDetail__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>PartnerAccountId__c</fullName>
        <label>PartnerAccountId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PartnerUserId__c</fullName>
        <label>PartnerUserId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>PartnerDetail</label>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Install_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals (Sales Partner)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_CustomPartnerLookup.cls
@isTest (SeeAllData = true)  
public class Test_CustomPartnerLookup {
	public static testmethod void TestCustomPartnerLookup() {

		Id userId = PartnerDetail__c.getValues('ApexTestAccount').PartnerUserId__c;
	User partnerUser = [Select id, name, email from User where Id =:userId];
	
	System.runAs(partnerUser){
		StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
		mock.setStaticResource('PartnerPortal');
		mock.setStatusCode(200); // Or other appropriate HTTP status code
		mock.setHeader('Content-Type', 'application/json'); // Or other appropriate MIME type like application/xml
		Test.setMock(HttpCalloutMock.class, mock);
		 //
		Test.startTest();
		    Account account = new Account();
		    account.Name = 'Lease Account';
		    account.BillingStreet = '1290 Happy Path';
		    account.BillingCity = 'San Francisco';
		    account.BillingState = 'CA';
		    account.BillingCountry = 'USA';
		    insert account;
		    //    
		   
		    Contact contact = new Contact();
		    contact.AccountId = account.Id;
		    contact.LastName = 'Lease';
		    contact.FirstName = 'Johnny';
		    contact.Email = 'JLease@Test.com';
		    contact.Phone = '2022022020'; 
		    contact.MailingStreet = '1290 Happy Path';
		    contact.MailingState = 'CA';
		    contact.MailingCountry = 'USA';
		    contact.MailingCity = 'San Francisco';
		    contact.MailingPostalCode = '95051';   
		    contact.Accreditation_period_start_date__c = Date.Today().addDays(-180);
		    contact.Accreditation_period_end_date__c = Date.Today().addDays(180);
		    contact.Birthdate = Date.Today();    
		    //           
		   insert contact;
		      
		     Opportunity oppty = new Opportunity();
		    oppty.AccountId = account.Id;
		    oppty.Name = 'EDPLookup Test';
		    oppty.StageName = 'Qualified';
		    oppty.CloseDate = Date.Today().addDays(18);
		    insert oppty;
		    //
		    Proposal__c proposal = new Proposal__c();
		    proposal.Opportunity__c = oppty.Id;
		    proposal.Sales_Rep_Email__c = 'partnerrep@repsfortesting.com';
		    proposal.Date_Issued__c = Date.Today().addDays(18);
		    proposal.Mode_Name__c = 'Mode323';
		    proposal.System_Size_STC_DC__c = 1290;
		    proposal.Upfront_Payment__c = 1290;
		    proposal.sales_partner__c = PartnerDetail__c.getValues('ApexTestAccount').PartnerAccountId__c;
		    proposal.Install_Partner__c = PartnerDetail__c.getValues('ApexTestAccount').PartnerAccountId__c;
		    insert proposal;
			
			ApexPages.currentPage().getParameters().put('proposalId', proposal.Id);
			ApexPages.currentPage().getParameters().put('lksrch', 'Johnny');
			ApexPages.currentPage().getParameters().put('idValue', 'Contact');
			CustomPartnerLookup CustomPartnerLookupobj = new CustomPartnerLookup();
		
			Integer pagenumber = CustomPartnerLookupobj.pageNumber;
			CustomPartnerLookupobj.first();
			CustomPartnerLookupobj.getFormTag();
			CustomPartnerLookupobj.getResults();
			CustomPartnerLookupobj.getTextBox();
			CustomPartnerLookupobj.first();
			boolean testVar1 = CustomPartnerLookupobj.hasNext;
			boolean testVar2 = CustomPartnerLookupobj.hasPrevious;
			CustomPartnerLookupobj.last();
			CustomPartnerLookupobj.next();
			CustomPartnerLookupobj.previous();
			CustomPartnerLookupobj.search();
		
		
		Test.stopTest();
	}
		
	}
}