SFDCProject/src/objects/PartnerDetail__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>PartnerAccountId__c</fullName>
        <label>PartnerAccountId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PartnerContactEmail__c</fullName>
        <label>PartnerContactEmail</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>PartnerDetail</label>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EDP_Phase__c</fullName>
        <label>EDP_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>EDP Phase-0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDP Phase-1</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Install_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <formula>TEXT( Opportunity__r.Lead_Source_2__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Source</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposal_ID__c</fullName>
        <description>The proposal identification number.</description>
        <label>Proposal ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals (Sales Partner)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Service_Contract_Event__c.object
<CustomObject>
    <fields>
        <fullName>Commencement_of_Construction__c</fullName>
        <label>Commencement of Construction</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Completion_of_Construction__c</fullName>
        <label>Completion of Construction</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_s_Email__c</fullName>
        <label>Customer&apos;s Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>External_id__c</fullName>
        <externalId>true</externalId>
        <label>External id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <formula>TEXT(Service_Contract__r.Opportunity__r.Lead_Source_2__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Source</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Service_Contract__r.Opportunity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>Contains Sales Rep email address from proposal where SC was generated</description>
        <label>Sales Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Service Contract Events</relationshipLabel>
        <relationshipName>Service_Contract_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Contract Event</label>
    <nameField>
        <displayFormat>SCA-{00000}</displayFormat>
        <label>Service Contract Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/UnitTest_CostcoSC.cls
@istest(seealldata=true)
public with sharing class UnitTest_CostcoSC {
	 static testmethod void testMethod1(){
		String partnerAccountId = PartnerDetail__c.getValues('ApexTestAccount').PartnerAccountId__C;
		String salesRepEmail = PartnerDetail__c.getValues('ApexTestAccount').PartnerContactEmail__C;
		Proposal__C proposalObj = new Proposal__C();
        Account accountObj = TestPRMLibrary.insertAccount('Test Acc123', 'Residential');
        Contact primaryContact = TestPRMLibrary.insertContact(accountObj.Id, 'Residential', 'firstName'+ '-1', 'lastName'+'-1', 'first.' + 'customerEmail@yopmail.com');
        Contact secondaryContact = TestPRMLibrary.insertContact(accountObj.Id, 'Residential', 'firstName'+ '-2', 'lastName'+'-2', 'second.' + 'customerEmail@yopmail.com');
        Opportunity oppotyObj=new Opportunity();
		oppotyObj.channel_2__c='Retail';
		oppotyObj.Lead_Source_2__c='Costco';
		oppotyObj.accountid=accountObj.id;
		oppotyObj.external_id__c='123456';
		oppotyObj.name='TESt';
		oppotyObj.stageName='Open';
		insert oppotyObj;
        proposalObj.Name = 'P124124123-I';
        proposalObj.Opportunity__c = oppotyObj.Id;
        proposalObj.Upfront_Payment__c = 1000;
        proposalObj.Proposal_ID__c = 23532;
        proposalObj.System_Size_STC_DC__c = 23;
        proposalObj.Mode_Name__c = 'Mode-1';
        proposalObj.Date_Issued__c =  date.today();
        proposalObj.Sales_Rep_Email__c = salesRepEmail; 
        proposalObj.Sales_Partner__c = partnerAccountId;
        proposalObj.Install_Partner__c = partnerAccountId;
        proposalObj.EDP_Phase__c = 'EDP Phase-1';
        proposalObj.stage__c = EDPUtil.SR_OPS_APPROVED;
        insert proposalObj;
        ServiceContract sc = new ServiceContract();
        sc.accountId = accountObj.Id;
        sc.Proposal__c = proposalObj.id;
        sc.Opportunity__c = oppotyObj.Id;
        sc.ContactId=primaryContact.id;
        insert sc;
        Service_contract_event__c sce=new Service_contract_event__c();
        sce.service_contract__c=sc.id;
        //sce.Customer_s_Email__c='TEST@yopmail.com';
        //sce.Sales_Rep_Email__c='TEST@yopmail.com';
        insert sce;
          
           Test.startTest();
       		 sce.Commencement_of_Construction__c=system.today();
        	 sce.Completion_of_Construction__c=system.today();
       		 update sce;
       		 List<Service_Contract_Event__c> sceToBeUpdated = new List<Service_Contract_Event__c>();
       		 sceToBeUpdated.add(sce);
       		 BaseClass bas=new BaseClass();
       		 bas.enqueueJobWithCheck(new CostcoLeadUpdateInstallInfoJob(bas.getUniqueIdList(sceToBeUpdated)));
           Test.stopTest();
          
        /*
        ApexPages.StandardController controller = new ApexPages.StandardController(proposalObj);
       CreateServiceContractController serviceContractController = new CreateServiceContractController(controller);
       PageReference page = serviceContractController.create();
       //get object id from page reference
       String objectId = page.getURL().right(page.getURL().length() - 1);
       
       Set<Id> contractIds = new Set<Id>();
       contractIds.add(objectId);
       Map<Id, ServiceContract> contractMap = ServiceContractUtil.getServiceContractMap(contractIds);
       ServiceContract scObj = contractMap.get(objectId);  
       if(scObj.Service_Contract_Events__r != null && !scObj.Service_Contract_Events__r.isEmpty()){
           Service_contract_event__c scEventObj = scObj.Service_Contract_Events__r[0];
           Test.startTest();
       		 scEventObj.Commencement_of_Construction__c=system.today();
        	 scEventObj.Completion_of_Construction__c=system.today();
       		 update scEventObj;
           Test.stopTest();
       }  
        //Service_contract_event__c sce=new 
        //Service_contract_event__c sce=[select id,Commencement_of_Construction__c,Completion_of_Construction__c,service_contract__r.opportunity__r.external_id__c,lead_source__c from Service_contract_event__c where Service_Contract__c=:sc.id];
        //sce.Commencement_of_Construction__c=system.today();
        //sce.Completion_of_Construction__c=system.today();
        */
		
	}
}