SFDCProject/src/objects/Partner_Api_Field__c.object
<CustomObject>
    <description>Object used to define the Partner APIs rest to SFDC field mappings.</description>
    <fields>
        <fullName>Api__c</fullName>
        <inlineHelpText>The api, which this mapping is applicable to.</inlineHelpText>
        <label>Api</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Api</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Api</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal Api</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Api</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Api</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Api</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opty Api</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduler Api</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Api</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rest_Field__c</fullName>
        <inlineHelpText>The Rest field name of the api. Note that Rest field names are case sensitive and must follow lowerCamelCase format.</inlineHelpText>
        <label>Rest Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sfdc_Field__c</fullName>
        <inlineHelpText>Salesforce field which this record&apos;s rest field should map to. This should be an actual Salesforce API field in specified Sobject. Api name could contain parent relationship references. For ex., for ServiceContract, this could be Opportunity__r.Deal_Id__c</inlineHelpText>
        <label>Sfdc Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sobject__c</fullName>
        <inlineHelpText>The Salesforce Object name. For ex., Contact or Lead or Opportunity or Proposal__c etc.,</inlineHelpText>
        <label>Sobject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Api Field</label>
    <nameField>
        <displayFormat>PAF-{0000000000}</displayFormat>
        <label>Partner Api Field#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Api Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/PartnerApiFieldTest.cls
@IsTest
public class PartnerApiFieldTest {
	
    testmethod public static void testTrigger() {
        Partner_Api_Field__c field = new Partner_Api_Field__c();
        try {
	        insert field;
            System.assert(false, 'Expected a exception due to missing requried fields');
        } catch (Exception e) {
            //Exception is expected
        }
        field.Api__c = 'Test Api';
        field.Rest_Field__c = 'foo';
        field.Sobject__c = 'Contact';
        field.Sfdc_Field__c = 'non_existing_contact_field__c';
        
        try {
	        insert field;
            System.assert(false, 'Expected a exception due to invalid sfdc field');
        } catch (Exception e) {
            //Exception is expected
        }

        field.Sfdc_Field__c = 'FirstName';
        insert field;
		
        //Now insert second field with same rest field and expect it to fail.
        Partner_Api_Field__c field2 = new Partner_Api_Field__c();
        field2.Api__c = 'Test Api';
        field2.Rest_Field__c = 'foo';
        field2.Sobject__c = 'Contact';
        field2.Sfdc_Field__c = 'FirstName';
        try {
	        insert field2;
            System.assert(false, 'Expected a exception due to duplicate rest field mapping');
        } catch (Exception e) {
            //Exception is expected
        }
        
        //Now update the field to non existing value and it should fail.
        field.Sfdc_Field__c = 'non_existing_contact_field__c';
        try {
	        update field;
            System.assert(false, 'Expected a exception due to invalid sfdc field while updating');
        } catch (Exception e) {
            //Exception is expected
        }
        field.Sfdc_Field__c = 'LastName';
        update field;
    }
    
    testmethod public static void validateRelationshipField() {
        Partner_Api_Field__c field = new Partner_Api_Field__c();
        field.Api__c = 'Test Api';
        field.Rest_Field__c = 'standardRelationField';
        field.Sobject__c = 'Contact';
        field.Sfdc_Field__c = 'NonExisting.Name';
        
        try {
        	insert field;
            System.assert(false, 'Expected a exception due to invalid sfdc field while updating');
        } catch (Exception e) {
            //Expected
        }
     	
        //Now change to valid relationship field and insert.
        field.Sfdc_Field__c = 'Account.Name';
        insert field;
        
        //Same thing for custom relationship field
        field = new Partner_Api_Field__c();
        field.Api__c = 'Test Api';
        field.Rest_Field__c = 'customRelationField';
        field.Sobject__c = 'Contact';
        field.Sfdc_Field__c = 'NonExisting__r.Name';
        
        try {
        	insert field;
            System.assert(false, 'Expected a exception due to invalid sfdc field while updating');
        } catch (Exception e) {
            //Expected
        }
     	
        //Now change to valid relationship field and insert.
        field.Sfdc_Field__c = 'Location__r.Name';
        insert field;
    }
}