SFDCProject/src/objects/Partners_For_Service_Contrac_Batch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Partner_Id__c</fullName>
        <label>Partner Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Partners For Service Contract Batch</label>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Create_Service_Contract__c</fullName>
        <label>Create Service Contract</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals (Sales Partner)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sunrun_Credit_Status__c</fullName>
        <label>Sunrun Credit Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/ServiceContract_Batch.cls
/* 
** Class: ServiceContract_Batch
** Author: Raghavendra Masineni
** 
**
*/

global class ServiceContract_Batch implements Database.Batchable <sObject>, Database.Stateful {
	
	public Static Set<String> partnerIds = new Set<String>();
	public Set<String> salesPartnerIds;
	public String query = null;
	public String proposalFilter = null;
	public boolean testing = false;
	public static Map<String, Partners_For_Service_Contrac_Batch__c> partnersForSCBatchMap = new Map<String, Partners_For_Service_Contrac_Batch__c>();

    static
    {              
        partnersForSCBatchMap = Partners_For_Service_Contrac_Batch__c.getAll();
        for(Partners_For_Service_Contrac_Batch__c scBatchObj: partnersForSCBatchMap.values()){
        	if(scBatchObj.Partner_Id__c != null && scBatchObj.Partner_Id__c != ''){
        		partnerIds.add(scBatchObj.Partner_Id__c);
        	}
        }
	}

	public ServiceContract_Batch(Boolean testing){
		this.salesPartnerIds = ServiceContract_Batch.partnerIds;
		System.debug('this.salesPartnerIds: ' + this.salesPartnerIds);
		this.testing = testing;
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		String stage = 'SR Approved';
		String creditStatus = 'SR Credit Approved';
		String createSC = 'Yes';
		query = 'Select Id, name, Create_Service_Contract__c,Sunrun_Credit_Status__c,stage__c,Sales_Partner__c from Proposal__c where Create_Service_Contract__c =:createSC and Sunrun_Credit_Status__c =:creditStatus and stage__c =:stage and Sales_Partner__c in :salesPartnerIds  ' ;
		if(Test.isRunningTest()){
			query += ' limit 1 ';
		}
        System.debug('XXXXXXXXXXXXXXXXXXXXXXX query: ' + query);
        return Database.getQueryLocator(query);
        
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        ServiceContractUtil.createServiceContract((List<Proposal__c>) scope);
        return;
    }
    
    global void finish(Database.BatchableContext BC){
		BatchUtil.processBatchErrors(bc);
    }
}