SFDCProject/src/objects/Phase__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Phases</relationshipLabel>
        <relationshipName>Phases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Project__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Task__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Required</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <picklist>
            <picklistValues>
                <fullName>Branch Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brea PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drafting Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspection Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interconnection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Milestone Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NTP Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting/Design Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planner/Brea PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Payment Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Change Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialist Team</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Phase__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phase__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <controllingField>Group_Name__c</controllingField>
            <picklistValues>
                <fullName>Construction Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer-Facing Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discrepancy with Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete Design Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jurisdiction Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Documents for Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing for NTP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offsetting Electricity Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Information Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunrun Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Disqualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update Permit</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Reason__c</fullName>
        <label>Sub-Reason</label>
        <picklist>
            <controllingField>Reason__c</controllingField>
            <picklistValues>
                <fullName>AHJ:  Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AHJ Comments/Redlines: Existing Requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AHJ Comments/Redlines: New Requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attached Home Approval Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOM Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breaker size discrepancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation request: Verbal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation request: written</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change order: customer rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Order Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Code Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constructability: electrical panel relocation required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constructability: existing permitting issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constructability: minimum system size not met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constructability: non-qualifying panel upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constructability: poor roof condition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constructability: structural issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constructability: unpermitted structures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constructability: unsupported roof surface</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction Change Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract/ Utility Address Discrepancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County/ Title Discrepancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit memo or rebate outstanding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer facing change order required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Nonresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer rejected change order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer requested cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Signature Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discrepancy within Planset</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Description__c</fullName>
        <label>Task Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Task_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adhoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rework</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Workflow Task</label>
    <nameField>
        <label>Workflow Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflow Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/wfcreateAdhocTaskClass.cls
public class wfcreateAdhocTaskClass {
  public boolean editModeSec{get;set;}
    //public task__c originalTask {get; set;} 
    public task__c newtask{get; set;}
    DateTime dT = System.now();
    list<Task__c> openTasks {get; set;}
    public DateTime CurrentDate = DateTime.newinstance(dT.getTime()); 
    public id projectId = System.currentPagereference().getParameters().get('projectId');
    public  String returnUrl = System.currentPagereference().getParameters().get('returnUrl');
    public List<Opportunity_Team__c> optyRoleList {get;set;}
    
    public wfcreateAdhocTaskClass(ApexPages.StandardController controller) {
        system.debug('returnUrl:' + returnUrl);
        this.newtask = (Task__c)Controller.getRecord();
        if(newTask == null){
            editModeSec = true;
            newTask = new task__c();
            initialize();
            system.debug('newtask Null');
        }
        if(newTask.id != null){
            newTask = [select id, name, Type__c,Status__c,Phase__r.name,Project_Name__c,Group_Name__c,Reason__c,Sub_Reason__c,
                       Task_Description__c,phase__r.Project__r.name,Task_Owner__c, Category__c,Open_Date__c,Start_Date__c,Notify_Owner__c from task__c where id =: newTask.Id];
            initialize();
            system.debug('NewTask Not Null');
        }
        else{
            system.debug('else');
            editModeSec = true;
            initialize();
            
        }
      system.debug('STANDARD CONTROLLER CONSTRUCTOR');
    }
    
    private void initialize(){
        newTask.Type__c = 'Adhoc';
        newTask.Category__c = 'Required';
        newTask.Start_Date__c = CurrentDate; 
        newtask.Project_Name__c =  ProjectId;
        newTask.Status__c = 'Open';
    }
    
    public PageReference backToSearch() {
         // editModeSec = true;
        if(returnUrl != null){
            pageReference returnToTaskView;
            returnToTaskView = new pageReference(returnUrl);
            return returnToTaskView;
        } else {
            pageReference returnToPrjctSearch;
            returnToPrjctSearch = new pageReference('/apex/wfProjectDetails?id='+projectId);
            return returnToPrjctSearch;
          //return page.TaskSearchOffset;
            
        }
          
    }
    
    public PageReference editTask() {
        
        editModeSec =true;
        PageReference pageRef = new PageReference('/apex/wfCreateAdhocTaskOnproject?id='+newtask.id + '&gmaps=1'); 
        return pageRef;  
    }
    
    
     //Method to assign optyTeam contact user as adhoc task owner based role & group information
    private void assignOptyTeamRoleToTaskOwner(task__c task)
    {
        String optyId=[SELECT Opportunity__r.id  FROM Project__c where Id=:projectId limit 1].Opportunity__r.id;  
        system.debug('optyId:::::' + optyId);
        optyRoleList =[SELECT Id, Role__c, user__c, Opportunity__c FROM Opportunity_Team__c where Opportunity__c=:optyId];
        for(Opportunity_Team__c optyRole : optyRoleList) {
            If(optyRole.Role__c==task.Group_Name__c)
            {
                task.Task_Owner__c= optyRole.user__c;
            }
        }
        update task;
    } 
    
    public  void saveAdhocTask(){

       System.Savepoint sp1 = Database.setSavepoint();
       try{
       
               editModeSec = false;
               upsert newTask;
               system.debug('Inserted Task:: '+newTask);
               String message ='Task Cloned Successfully';
               ApexPages.Message myMsg = new ApexPages.Message(ApexPages.severity.Info, 'Success', message);
               ApexPages.addMessage(myMsg);
               if(newTask.id != null)
                   newTask = [select id, name, Type__c,Status__c,Notify_Owner__c,Phase__r.name,Group_Name__c,Task_Description__c,phase__r.Project__r.name,Task_Owner__c, Project_Name__c,
                              Category__c,Open_Date__c,Start_Date__c,Reason__c,Sub_Reason__c from task__c where id =: newTask.Id]; 
               assignOptyTeamRoleToTaskOwner(newTask);
           
       } catch (System.DmlException e) {
            system.debug('error: ' + e);
            Database.rollback(sp1);
            for (Integer i=0; i < e.getNumDml(); i++) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, e.getDmlMessage(i)));
            } 
       } catch(Exception e){
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error, e.getmessage() ));
            }
            
    }
    
        // show all open tasks related to a project
   /* public list<task__c> getShowOpenTasks(){
        if(projectId != null){
            openTasks = [select Id, Name, Status__c,Open_Date__c,Start_Date__c, Category__c ,Project_Name__c from task__c 
                         where Project_Name__c =:projectId and Status__c ='Open'] ;  
        }
        return openTasks;
    }*/
    

    
}