SFDCProject/src/objects/Phase__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Phases</relationshipLabel>
        <relationshipName>Phases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Project__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Task__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <picklist>
            <picklistValues>
                <fullName>Branch Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brea PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drafting Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspection Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interconnection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Milestone Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NTP Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting/Design Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planner/Brea PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Payment Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Change Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialist Team</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Phase__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phase__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <formula>Project_Name__r.Service_Contract__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Contract</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Workflow Task</label>
    <nameField>
        <label>Workflow Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflow Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/testWfTaskSearch.cls
@ isTest (seeAllData = true)
public class testWfTaskSearch {
  
    public static testmethod void unitTestOne(){
        Profile p = [select id from profile where Name ='System Administrator' limit 1]; 
       User pu = new User(profileId = p.id, username ='testemail', email ='one@email.com',emailencodingkey = 'UTF-8', localesidkey = 'en_US',  languagelocalekey = 'en_US', timezonesidkey = 'America/Los_Angeles',  alias='cspu', lastname='lastname', firstname = 'firstname', title = 'developer');
        
        Account a = new Account(name='Test Acct1');
            insert a;
            
            Opportunity oppty = new Opportunity();
            oppty.AccountId = a.Id;
            oppty.Name = 'NewCC Test';
            oppty.StageName = 'Qualified';
            oppty.CloseDate = Date.Today().addDays(18);
            insert oppty;
            //
            //Proposal__c proposal = UnitTest_ServiceContractUtil.createProposal(oppty.Id);
            //
            Proposal__c proposal = new Proposal__c();
            proposal.Opportunity__c = oppty.Id;
            proposal.Sales_Rep_Email__c = 'Salesrep@repsfortesting.com';
            proposal.Date_Issued__c = Date.Today().addDays(18);
            proposal.Mode_Name__c = 'Mode323';
            proposal.System_Size_STC_DC__c = 1290;
            proposal.Upfront_Payment__c = 1290;
            //proposal__c proposal = UnitTest_ServiceContractUtil.createTestProposal();
            insert proposal;   
           
            ServiceContract scAssetRec = new ServiceContract();
            scAssetRec.accountId = a.Id;
           // scAssetRec.contactId = contactRec.Id;  
            scAssetRec.Proposal__c = proposal.id;
            scAssetRec.Opportunity__c = oppty.Id;
            insert scAssetRec;
                
             project__c proj = new project__c ( name = 'test project', Account__c= a.Id , Opportunity__c= oppty.id, Proposal__c = proposal.id, service_contract__c = scAssetRec.id); 
             
           insert proj;
        
        
        Phase__c phase = new Phase__c(name='testPhase', Project__c=proj.Id);
        insert phase;
        
           task__c tasklocal = new task__c();
           tasklocal.name = 'testTask';
           tasklocal.Group_Name__c = 'Branch manager';
           tasklocal.phase__c = phase.id;
           tasklocal.project_Name__c = proj.id;
           insert tasklocal;
        
        wfTaskSearchNew tsksearch  = new wfTaskSearchNew();
        Test.startTest();
        PageReference pageRef = Page.wfTaskSearch;
        Test.setCurrentPage(pageRef);
        
        tsksearch.getViews();
        tsksearch.getSearchBy();
        //tsksearch.getTasksForSelectedView();
        
       // tsksearch.taskListdisp[0].taskObj.name =   tw = new tsksearch.tasks();
      //  System.assertEquals(tw.checked,false);

       // tsksearch.tasks cw2 = new tsksearch.tasks(new task__c(name='Tast Task'), false);
        //System.assertEquals(tsksearch.taskListdisp.isEmpty(),false);
        tsksearch.doSearch();
        tsksearch.userActions();
        tsksearch.viewName = 'AllTasks';
         if(tsksearch.taskListdisp.size() >= 2  ) {
        tsksearch.taskListdisp[0].taskObj.Task_Owner__c = null;
        tsksearch.taskListdisp[0].checked = true;
        tsksearch.taskListdisp[1].checked = true;
        tsksearch.DoSave();
        tsksearch.taskListdisp[0].taskObj.Task_Owner__c = pu.id;
        tsksearch.DoSave();
        tsksearch.taskListdisp[0].taskObj.Task_Owner__c = null;
        tsksearch.DoSave();
        //tsksearch.clonedTask = tasklocal ;
        tsksearch.getloadtable();
          
          wfTaskSearchNew.wrapper testTable3 = new wfTaskSearchNew.wrapper();
          testTable3.selectedValue ='InstallBranch';
          testTable3.searchText = 'test';
          tsksearch.tableList.add(testTable3);
          wfTaskSearchNew.wrapper testTable4 = new wfTaskSearchNew.wrapper();
          testTable4.selectedValue ='Phase';
          testTable4.searchText = 'test';
          tsksearch.tableList.add(testTable4);
          wfTaskSearchNew.wrapper testTable5 = new wfTaskSearchNew.wrapper();
          testTable5.selectedValue ='Group';
          testTable5.searchText = 'Add Values';
           tsksearch.tableList.add(testTable5);
           wfTaskSearchNew.wrapper testTable6 = new wfTaskSearchNew.wrapper();
          testTable6.selectedValue ='CustomerName';
          testTable6.searchText = 'test';
           tsksearch.tableList.add(testTable6);
         
           
        tsksearch.DoAdd();
        tsksearch.removeRow();
        tsksearch.DoAdd();
        tsksearch.DoAdd();
        tsksearch.DoAdd();
        tsksearch.DoAdd();
        tsksearch.DoAdd();
        
        tsksearch.getMytableRecords();
        
        
       
      
        //tsksearch.saveClone();
        
       
        tsksearch.first();
        tsksearch.Next();
        tsksearch.previous();
        tsksearch.last();
        tsksearch.getHasNext();
        tsksearch.getHasPrevious();
        tsksearch.getTotal_size();
        tsksearch.getPageNumber();
        tsksearch.getTotalPages();
        tsksearch.getTasks();
        }
        Test.StopTest();

    }
    
    public static testmethod void unitTestTwo(){
        Profile p = [select id from profile where Name ='System Administrator' limit 1];   
        User pu = new User(profileId = p.id, username ='testemail', email ='one@email.com',emailencodingkey = 'UTF-8', localesidkey = 'en_US',  languagelocalekey = 'en_US', timezonesidkey = 'America/Los_Angeles',  alias='cspu', lastname='lastname', firstname = 'firstname', title = 'developer');
        Account a = new Account (Name ='Test12345');
        try{
          insert a ;
        }
        catch(exception e){}
        
        Project__c proj = new Project__c(name='testProp');
        insert proj;
        Phase__c phase = new Phase__c(name='testPhase', Project__c=proj.Id);
        insert phase;
        Task__c tasklocal = new Task__c(name='testTask', Project_Name__c =proj.id, Phase__c = phase.Id);
        insert tasklocal;
        wfTaskSearchNew tsksearch  = new wfTaskSearchNew();
        Test.startTest();
        PageReference pageRef = Page.wfTaskSearch;
        Test.setCurrentPage(pageRef);
        tsksearch.errorMessage ='test eror';
        tsksearch.noOfRecords =20;
        tsksearch.size =10;
        tsksearch.getViews();
        tsksearch.getSearchBy();
        //tsksearch.getTasksForSelectedView();
        
       // tsksearch.taskListdisp[0].taskObj.name =   tw = new tsksearch.tasks();
      //  System.assertEquals(tw.checked,false);

       // tsksearch.tasks cw2 = new tsksearch.tasks(new task__c(name='Tast Task'), false);
        //System.assertEquals(tsksearch.taskListdisp.isEmpty(),false);
        tsksearch.getloadtable();
        tsksearch.DoAdd();
          wfTaskSearchNew.wrapper testTable27 = new wfTaskSearchNew.wrapper();
          testTable27.selectedValue ='InstallPartner';
          testTable27.searchText = 'test';
          tsksearch.tableList.add(testTable27);
        tsksearch.DoAdd();
          wfTaskSearchNew.wrapper testTable17 = new wfTaskSearchNew.wrapper();
          testTable17.selectedValue ='InstallPartner';
          testTable17.searchText = 'test';
          tsksearch.tableList.add(testTable17);
        tsksearch.DoAdd();
        tsksearch.DoAdd();
        tsksearch.DoAdd();
        tsksearch.DoAdd();
        
          wfTaskSearchNew.wrapper testTable7 = new wfTaskSearchNew.wrapper();
          testTable7.selectedValue ='InstallPartner';
          testTable7.searchText = 'test';
           //tsksearch.tableList.add(testTable7); 
         /*  wfTaskSearchNew.wrapper testTable8 = new wfTaskSearchNew.wrapper();
          testTable8.selectedValue ='TaskOwner';
          testTable8.searchText = '005600000034S8I';
           tsksearch.tableList.add(testTable8); */
           wfTaskSearchNew.wrapper testTable1 = new wfTaskSearchNew.wrapper();
          testTable1.selectedValue ='Task';
          testTable1.searchText = 'test5';
          tsksearch.tableList.add(testTable1);
          wfTaskSearchNew.wrapper testTable2 = new wfTaskSearchNew.wrapper();
          testTable2.selectedValue ='Project';
          testTable2.searchText = '1222';
          tsksearch.tableList.add(testTable2);
          wfTaskSearchNew.wrapper testTable3 = new wfTaskSearchNew.wrapper();
          testTable3.selectedValue ='InstallBranch';
          testTable3.searchText = 'test';
          tsksearch.tableList.add(testTable3);
          wfTaskSearchNew.wrapper testTable4 = new wfTaskSearchNew.wrapper();
          testTable4.selectedValue ='Phase';
          testTable4.searchText = 'test';
          tsksearch.tableList.add(testTable4);
          wfTaskSearchNew.wrapper testTable5 = new wfTaskSearchNew.wrapper();
          testTable5.selectedValue ='Group';
          testTable5.searchText = 'Add Values';
           tsksearch.tableList.add(testTable5);
           wfTaskSearchNew.wrapper testTable6 = new wfTaskSearchNew.wrapper();
          testTable6.selectedValue ='CustomerName';
          testTable6.searchText = 'test';
           tsksearch.tableList.add(testTable6);
           WfTaskSearchNew.wrapper testTable9 = new wfTaskSearchNew.wrapper();
          testTable9.selectedValue ='SalesPartner';
          testTable9.searchText = 'test';
           tsksearch.tableList.add(testTable9); 
           wfTaskSearchNew.wrapper testTable10 = new wfTaskSearchNew.wrapper();
          testTable10.selectedValue ='SlaStatus';
          testTable10.searchText = 'Missed SLA';
           tsksearch.tableList.add(testTable10);
           wfTaskSearchNew.wrapper testTable11 = new wfTaskSearchNew.wrapper();
          testTable11.selectedValue ='TaskStatus';
          testTable11.searchText = 'Complete';
           tsksearch.tableList.add(testTable11); 
        tsksearch.viewName = 'AllTasks';
         if(tsksearch.taskListdisp.size() > 0  ) {
        tsksearch.taskListdisp[0].taskObj.Task_Owner__c = null;
        tsksearch.DoSave();
        tsksearch.taskListdisp[0].taskObj.Task_Owner__c = pu.id;
        tsksearch.DoSave();
        tsksearch.taskListdisp[0].taskObj.Task_Owner__c = null;
        tsksearch.DoSave();
        }
        //tsksearch.clonedTask = tasklocal ;
        tsksearch.getMytableRecords();
        tsksearch.doSearch();
        
        tsksearch.viewName = 'myOpenTasks';
        //tsksearch.doSearch();
        tsksearch.userActions();
        tsksearch.viewName = 'myGroupTasks';
        //tsksearch.doSearch();
        tsksearch.userActions();
        tsksearch.viewName = '';
        tsksearch.userActions(); 
        //tsksearch.doSearch();
       
        tsksearch.first();
        tsksearch.Next();
        tsksearch.previous();
        tsksearch.last();
        tsksearch.getHasNext();
        tsksearch.getHasPrevious();
        tsksearch.getTotal_size();
        tsksearch.getPageNumber();
        tsksearch.getTotalPages();
        tsksearch.getTasks();
        
        Test.StopTest();

    }
  
  public static testmethod void unitTestThird(){
        Profile p = [select id from profile where Name ='System Administrator' limit 1];   
        User pu = new User(profileId = p.id, username ='testemail', email ='one@email.com',emailencodingkey = 'UTF-8', localesidkey = 'en_US',  languagelocalekey = 'en_US', timezonesidkey = 'America/Los_Angeles',  alias='cspu', lastname='lastname', firstname = 'firstname', title = 'developer');
        Account a = new Account (Name ='Test12345');
        try{
          insert a ;
        }
        catch(exception e){}
        Project__c proj = new Project__c(name='testProp');
        insert proj;
        Phase__c phase = new Phase__c(name='testPhase', Project__c=proj.Id);
        insert phase;
        Task__c tasklocal = new Task__c(name='testTask', Project_Name__c =proj.id, Phase__c = phase.Id);
        insert tasklocal;
        wfTaskSearchNew tsksearch  = new wfTaskSearchNew();
        Test.startTest();
        PageReference pageRef = Page.wfTaskSearch;
        Test.setCurrentPage(pageRef);
        
        tsksearch.getViews();
        tsksearch.getSearchBy();
        
       // tsksearch.tasks cw2 = new tsksearch.tasks(new task__c(name='Tast Task'), false);
        //System.assertEquals(tsksearch.taskListdisp.isEmpty(),false);
        tsksearch.doSearch();
        tsksearch.userActions();
        tsksearch.viewName = 'AllTasks';
         if(tsksearch.taskListdisp.size() >= 3  ) {
        tsksearch.taskListdisp[0].taskObj.Task_Owner__c = null;
        tsksearch.taskListdisp[0].checked = true;
        tsksearch.taskListdisp[1].checked = true;
        tsksearch.taskListdisp[2].checked = true;
        tsksearch.DoSave();
        tsksearch.taskListdisp[0].taskObj.Task_Owner__c = pu.id;
        tsksearch.DoSave();
        tsksearch.taskListdisp[0].taskObj.Task_Owner__c = null;
        tsksearch.DoSave();
        //tsksearch.clonedTask = tasklocal ;
        tsksearch.getloadtable();
      }
       // tsksearch.AssignTasks();
        //tsksearch.cloneTask();
        test.stopTest();
        
  }
    
    
}