SFDCProject/src/objects/Phase__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Phases</relationshipLabel>
        <relationshipName>Phases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Project__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Task__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Last_Modified_Date__c</fullName>
        <formula>DATEVALUE(LastModifiedDate)</formula>
        <label>Last Modified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Phase__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phase__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflow Task</label>
    <nameField>
        <label>Workflow Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflow Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/wfValidateTasksBatch.cls
global class wfValidateTasksBatch implements Database.Batchable<String>, Database.AllowsCallouts, Database.Stateful {
	global  Map<Id, Map<Id, Set<String>>> validationReport = new  Map<Id, Map<Id, Set<String>>>();
	global Iterable<String> start(Database.BatchableContext bc) {
		String completedStr = 'Complete';
		string requiredStr = 'Required';
		string onHoldStr = 'On-Hold';
    	Date currentDate = Date.today();
    	List<String> projectIds = new List<String>();
    	Set<String> tempProjectIds = new Set<String>();
		String taskSOQLStr = 'select Id, phase__r.project__c, Last_Modified_Date__c from Task__c where Last_Modified_Date__c =:currentDate ';
		if(Test.isRunningTest()){
			taskSOQLStr += ' limit 2 ' ;
		}
		
		//for(Task__c taskObj : [select Id, phase__r.project__c, Last_Modified_Date__c from Task__c where Last_Modified_Date__c =:currentDate]){
		for(Task__c taskObj : Database.query(taskSOQLStr)){
				tempProjectIds.add(taskObj.phase__r.project__c);
		}
		if(!tempProjectIds.isEmpty()){
			projectIds.addall(tempProjectIds);
		}
        return projectIds;
    }
    
    global void execute(Database.BatchableContext BC, List<String> projectIds){
        try {
			wfValidateTasks.validateProjects(projectIds, validationReport);
			//wfValidateTasks.emailValidationReport(validationReport);
        } catch (Exception e) {
			System.debug('Exception: ' + e);
            //ExceptionLogger.logException(utils.getCurrentClassName(), 'Exception while Updating IKnock with Lead Urls for ' + leads, e);
        }	
    }
    
    global void finish(Database.BatchableContext BC){
		wfValidateTasks.emailValidationReport(validationReport);
    }

}