SFDCProject/src/objects/Phase__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Phase_Status__c</fullName>
        <label>Phase Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Phases</relationshipLabel>
        <relationshipName>Phases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Project__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Task__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Required</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Phase__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Phase__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <formula>Project_Name__r.Service_Contract__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Contract</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Workflow Task</label>
    <nameField>
        <label>Workflow Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflow Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/testWfProjTaskHelper.cls
@ isTest (seeAllData = true)
public class testWfProjTaskHelper {

     public static testmethod void unitTestOne(){
         
          ServiceContract sc = [select id from ServiceContract limit 1];  
        Test.startTest();
        Project__c proj = new Project__c(name='testProp', service_contract__c = sc.id);
        insert proj;
          Project__c proj1 = new Project__c(name='testProp1', service_contract__c = sc.id,status__c='Blocked');
        insert proj1;
        system.assertNotEquals(null, proj.id) ; 
        Phase__c phase = new Phase__c(name='testPhase', Project__c=proj.Id, Phase_Status__c='INACTIVE');
        
        insert phase;
          Phase.Phase_Status__c = 'OPEN';
         update phase;
          Map<Id, Phase__c> newMap = new Map<Id, Phase__c>();
        Map<Id, Phase__c> oldMap = new Map<Id, Phase__c>();
         newMap.put(phase.id, phase);
         oldMap.put(phase.id, phase);
         projTaskHelper.currentPhase(newMap,oldMap);
        system.assertNotEquals(null, phase.id) ;
        list<Task__c> lstTask = new list<Task__c >();
        for(integer i=1;i<10;i++){
            Task__c tasklocal = new Task__c(name='testTask'+i, Project_Name__c =proj.id, Phase__c = phase.Id);
            lstTask.add(tasklocal );
        }
        insert lstTask;
        system.assertNotEquals(null, lstTask.size()) ; 
        Task__c tasklocal = new Task__c(name='testTask', Project_Name__c =proj.id, Phase__c = phase.Id,category__c='REQUIRED',status__c ='OPEN');
        insert tasklocal ;
        system.assertNotEquals(null, tasklocal.id) ; 
        lstTask[0].status__c = 'ON_HOLD';
        lstTask[1].status__c = 'OPEN';
        lstTask[2].status__c = 'COMPLETE';
        lstTask[3].status__c = 'INACTIVE';
        lstTask[4].category__c= 'OPTIONAL';
        update lstTask;
        tasklocal.status__c = 'COMPLETE';
        update tasklocal ;
        tasklocal.status__c = 'INACTIVE';
        update tasklocal ;
        tasklocal.category__c= 'OPTIONAL';
        update tasklocal ;
        Task__c tasklocal1 = new Task__c(name='Start Installation', Project_Name__c =proj.id, Phase__c = phase.Id,category__c='REQUIRED',status__c ='OPEN');
        insert tasklocal1 ;
          Task__c tasklocal2 = new Task__c(name='Finish Site Audit', Project_Name__c =proj.id, Phase__c = phase.Id,category__c='REQUIRED',status__c ='OPEN');
        insert tasklocal2;
            Task__c tasklocal3 = new Task__c(name=' Submit Post Site-Audit Change Order and Request NTP', Project_Name__c =proj.id, Phase__c = phase.Id,category__c='REQUIRED',status__c ='COMPLETE');
        insert tasklocal3;
       Set<id> setIds=  projTaskHelper.getAllowUsersToModify();
            
       Test.StopTest();
    
     }
    
}