SFDCProject/src/objects/Phase_Template__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phase_Number__c</fullName>
        <label>Phase Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Template</label>
        <referenceTo>Project_Template__c</referenceTo>
        <relationshipLabel>Phase Templates</relationshipLabel>
        <relationshipName>Phase_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Phase Template</label>
    <nameField>
        <label>Phase Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phase Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Project_Template__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project Template</label>
    <nameField>
        <label>Project Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/Task_Template__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Required</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Optional</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <picklist>
            <picklistValues>
                <fullName>Branch Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branch Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brea PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drafting Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inside Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspection Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interconnection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Milestone Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NTP Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting/Brea PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting/Contract Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting/Design Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planner/Brea PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planner/Contract Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Payment Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phase_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Phase Template</label>
        <referenceTo>Phase_Template__c</referenceTo>
        <relationshipLabel>Task Templates</relationshipLabel>
        <relationshipName>Task_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Template2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Template2</label>
        <referenceTo>Project_Template__c</referenceTo>
        <relationshipLabel>Task Templates</relationshipLabel>
        <relationshipName>Task_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Template__c</fullName>
        <formula>Phase_Template__r.Project_Template__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Template</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_In_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>SLA (In Hours)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adhoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rework</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/testWfObjectFieldController.cls
@ isTest (seeAllData = true)
public class testWfObjectFieldController {
     public static testmethod void wfObjectFieldController_Test(){
      project_template__c prjTemplate = new project_template__c ( name = 'test project Template', Type__c= 'Direct' , Start_Date__c= Date.Today(), End_Date__c =Date.Today().addDays(18)); 
            insert prjTemplate;
            
            Phase_Template__c phaseTemplate = new phase_Template__c( name = 'Project Initiation' , Project_Template__c = prjTemplate.id, Phase_Number__c = '1.0', Start_Date__c= Date.Today(), End_Date__c =Date.Today().addDays(18) );
            insert phaseTemplate;
            
            Task_Template__c taskTemplate = new Task_Template__c( name = 'Verification Call' , Project_Template2__c = prjTemplate.id, Phase_Template__c = phaseTemplate.id, Group_Name__c = 'Barnch Manager',
                                                     Category__c= 'Required', Type__c = 'Standdard', SLA_In_Hours__c = 40 ,Start_Date__c= Date.Today(), End_Date__c =Date.Today().addDays(18) );
            insert taskTemplate;
 
            ApexPages.StandardController con = new ApexPages.standardController(taskTemplate);
            ApexPages.currentPage().getParameters().put('id',taskTemplate.id);
            wfObjectFieldController  obj1 = new wfObjectFieldController(con);
			Task_Template__c taskTemplate2 = new  Task_Template__c ();
         	taskTemplate2 = obj1.tskObj;
         	system.assertEquals(taskTemplate.id, taskTemplate2.id);
         	
     }
}