SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EDP_Phase__c</fullName>
        <label>EDP_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>EDP Phase-0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDP Phase-1</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Home_Type__c</fullName>
        <label>Home Type</label>
        <picklist>
            <picklistValues>
                <fullName>Detached single family home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vertically-split duplex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Townhome / rowhome</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Install_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <description>Preferred Language</description>
        <formula>TEXT( Opportunity__r.Preferred_Language__c )</formula>
        <label>Preferred Language</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchased_Thru__c</fullName>
        <formula>TEXT(Opportunity__r.Purchased_Thru__c)</formula>
        <label>Purchased Thru</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals (Sales Partner)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sunrun_Credit_Status__c</fullName>
        <label>Sunrun Credit Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Indicates which territory homeowner is located in.</description>
        <label>Territory</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/Territory__c.object
<CustomObject>
    <description>Captures territory information</description>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_ContractDBService.cls
@istest
public class Test_ContractDBService {
    static testmethod void testContractDBService(){
        HttpResponse responseObj = new HttpResponse();
        Test.startTest();
        account oAccount = new Account();
        oAccount.Name = 'SCETriggerClassTest';
        oAccount.BillingStreet = '123 Unit Test Street';
        oAccount.BillingCity ='Union City';
        oAccount.BillingState = 'CA';
        oAccount.BillingPostalCode = '94587';
        oAccount.BillingCountry='US';
        
        insert oAccount; 
        System.debug('Accounts created');
        
        
        Contact testContact = new Contact(LastName='SCETriggerClassCust',AccountId=oAccount.id, Email='SCETriggerClass.Customer1@yopmail.com'); 
        
        insert testContact; 
        testcontact.Preferred_Language__c = 'Spanish';
        update testcontact; 
        
        
        Opportunity  opty = new Opportunity(Name='SCETriggerClassTest',StageName = 'Created',CloseDate = Date.Today()+30,
                                            Average_Monthly_Electric_Bill__c = 1000,Square_footage__c = 1500,channel_2__c = 'Billboard',
                                            Lead_Source_2__c = 'Billboard: Brilliant',Opportunity_Source_Type__c = 'BB',Utility_Company__c = 'PG&E', 
                                            Usage_Option__c = 'Basic',territory__c = 'Z', home_type__c = 'Detached single family home',  
                                            Sales_Partner__c = oAccount.Id, 
                                            Install_Partner__c = oAccount.Id, Sales_Rep_Division__c ='TestDiv',Sales_Rep_Email__c = 'SCETriggerClass.SalesRep@yopmail.com',Purchased_Thru__c = 'Costco');
        insert opty;
        System.debug('Oppty created');
        opty.Preferred_Language__c = 'English';
        update opty;
        
        Proposal__c prop = new Proposal__c();
        prop.Name='SCETriggerClassProposalTest';
        prop.Opportunity__c = Opty.Id;
        prop.Stage__c = 'Created';  
        prop.Sales_Rep_Email__c = 'SCETriggerClass.SalesRep@yopmail.com';
        prop.Date_Issued__c = Date.Today().addDays(18); 
        prop.Mode_Name__c = '1234';
        prop.System_Size_STC_DC__c  = 5.8;
        prop.Upfront_Payment__c = 20.0;
        prop.Sunrun_Credit_Status__c = 'SR Credit Approved';
        prop.EDP_Phase__c = 'EDP Phase-0';
        insert prop;
        System.debug('Proposal created');
        string agreementnumber ='1000';
        ServiceContract sc=new ServiceContract(name='98903232',contactid=testContact.id,accountid=oAccount.id,Opportunity__c = opty.id, Proposal__c = prop.id,Agreement_Number__c= agreementnumber);  
        insert sc;
        set<string> agreementId = new set<string>();
        agreementId.add(agreementnumber);
        //Invoke WebService
        ContractDBService.processContractDB(agreementId);
        
        Test.stopTest();
    }
}