SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Assigne__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cash Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Approval from partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Pass &amp; signed up for ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approval Revoked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Home - Guarantee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Credit Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prepaid: Full Payment received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Signoff_Date__c</fullName>
        <label>Customer Signoff</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EDP_Phase__c</fullName>
        <label>EDP_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>EDP Phase-0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDP Phase-1</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Rebate_Amount__c</fullName>
        <label>Estimated Rebate Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner_Guaranteed_Rebate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Guaranteed Rebate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pending_Notes__c</fullName>
        <label>Pending Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pending_Proposal_Reason__c</fullName>
        <label>Pending Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Additional utility bills required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot cross out or write on contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot verify sig. need printed name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cert. of Exempt Capital Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Checklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPASS: need to sign up for ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPASS Prepaid: need Full Payment or CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer not on utility account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired credit check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed cr, need cr for other homeowner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home in Irrevocable Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inaccurate Sizing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inaccurate square footage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete Conditional Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Proposal ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect rate Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interconnection Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid Deal Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Homeowner signature or initials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing large system approval form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing pages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing sales rep signature or ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing sig. of homeowner who pass cr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Square Footage Proof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing utility bill</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>SR_Finance_Action__c</fullName>
        <label>SR Finance Action</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SR_Ops_Actions__c</fullName>
        <label>SR Ops Actions</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sunrun_Credit_Status__c</fullName>
        <label>Sunrun Credit Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_Proposal_before_insert_Trigger.cls
@isTest
private class Test_Proposal_before_insert_Trigger {

    static testMethod void myUnitTest() {
    Opportunity Opp = new Opportunity();
          Opp.Name = 'TestOpp';
          Opp.CloseDate = date.today();
          Opp.StageName = 'Closed Won';
          insert Opp;
    Opportunity Opp2 = new Opportunity();
          Opp2.Name = 'TestOpp';
          Opp2.CloseDate = date.today();
          Opp2.StageName = 'Closed Won';
          Opp2.Credit_Status__c = 'Expired';
          insert Opp2;      
       List<Proposal__c> listProp = new List<Proposal__c>();
        Proposal__c prop = new Proposal__c();
        prop.Opportunity__c = Opp.Id;
      //  prop.Assigne__c = u1.Id;        
        prop.Stage__c = 'Created';  
        prop.Sales_Rep_Email__c = 'therepsemail@repemailfake.com';
        prop.Date_Issued__c = Date.Today().addDays(18); 
        prop.Mode_Name__c = '1234';
        prop.System_Size_STC_DC__c  = 5.8;
        prop.Upfront_Payment__c = 20.0;
        prop.Sunrun_Credit_Status__c = 'SR Credit Approved';
        prop.EDP_Phase__c = 'EDP Phase-0';
        listProp.add(prop);
        //
        Proposal__c prop2 = new Proposal__c();
        prop2.Opportunity__c = Opp.Id;
       // prop2.Assigne__c = u1.Id;        
        prop2.Stage__c = 'Created';
        prop2.Sales_Rep_Email__c = 'therepsemail@repemailfake.com'; 
        prop2.Date_Issued__c = Date.Today().addDays(18); 
        prop2.Mode_Name__c = '1234';
        prop2.System_Size_STC_DC__c  = 5.8;
        prop2.Upfront_Payment__c = 20.0;
        prop2.Sunrun_Credit_Status__c = 'SR Credit Approved';
        prop2.EDP_Phase__c = 'EDP Phase-0';
        listProp.add(prop2);
        insert listProp;
        //
        prop.Estimated_Rebate_Amount__c = 999;
        prop.Partner_Guaranteed_Rebate__c = true;         
      //  prop.Assigne__c = u2.Id;
        prop.Stage__c = EDPUtil.SR_OPS_APPROVED;
        prop.Customer_SignOff_Date__c = datetime.now();
        update prop;
        //
        
        prop2.Estimated_Rebate_Amount__c = 999;
        prop2.Partner_Guaranteed_Rebate__c = true;         
       // prop2.Assigne__c = u2.Id;
        prop2.SR_Ops_Actions__c = EDPUtil.WITH_DRAWN;
        prop2.SR_Finance_Action__c = 'Pending';
       prop2.Pending_Proposal_Reason__c = 'Additional utility bills required';
      //  prop2.Stage__c = EDPUtil.EXPIRED;
        update prop2;
        Proposal__c prop3 = new Proposal__c();
        prop3.Opportunity__c = Opp2.Id;
      //  prop.Assigne__c = u1.Id;        
        prop3.Stage__c = 'Created';  
        prop3.Sales_Rep_Email__c = 'therepsemail@repemailfake.com';
        prop3.Date_Issued__c = Date.Today().addDays(18); 
        prop3.Mode_Name__c = '1234';
        prop3.System_Size_STC_DC__c  = 5.8;
        prop3.Upfront_Payment__c = 20.0;
        prop3.Sunrun_Credit_Status__c = 'SR Credit Approved';
        prop3.EDP_Phase__c = 'EDP Phase-0';
        insert prop3;
        
        Proposal__c prop4 = new Proposal__c();
        prop4.Opportunity__c = Opp.Id;
      //  prop.Assigne__c = u1.Id;        
        prop4.Stage__c = 'Created';  
        prop4.Sales_Rep_Email__c = 'therepsemail@repemailfake.com';
        prop4.Date_Issued__c = Date.Today().addDays(18); 
        prop4.Mode_Name__c = '1234';
        prop4.System_Size_STC_DC__c  = 5.8;
        prop4.Upfront_Payment__c = 20.0;
        prop4.Sunrun_Credit_Status__c = 'SR Credit Approved';
        prop4.EDP_Phase__c = 'EDP Phase-0';
       // prop4.Customer_Signoff_Date__c = Null;
        insert prop4;
      prop4.Estimated_Rebate_Amount__c = 999;
        prop4.Partner_Guaranteed_Rebate__c = true;         
      //  prop4.Assigne__c = u2.Id;
		prop4.Stage__c = EDPUtil.SR_OPS_APPROVED;
        prop4.Customer_SignOff_Date__c = datetime.now();
        update prop4;  
         prop4.Estimated_Rebate_Amount__c = 999;
        prop4.Partner_Guaranteed_Rebate__c = true;         
      //  prop.Assigne__c = u2.Id;
        prop4.Stage__c = EDPUtil.SR_OPS_APPROVED;
                prop4.Pending_Proposal_Reason__c = 'Additional utility bills required';
        prop4.Pending_notes__c = 'XYZ';
        update prop4;
        //
    }
              
    
}