SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <description>The type of agreement proposed to the customer for Power Plan.</description>
        <label>Agreement Type</label>
        <picklist>
            <picklistValues>
                <fullName>PPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Owned - Full Upfront</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Owned - Bank Financed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Finance_Type__c</fullName>
        <label>Finance Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bank Financed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/ProposalModifyApiTest.cls
@IsTest(seealldata=true)
public class ProposalModifyApiTest {
    
    private static void proposalAction(string action, string proposalName,boolean IsTest){
        Test.startTest();
        RestContext.request  = new RestRequest();
        RestContext.response  = new RestResponse();
        RestContext.request.requestURI='/services/apexrest/v2/modifyProposal?debug=true';
        string str ='{ "action":';
        str+='"' + action+'",';
        str+= '"proposalName":';
        str+= '"'+ proposalName + '"' ;
        str+='}';
          if(IsTest){
              RestContext.request.requestBody=Blob.valueOf('{"testMode": "1"}');   
        }
        else{
            RestContext.request.requestBody = Blob.valueOf(str);
        }
        ProposalApiModifyEndpoint.httpPatch();
        Test.stopTest();
    }
    
    testmethod public static void testProposalActions(){
        Proposal__c proposal =[select name ,id from Proposal__c where stage__c='created' limit 1 ];
        proposalAction('submit',proposal.Name,false);
        
    }
    
    testmethod public static void testVoidProposal(){
        Proposal__c proposal =[select name ,id from Proposal__c where stage__c='created' limit 1 ];
        proposalAction('void',proposal.Name,false);
    }
    
    testmethod public static void testWarnProposal(){
        Proposal__c proposal =[select name ,id from Proposal__c where stage__c='created' and Agreement_Type__c ='Customer Owned - Full Upfront' and Finance_Type__c != 'N/A' and Finance_Type__c != 'Bank Financed' limit 1 ];
        proposalAction('submit',proposal.Name,false);
    }
    testmethod public static void testSRApprovedProposal(){
        Proposal__c proposal =[select name ,id from Proposal__c where stage__c='SR Ops Received'  limit 1 ];
        proposalAction('submit',proposal.Name,false);
    }
    
    testmethod public static void testVoidedProposal(){
        Proposal__c proposal =[select name ,id from Proposal__c where stage__c='Voided'  limit 1 ];
        proposalAction('void',proposal.Name,false);
    }
    
    testmethod public static void testInactiveProposal(){
        Proposal__c proposal =[select name ,id from Proposal__c where stage__c='Inactive'  limit 1 ];
        proposalAction('void',proposal.Name,false);
    }
    
    testmethod public static void testActionParam(){
        Proposal__c proposal =[select name ,id from Proposal__c where stage__c='Inactive'  limit 1 ];
        proposalAction('test',proposal.Name,false);
    }
    
    testmethod public static void testSubmitInvalid(){
        Proposal__c proposal =[select name ,id from Proposal__c where stage__c='Inactive'  limit 1 ];
        proposalAction('submit',proposal.Name,false);
    }
     testmethod public static void testApi(){
        
        proposalAction('','',true);
    }
}