SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Install_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals (Sales Partner)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_BatchClassShareOppty.cls
@isTest(SeeAllData=true)
public with sharing class Test_BatchClassShareOppty {
    public static testmethod void Test_BatchClassShareOppty(){
        Test.StartTest();   
        List<Proposal__c> proList=[select id,opportunity__c,Sales_Partner__c,Install_Partner__c from Proposal__c where sales_partner__c!=null limit 10];
        Map<id,id> UserAccountMap=new Map<id,id>();
        if(!proList.isempty())
        UserAccountMap.put(proList[0].Sales_Partner__c,userinfo.getuserid());  
        String query='select id,opportunity__c,Sales_Partner__c,Install_Partner__c from Proposal__c where sales_partner__c!=null limit 10';     
         BatchApexHistoricalOppty  batch=new BatchApexHistoricalOppty(query); 
         batch.UserAccountMap= UserAccountMap;                 
            ID batchprocessid =database.executeBatch(batch,10);
         Test.stopTest();       
    }   
}