SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EDP_Phase__c</fullName>
        <label>EDP_Phase</label>
        <picklist>
            <picklistValues>
                <fullName>EDP Phase-0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDP Phase-1</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_OpportunitySalesRep.cls
@isTest(SeeAllData=true)
public  class Test_OpportunitySalesRep {
static testMethod void OpportunitySalesRep() {  
     Test.starttest();
        
        //Profile p = [SELECT Id FROM Profile limit 1];
        //User u = new user ( FirstName = 'Smith',LastName  = 'James',Email='test@gmail.com',Username= 'sfdctest1111@yopmail.com',Alias = 'Jim',TimeZoneSidKey= 'America/Denver',
        //LocaleSidKey = 'en_US',EmailEncodingKey  = 'UTF-8',LanguageLocaleKey = 'en_US',ProfileId =p.Id);
        //insert u;
        //Proposal__c prop = [Select Name,Sales_Rep_Email__c, Date_Issued__c, Opportunity__c, System_Size_STC_DC__c, Upfront_Payment__c FROM Proposal__c limit 1];      
        
        Opportunity opp = new Opportunity(Name='TestOpportunity',StageName='Prospecting',salesrep__c=userinfo.getuserid());
        insert opp;  
        Proposal__c propObj=new Proposal__c(opportunity__c=opp.id,name='TESTPROPSalesrepupdate',Upfront_Payment__c = 1000,Mode_Name__c ='TEST',Date_Issued__c =  date.today(),Sales_Rep_Email__c ='test4343@yopmail.com',EDP_Phase__c = 'EDP Phase-1',System_Size_STC_DC__c=100);
        insert propObj;      
        set<id> ids = new set<id>();
        ids.add(opp.id);       
        OpportunitySalesRep.OpportunitySalesRep(ids);
        OpportunitySalesRepUpdate.OpportunitySalesRepUpdate(ids);
        test.stopTest();
       
    }
    
}