SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Guaranteed_production_to_date__c</fullName>
        <label>Guaranteed production to date</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Yearly_refund_rate__c</fullName>
        <label>Yearly refund rate</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_PartnerDashboardController.cls
@isTest (SeeAllData=false)
public with sharing class Test_PartnerDashboardController {

    public static testmethod void TestPartnerDashboardController(){
        Test.StartTest();
        Opportunity opportunity=new Opportunity(name='TEst',stagename='Approved',closedate=system.today());
        Opportunity opportunity2=new Opportunity(name='Test2',stagename='Closed Won',closedate=system.today());  
        List<Opportunity> oppList=new List<Opportunity>();
        oppList.add(opportunity);
        oppList.add(opportunity2);
        insert oppList;
        Proposal__c proposal=new Proposal__c(Upfront_Payment__c=1,date_issued__c=system.now(),sales_rep_email__c='test22@yopmail.com',stage__c='SR Approved',
        System_Size_STC_DC__c=1,opportunity__c=opportunity.id,Mode_Name__c='Test',Guaranteed_production_to_date__c='111',Yearly_refund_rate__c='111');
        insert proposal;     
        String startdate=system.today()-10+'';    
        String enddate=system.today()+10+'';  
        ApexPages.currentPage().getParameters().put('startDate',startdate.trim());
        ApexPages.currentPage().getParameters().put('endDate',enddate.trim());
        PartnerDashboardController PartnerDashboardControllerobj = new PartnerDashboardController();              
        PartnerDashboardControllerobj.getDashboardTypes();
        PartnerDashboardControllerobj.getOpportunitiesByStageByMonthJSON();
        PartnerDashboardControllerobj.getOpportunitiesByStageJSON();
       // PartnerDashboardControllerobj.getOpportunitiesClosedByMonthJSON();
        PartnerDashboardControllerobj.getProposalsByStageByMonthJSON();
        PartnerDashboardControllerobj.getProposalsByStageJSON();
        PartnerDashboardControllerobj.dashboardName='Proposals';
        PartnerDashboardControllerobj.proposalDashboard=true;
        PartnerDashboardControllerobj.optyDashboard=false;
        PartnerDashboardControllerobj.refreshdashboards();
        PartnerDashboardControllerobj.dashboardName='Opportunities';
        PartnerDashboardControllerobj.proposalDashboard=false;
        PartnerDashboardControllerobj.optyDashboard=true;
        PartnerDashboardControllerobj.refreshdashboards();
       Test.StopTest();

    }

}