SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date_Submitted__c</fullName>
        <label>Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Time_Submitted__c</fullName>
        <label>Date/Time Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Expiration_eMail_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Expiration eMail Count</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Install_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Install Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposal_Source__c</fullName>
        <label>Proposal Source</label>
        <picklist>
            <picklistValues>
                <fullName>PT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals (Sales Partner)</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/UnitTest_expireProposalBatch.cls
@isTest
private class UnitTest_expireProposalBatch {
    
	 @testSetup static void dataSetup() {
   
         Account a = new Account(name='Test Acct1');
         insert a;
         
         Opportunity oppty = new Opportunity();
         oppty.AccountId = a.Id;
         oppty.Name = 'NewCC Test';
         oppty.StageName = 'Qualified';
         oppty.CloseDate = Date.Today().addDays(18);
         insert oppty;
         //login
         //Proposal__c proposal = UnitTest_ServiceContractUtil.createProposal(oppty.Id);
         //
         Proposal__c proposalObj = new Proposal__c();
         proposalObj.name = 'PKRN9CF53433I-A';
         proposalObj.stage__c = 'Submitted';
         proposalObj.Opportunity__c = oppty.Id;
         
         Id SunrunIncId = System.Label.Sunrun_Inc_Id;
         proposalObj.sales_partner__c = SunrunIncId;
         proposalObj.install_partner__c = SunrunIncId;
         proposalObj.Proposal_Source__c = 'BB';
         proposalObj.Date_Time_Submitted__c = system.now()-51;
         proposalObj.Sales_Rep_Email__c = 'test@yopmail.com';
         proposalObj.Signed__c = false;
         proposalObj.Date_Issued__c = Date.Today().addDays(18);
         proposalObj.Mode_Name__c = 'Mode323';
         proposalObj.System_Size_STC_DC__c = 1290;
         proposalObj.Upfront_Payment__c = 1290;
         proposalObj.Date_Submitted__c =system.now().date() - 52;
         insert proposalObj;       
   		system.assertNotEquals(null, proposalObj);  
  } 
    
    static testMethod void myUnitTest1() {
        
       expireProposalsBatch p1 = new expireProposalsBatch();
       Database.executeBatch(p1);
    } 
    
    static testMethod void myUnitTest2() {
        list<proposal__c> proplistUpdate = [SELECT Id,Signed__c,Stage__c,CreatedDate,Date_Submitted__c,Sales_Rep_Email__c FROM Proposal__c];
        if(proplistUpdate != null && proplistUpdate.size()>0){
            proplistUpdate[0].Date_Submitted__c =system.now().date() - 59;  
            proplistUpdate[0].Signed__c = true;
            proplistUpdate[0].Expiration_eMail_Count__c = 1;
            proplistUpdate[0].Stage__c = EDPUtil.SUBMITTED;
            System.debug('proplistUpdateSize:' +proplistUpdate.size() );
        }
        update proplistUpdate;
        if(proplistUpdate != null && proplistUpdate.size()>0)
            System.debug('Date_Submitted__c' +proplistUpdate[0].Date_Submitted__c + 'Signed?' + proplistUpdate[0].Signed__c + 
                         'emailCount' + proplistUpdate[0].Expiration_eMail_Count__c + 'Proposal Stage' +  proplistUpdate[0].stage__c);
        expireProposalsBatch p2 = new expireProposalsBatch();
        Database.executeBatch(p2);
    }
    
    static testMethod void myUnitTest3() {
        list<proposal__c> proplistUpdate = [SELECT Id,Signed__c,Stage__c,CreatedDate,Date_Submitted__c,Sales_Rep_Email__c FROM Proposal__c];
        if(proplistUpdate != null && proplistUpdate.size()>0){
            proplistUpdate[0].Date_Submitted__c =system.now().date() - 100;  
            proplistUpdate[0].Signed__c = true;
            proplistUpdate[0].Expiration_eMail_Count__c = 2;
             proplistUpdate[0].Stage__c = EDPUtil.SUBMITTED;
            System.debug('proplistUpdate2size:' +proplistUpdate.size() );
        }
        update proplistUpdate;
        if(proplistUpdate != null && proplistUpdate.size()>0)
        System.debug('Date_Submitted__c' +proplistUpdate[0].Date_Submitted__c + 'Signed?' + proplistUpdate[0].Signed__c + 
                     'emailCount' + proplistUpdate[0].Expiration_eMail_Count__c + 'Proposal Stage' +  proplistUpdate[0].stage__c);
        expireProposalsBatch p2 = new expireProposalsBatch();
        Database.executeBatch(p2);
    } 
    
    
  
}