SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Assigne__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_Order_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the change order that was created from this proposal</description>
        <inlineHelpText>This is the change order that was created from this proposal</inlineHelpText>
        <label>Parent Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_Order_Type__c</fullName>
        <label>Change Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>FINAL INPUTS HYBRID ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RE-SIGNED CONTRACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REVISED EPC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Change_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate whether or not a change order was created for this customer.</description>
        <label>Change Order?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credit_Status__c</fullName>
        <label>Credit Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cash Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Approval from partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional Pass &amp; signed up for ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approval Revoked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Home - Guarantee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Credit Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prepaid: Full Payment received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EPC_Price__c</fullName>
        <description>The turnkey price to be paid to the installer.</description>
        <inlineHelpText>The turnkey price to be paid to the installer.</inlineHelpText>
        <label>EPC Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Electronically_Signed_Document__c</fullName>
        <defaultValue>false</defaultValue>
        <label>eSigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estimated_Rebate_Amount__c</fullName>
        <label>Estimated Rebate Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Original_Proposal_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the proposal ID that the change order was created from</description>
        <label>Original Proposal ID</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Guaranteed_Rebate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Partner Guaranteed Rebate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pending_Proposal_Reason__c</fullName>
        <label>Pending Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Additional utility bills required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot cross out or write on contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot verify sig. need printed name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cert. of Exempt Capital Improvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Checklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPASS: need to sign up for ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPASS Prepaid: need Full Payment or CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer not on utility account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired credit check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed cr, need cr for other homeowner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home in Irrevocable Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inaccurate Sizing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inaccurate square footage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete Conditional Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Proposal ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect rate Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interconnection Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid Deal Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Homeowner signature or initials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing large system approval form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing pages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing sales rep signature or ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing sig. of homeowner who pass cr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Square Footage Proof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing utility bill</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Product_ID__c</fullName>
        <label>Product ID</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/testProposalTriggers.cls
/**
Peter Alexander Mandy
10232012 121228
 */
@isTest
private class testProposalTriggers {

    static testMethod void myUnitTest() {
       Account accountRec = new Account();
        accountRec.Name = 'Test Account Oppties';
        insert accountRec;
        //
        Contact contactRec = new Contact();
        contactRec.FirstName = 'TestAcct';
        contactRec.LastName = 'TestAcctOppty';
        contactRec.Email = 'emailfake@fakeemail.net';
        contactRec.AccountId = accountRec.Id;
        insert contactRec;
        //
        ID ProfileID = [ Select id from Profile where UserType = 'Standard' LIMIT 1].id;
        //
        List<User> listUsers = new List<User>();
        User u1 = new User( email='test-user11@fakeemail.com', profileid = ProfileID, 
                UserName='test-user1@fakeemail.com', alias='tusr11', CommunityNickName='tusr11', 
		        TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', 
		        LanguageLocaleKey='en_US', FirstName = 'Test', LastName = 'User',Title = 'Key User' );
        listUsers.add(u1);
        User u2 = new User( email='test-user22@fakeemail.com', profileid = ProfileID, 
                UserName='test-user22@fakeemail.com', alias='tusr22', CommunityNickName='tusr22', 
		        TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', 
		        LanguageLocaleKey='en_US', FirstName = 'Test2', LastName = 'User2',Title = 'Key User2' );
        listUsers.add(u2);
        insert listUsers;
        //
        Opportunity Opp = new Opportunity();
        /*Opp.Name = 'TestOpptyTriggers';
        Opp.StageName = 'In Progress';
        Opp.CloseDate = Date.Today().addDays(18);    
        Opp.AccountId = accountRec.Id;
        Opp.Sales_Representative__c = contactRec.Id;    
        Opp.Credit_Status__c = 'Approved'; 
        insert Opp;
        //temp fix for odd error on above insert on 11072012 while deploying LD changes
        Opp = [select id from Opportunity LIMIT 1];  
        
        //
        List<Proposal__c> listProp = new List<Proposal__c>();
        Proposal__c prop = new Proposal__c();
        prop.Opportunity__c = Opp.Id;
        prop.Assigne__c = u1.Id;        
        prop.Stage__c = 'Created';  
        prop.Sales_Rep_Email__c = 'therepsemail@repemailfake.com';
        prop.Date_Issued__c = Date.Today().addDays(18); 
        prop.Mode_Name__c = '1234';
        prop.System_Size_STC_DC__c  = 5.8;
        prop.Upfront_Payment__c = 20.0;
        listProp.add(prop);
        //
        Proposal__c prop2 = new Proposal__c();
        prop2.Opportunity__c = Opp.Id;
        prop2.Assigne__c = u1.Id;        
        prop2.Stage__c = 'Created';
        prop2.Sales_Rep_Email__c = 'therepsemail@repemailfake.com'; 
        prop2.Date_Issued__c = Date.Today().addDays(18); 
        prop2.Mode_Name__c = '1234';
        prop2.System_Size_STC_DC__c  = 5.8;
        prop2.Upfront_Payment__c = 20.0;
        listProp.add(prop2);
        //
        insert listProp;
        //
        Proposal__c prop3 = new Proposal__c();
        prop3.Opportunity__c = Opp.Id;
        prop3.Assigne__c = u1.Id;        
        prop3.Stage__c = 'Created';
        prop3.Sales_Rep_Email__c = 'therepsemail@repemailfake.com'; 
        prop3.Date_Issued__c = Date.Today().addDays(18); 
        prop3.Mode_Name__c = '1234';
        prop3.System_Size_STC_DC__c  = 5.8;
        prop3.Upfront_Payment__c = 20.0;
        prop3.Change_Order__c = true;
        prop3.Change_Order_ID__c = prop2.Id;        
        insert prop3;
        //
        prop.Estimated_Rebate_Amount__c = 999;
        prop.Partner_Guaranteed_Rebate__c = true;         
        prop.Assigne__c = u2.Id;
        prop.Stage__c = EDPUtil.SR_OPS_APPROVED;
        update prop;
        //
        try{
          prop.Stage__c = EDPUtil.SR_OPS_REVIEWED;
          prop.Estimated_Rebate_Amount__c = null;
          prop.Partner_Guaranteed_Rebate__c = false;
          update prop;
        }
        catch(Exception e)
        {
        	System.Debug('Trap the error that is intentionally thrown to the page.');
        }
        //
        prop.Stage__c = EDPUtil.SR_OPS_REVIEWED;
        update prop;
        prop.Stage__c = EDPUtil.CREDIT_APPROVED;
        prop.EPC_Price__c = 105000;
        update prop;
        //To hit lines 222-225 update again with no change to stage but equal to Approved:
        update prop;
        try{
        prop.Stage__c = EDPUtil.SUBMITTED;
        prop.Change_Order__c = true;
        prop.Change_Order_Type__c = EDPUtil.FINAL_INPUTS_HYBRID_ID;
        prop.Change_Order_ID__c = prop2.Id;        
        prop.Original_Proposal_ID__c = prop2.Id;
        prop.Electronically_Signed_Document__c = false;
        update prop;
        }
        catch(Exception e)
        {
        	System.Debug('Trap the error that is intentionally thrown to the page.');
        }
        //
        try{
        prop.Electronically_Signed_Document__c = true;
        update prop;   
        }
        catch(Exception e)
        {
        	System.Debug('Trap the error that is intentionally thrown to the page.');
        }   
        //
        try{
        prop.Product_ID__c = 'F';
        prop.Change_Order__c = true;
        prop.Change_Order_Type__c = EDPUtil.FINAL_INPUTS_HYBRID_ID;
        prop.Change_Order_ID__c = prop2.Id; 
        prop.Stage__c = EDPUtil.PENDING;
        prop.Pending_Proposal_Reason__c = 'Missing pages';
        update prop;
        }
        catch(Exception e)
        {
        	System.Debug('Trap the error that is intentionally thrown to the page.');
        }
        //
        try{
        	prop.Change_Order_ID__c = null;
        	update prop;
        }
        catch(Exception e)
        {
           System.Debug('Trap the error that is intentionally thrown to the page.');
        }    
        try{
          prop.Assigne__c = null;
          update prop;	
        }
        catch(Exception e)
        {
        	System.Debug('Trap the error that is intentionally thrown to the page.');
        }    */
    }
}