SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Mode_Name__c</fullName>
        <description>The unique name of the proposal mode in which this proposal was issued. A mode is a financial model constructed by the Proposal Engine for a given set of circumstances (eg. a particular partner, geography, rebate structure, or other deal situation as determined by the sales rep or channel manager)</description>
        <label>Mode Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/CallcenterOptyPaymentControllerTest.cls
@IsTest
public class CallcenterOptyPaymentControllerTest {
    
    
        public static BaseClass utils = new BaseClass();
    
        testmethod static void testController() {
        Sf.settingsService.setString(Constants.PaymentOptyContactRole, 'Homeowner');
        Account account = BaseClassTest.createTestAccount();
        Opportunity opty = new Opportunity();
        opty.name = 'Test Opty3';
        opty.StageName = 'New';
        opty.AccountId = account.id;
        insert opty;

        
        Test.setCurrentPage(new PageReference('/apex/CallCenterOptyPayment?id=' + opty.id));
        CallCenterOptyPaymentController  controller1 = new CallCenterOptyPaymentController(null);
        System.assertEquals(true, utils.getHasErrorMessagesContains('There is no Contact associated with opportunity with required billing Contact Role (Homeowner). Please associate a Contact with specified role and try again'));
        
        
        Contact contact1 = new Contact(firstName='Test1', lastName='Doe4', email='john.doe2@yopmail.com', MailingStreet='1 Main St', MailingCity='San F', MailingState='CA', MailingCountry='US');
        contact1.AccountId = account.id;
        insert contact1;
        
        OpportunityContactRole role1 = new OpportunityContactRole(OpportunityId=opty.Id, ContactId=contact1.id, Role='Homeowner');     
        insert role1;    
        
        Test.setCurrentPage(new PageReference('/apex/CallCenterOptyPayment?id=' + opty.id));

        CallCenterOptyPaymentController controller = new CallCenterOptyPaymentController(null);
        System.assertEquals(true, utils.getHasErrorMessagesContains('Please generate a proposal before initiating a financial transaction.'));
        
        Proposal__c prop = new Proposal__c(Opportunity__c =opty.Id,System_Size_STC_DC__c=5.85,Upfront_Payment__c = 1200,Mode_Name__c='Sunrun - REC - CSI',Name ='PKRDC1439VC1-H',Sales_Rep_Email__c ='abc@gmail.com',Date_Issued__c = system.today());
        insert prop;
        
        OptyPaymentController optyc = new OptyPaymentController(); 
        Dto.optyPaymentInfo optyPaymentInfo = optyc.getOptyPaymentInfo(); 

        controller = new CallCenterOptyPaymentController(null);
        System.assertEquals(opty.id, controller.opty.id);
        System.assertEquals(true, controller.renderPanel);
}
}