SFDCProject/src/objects/Proposal__c.object
<CustomObject>
    <description>This represents a proposal to an opportunity with pricing information and other meta information related to the issuing of the proposal.</description>
    <fields>
        <fullName>Date_Issued__c</fullName>
        <description>The date the proposal was created</description>
        <label>Date Issued</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The opportunity for which this proposal was issued</description>
        <inlineHelpText>The opportunity for which this proposal was issued</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposal_Source__c</fullName>
        <label>Proposal Source</label>
        <picklist>
            <picklistValues>
                <fullName>PT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <description>The email address of the sales representative who issued this proposal</description>
        <inlineHelpText>The email address of the sales representative who issued this proposal</inlineHelpText>
        <label>Sales Rep Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Task Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replaced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Credit Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Ops Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SR Signoff Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Size_STC_DC__c</fullName>
        <description>The size of the proposed system in DC Watts</description>
        <label>System Size STC DC</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upfront_Payment__c</fullName>
        <description>The upfront payment to the customer for this proposed deal.</description>
        <inlineHelpText>Does not include Tax</inlineHelpText>
        <label>Upfront Payment</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/objects/TermsConditions__c.object
<CustomObject>
    <description>Terms and Conditions</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Status of Terms and Conditions</description>
        <inlineHelpText>Status of Terms and Conditions</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SeqNo__c</fullName>
        <description>Sequence Number to identify the multiple entries for Terms and Conditions for a specific Type.</description>
        <inlineHelpText>Sequence Number to identify the multiple entries for Terms and Conditions for a specific Type.</inlineHelpText>
        <label>SeqNo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TermsConditionsInfo__c</fullName>
        <description>Terms and Conditions</description>
        <inlineHelpText>Terms and Conditions</inlineHelpText>
        <label>TermsConditionsInfo</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>TermsConditionsType__c</fullName>
        <description>The type of Terms and Conditions</description>
        <inlineHelpText>The type of Terms and Conditions</inlineHelpText>
        <label>TermsConditionsType</label>
        <picklist>
            <picklistValues>
                <fullName>AEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTNER</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TermsConditions</label>
    <nameField>
        <label>TermsConditions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TermsConditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_PartnerTermsConditionsExt.cls
@isTest
private class Test_PartnerTermsConditionsExt {
    
    public static User partnerUser;
    public static Contact partnerContact; 
    @isTest static void constructorTest() {
        // set up the data
        setupData();

        Lead lead = new Lead(Company='PartnerTermsConditionsExtTest',LastName = 'PartnerTermsTest');
        insert lead;
        
        // Implement test code

        //System.runAs(partnerUser) {
            PageReference testPage = Page.PartnerTermsConditions;
            testPage.getParameters().put('Id',partnerContact.Id);
            testPage.getParameters().put('returnId',lead.Id);
            Test.setCurrentPage(testPage);

            ApexPages.StandardController controller = new ApexPages.StandardController(partnerContact);
            PartnerTermsConditionsExt controllerExtn = new PartnerTermsConditionsExt(controller);

            System.assert(controllerExtn.PartnerTermsConditions.size() == 0);
        //}
    }
  
    @isTest static void testLeadAcceptTermsConditionsFromPage() {
        // set up the data
        setupData();

        TermsConditions__c terms = new TermsConditions__c(TermsConditionsType__c = 'PARTNER', Active__c = True, SeqNo__c = 1.0, TermsConditionsInfo__c = 'Test');
        insert terms;

        Lead lead = new Lead(Company='PartnerTermsConditionsExtTest',LastName = 'PartnerTermsTest');
        insert lead;

        PageReference testPage = Page.PartnerTermsConditions;
        testPage.getParameters().put('Id',partnerContact.Id);
        testPage.getParameters().put('returnId',lead.Id);
        testPage.getParameters().put('returnPage','Lead');
        testPage.getParameters().put('selectedDesign','Design New Proposal');
        testPage.getParameters().put('tandCType','PARTNER');
        testPage.getParameters().put('prospectId','LTEST123');
        testPage.getParameters().put('src','P');
        Test.setCurrentPage(testPage);

        ApexPages.StandardController controller = new ApexPages.StandardController(partnerContact);
        PartnerTermsConditionsExt controllerExtn = new PartnerTermsConditionsExt(controller);

        System.assert(controllerExtn.PartnerTermsConditions.size() > 0);

        controllerExtn.declineTermsandConditions();
        System.assert(controllerExtn.displayTandCURL == false);
        
        controller = new ApexPages.StandardController(partnerContact);
        controllerExtn = new PartnerTermsConditionsExt(controller);
        controllerExtn.acceptTermsandConditions();

        partnerContact = [SELECT Id, T_C_Accepted__c, T_C_Accepted_Date__c FROM Contact WHERE Id =:partnerContact.Id];

        System.debug(LoggingLevel.INFO,'T_C_Accepted__c : '+partnerContact.T_C_Accepted__c);
        System.debug(LoggingLevel.INFO,'redirectURL : '+controllerExtn.redirectURL);
        system.assert(partnerContact.T_C_Accepted__c);
        system.assert(controllerExtn.redirectURL != null && controllerExtn.redirectURL.containsIgnoreCase('lightmile'));
    }


    @isTest static void testLeadAcceptTermsConditionsFromButton() {
        // set up the data
        setupData();

        TermsConditions__c terms = new TermsConditions__c(TermsConditionsType__c = 'PARTNER', Active__c = True, SeqNo__c = 1.0, TermsConditionsInfo__c = 'Test');
        insert terms;

        Lead lead = new Lead(Company='PartnerTermsConditionsExtTest',LastName = 'PartnerTermsTest');
        insert lead;

        PageReference testPage = Page.PartnerTermsConditions;
        testPage.getParameters().put('Id',partnerContact.Id);
        testPage.getParameters().put('returnId',lead.Id);
        testPage.getParameters().put('returnPage','Lead');
        testPage.getParameters().put('selectedDesign','Design New Proposal');
        testPage.getParameters().put('tandCType','PARTNER');
        testPage.getParameters().put('prospectId','LTEST123');
        testPage.getParameters().put('src','B');
        Test.setCurrentPage(testPage);

        ApexPages.StandardController controller = new ApexPages.StandardController(partnerContact);
        PartnerTermsConditionsExt controllerExtn = new PartnerTermsConditionsExt(controller);

        System.assert(controllerExtn.PartnerTermsConditions.size() > 0);

        controllerExtn.acceptTermsandConditions();

        partnerContact = [SELECT Id, T_C_Accepted__c, T_C_Accepted_Date__c FROM Contact WHERE Id =:partnerContact.Id];

        System.debug(LoggingLevel.INFO,'T_C_Accepted__c : '+partnerContact.T_C_Accepted__c);
        System.debug(LoggingLevel.INFO,'redirectURL : '+controllerExtn.redirectURL);
        system.assert(partnerContact.T_C_Accepted__c);
        system.assert(controllerExtn.redirectURL != null && controllerExtn.redirectURL.containsIgnoreCase('RedirectLMFromTandC'));
    }
    
    @isTest static void testLeadDeclineTermsandConditions() {
        System.debug(LoggingLevel.INFO,'Lead Decline');
        setupData();

        TermsConditions__c terms = new TermsConditions__c(TermsConditionsType__c = 'PARTNER', Active__c = True, SeqNo__c = 1.0, TermsConditionsInfo__c = 'Test');
        insert terms;

        Lead lead = new Lead(Company='PartnerTermsConditionsExtTest',LastName = 'PartnerTermsTest');
        insert lead;

        PageReference testPage = Page.PartnerTermsConditions;
        testPage.getParameters().put('Id',partnerContact.Id);
        testPage.getParameters().put('returnId',lead.Id);
        testPage.getParameters().put('returnPage','Lead');
        testPage.getParameters().put('selectedDesign','Design New Proposal');
        testPage.getParameters().put('tandCType','PARTNER');
        testPage.getParameters().put('prospectId','LTEST123');
        testPage.getParameters().put('src','P');
        Test.setCurrentPage(testPage);

        ApexPages.StandardController controller = new ApexPages.StandardController(partnerContact);
        PartnerTermsConditionsExt controllerExtn = new PartnerTermsConditionsExt(controller);

        System.assert(controllerExtn.PartnerTermsConditions.size() > 0);

        controllerExtn.declineTermsandConditions();

        partnerContact = [SELECT Id, T_C_Accepted__c, T_C_Accepted_Date__c FROM Contact WHERE Id =:partnerContact.Id];
        system.assert(!partnerContact.T_C_Accepted__c);

    }
  
    @isTest static void testOptyAcceptTermsConditionsFromPage() {
        // set up the data
        setupData();

        TermsConditions__c terms = new TermsConditions__c(TermsConditionsType__c = 'PARTNER', Active__c = True, SeqNo__c = 1.0, TermsConditionsInfo__c = 'Test');
        insert terms;

        Opportunity opty = new Opportunity(Name='PartnerTermsConditionsExtTest',StageName = 'Created',CloseDate= Date.Today()+30);
        insert opty;

        PageReference testPage = Page.PartnerTermsConditions;
        testPage.getParameters().put('Id',partnerContact.Id);
        testPage.getParameters().put('returnId',opty.Id);
        testPage.getParameters().put('returnPage','Opty');
        testPage.getParameters().put('selectedDesign','Design New Proposal');
        testPage.getParameters().put('tandCType','PARTNER');
        testPage.getParameters().put('prospectId','LTEST123');
        testPage.getParameters().put('src','P');
        Test.setCurrentPage(testPage);

        ApexPages.StandardController controller = new ApexPages.StandardController(partnerContact);
        PartnerTermsConditionsExt controllerExtn = new PartnerTermsConditionsExt(controller);

        System.assert(controllerExtn.PartnerTermsConditions.size() > 0);

        controllerExtn.acceptTermsandConditions();

        partnerContact = [SELECT Id, T_C_Accepted__c, T_C_Accepted_Date__c FROM Contact WHERE Id =:partnerContact.Id];
        
        System.debug(LoggingLevel.INFO,'T_C_Accepted__c : '+partnerContact.T_C_Accepted__c);
        System.debug(LoggingLevel.INFO,'redirectURL : '+controllerExtn.redirectURL);
        
        system.assert(partnerContact.T_C_Accepted__c);
        system.assert(controllerExtn.redirectURL != null && controllerExtn.redirectURL.containsIgnoreCase('lightmile'));
    }

  
    @isTest static void testOptyAcceptTermsConditionsFromButton() {
        // set up the data
        setupData();

        TermsConditions__c terms = new TermsConditions__c(TermsConditionsType__c = 'PARTNER', Active__c = True, SeqNo__c = 1.0, TermsConditionsInfo__c = 'Test');
        insert terms;

        Opportunity opty = new Opportunity(Name='PartnerTermsConditionsExtTest',StageName = 'Created',CloseDate= Date.Today()+30);
        insert opty;

        PageReference testPage = Page.PartnerTermsConditions;
        testPage.getParameters().put('Id',partnerContact.Id);
        testPage.getParameters().put('returnId',opty.Id);
        testPage.getParameters().put('returnPage','Opty');
        testPage.getParameters().put('selectedDesign','Design New Proposal');
        testPage.getParameters().put('tandCType','PARTNER');
        testPage.getParameters().put('prospectId','LTEST123');
        testPage.getParameters().put('src','B');
        Test.setCurrentPage(testPage);

        ApexPages.StandardController controller = new ApexPages.StandardController(partnerContact);
        PartnerTermsConditionsExt controllerExtn = new PartnerTermsConditionsExt(controller);

        System.assert(controllerExtn.PartnerTermsConditions.size() > 0);

        controllerExtn.acceptTermsandConditions();

        partnerContact = [SELECT Id, T_C_Accepted__c, T_C_Accepted_Date__c FROM Contact WHERE Id =:partnerContact.Id];
        
        System.debug(LoggingLevel.INFO,'T_C_Accepted__c : '+partnerContact.T_C_Accepted__c);
        System.debug(LoggingLevel.INFO,'redirectURL : '+controllerExtn.redirectURL);
        
        system.assert(partnerContact.T_C_Accepted__c);
        system.assert(controllerExtn.redirectURL != null && controllerExtn.redirectURL.containsIgnoreCase('RedirectLMFromTandC'));
    }
     
    @isTest static void testProposalAcceptTermsConditionsFromPage1() {
        // set up the data
        setupData();

        TermsConditions__c terms = new TermsConditions__c(TermsConditionsType__c = 'PARTNER', Active__c = True, SeqNo__c = 1.0, TermsConditionsInfo__c = 'Test');
        insert terms;

        Opportunity opty = new Opportunity(Name='PartnerTermsConditionsExtTest',StageName = 'Created',CloseDate= Date.Today()+30);
        insert opty;

        Proposal__c p = new Proposal__c(Name='PartnerTermsConditionsExtTestPropsal',Opportunity__c=opty.id,
                                        Proposal_Source__c='BB',Sales_Rep_Email__c='PartnerTermsConditionsExtTestPropsal@yopmail.com',
                                        Date_Issued__c=Date.Today(),System_Size_STC_DC__c=10,Upfront_Payment__c=500);
        insert p;
        
        PageReference testPage = Page.PartnerTermsConditions;
        testPage.getParameters().put('Id',partnerContact.Id);
        testPage.getParameters().put('returnId',p.Id);
        testPage.getParameters().put('returnPage','Proposal');
        testPage.getParameters().put('selectedDesign','Design New Proposal');
        testPage.getParameters().put('tandCType','PARTNER');
        testPage.getParameters().put('prospectId','LTEST123');
        testPage.getParameters().put('src','P');
        Test.setCurrentPage(testPage);

        ApexPages.StandardController controller = new ApexPages.StandardController(partnerContact);
        PartnerTermsConditionsExt controllerExtn = new PartnerTermsConditionsExt(controller);

        System.assert(controllerExtn.PartnerTermsConditions.size() > 0);

        controllerExtn.acceptTermsandConditions();

        partnerContact = [SELECT Id, T_C_Accepted__c, T_C_Accepted_Date__c FROM Contact WHERE Id =:partnerContact.Id];
        
        System.debug(LoggingLevel.INFO,'T_C_Accepted__c : '+partnerContact.T_C_Accepted__c);
        System.debug(LoggingLevel.INFO,'redirectURL : '+controllerExtn.redirectURL);
        
        system.assert(partnerContact.T_C_Accepted__c);
        system.assert(controllerExtn.redirectURL != null && controllerExtn.redirectURL.containsIgnoreCase('lightmile'));
    }

    @isTest static void testProposalAcceptTermsConditionsFromPage2() {
        // set up the data
        setupData();

        TermsConditions__c terms = new TermsConditions__c(TermsConditionsType__c = 'PARTNER', Active__c = True, SeqNo__c = 1.0, TermsConditionsInfo__c = 'Test');
        insert terms;

        Opportunity opty = new Opportunity(Name='PartnerTermsConditionsExtTest',StageName = 'Created',CloseDate= Date.Today()+30);
        insert opty;

        Proposal__c p = new Proposal__c(Name='PartnerTermsConditionsExtTestPropsal',Opportunity__c=opty.id,
                                        Proposal_Source__c='BB',Sales_Rep_Email__c='PartnerTermsConditionsExtTestPropsal@yopmail.com',
                                        Date_Issued__c=Date.Today(),System_Size_STC_DC__c=10,Upfront_Payment__c=500,
                                        Stage__c='Voided');
        insert p;
        
        PageReference testPage = Page.PartnerTermsConditions;
        testPage.getParameters().put('Id',partnerContact.Id);
        testPage.getParameters().put('returnId',p.Id);
        testPage.getParameters().put('returnPage','Proposal');
        testPage.getParameters().put('selectedDesign','Design New Proposal');
        testPage.getParameters().put('tandCType','PARTNER');
        testPage.getParameters().put('prospectId','LTEST123');
        testPage.getParameters().put('src','P');
        Test.setCurrentPage(testPage);

        ApexPages.StandardController controller = new ApexPages.StandardController(partnerContact);
        PartnerTermsConditionsExt controllerExtn = new PartnerTermsConditionsExt(controller);

        System.assert(controllerExtn.PartnerTermsConditions.size() > 0);

        controllerExtn.acceptTermsandConditions();

        partnerContact = [SELECT Id, T_C_Accepted__c, T_C_Accepted_Date__c FROM Contact WHERE Id =:partnerContact.Id];
        
        System.debug(LoggingLevel.INFO,'T_C_Accepted__c : '+partnerContact.T_C_Accepted__c);
        System.debug(LoggingLevel.INFO,'redirectURL : '+controllerExtn.redirectURL);
        
        system.assert(partnerContact.T_C_Accepted__c);
        system.assert(controllerExtn.redirectURL != null && controllerExtn.redirectURL.containsIgnoreCase('TandCModifyProposalError'));
    }
        
    @isTest static void testProposalAcceptTermsConditionsFromButton() {
        // set up the data
        setupData();

        TermsConditions__c terms = new TermsConditions__c(TermsConditionsType__c = 'PARTNER', Active__c = True, SeqNo__c = 1.0, TermsConditionsInfo__c = 'Test');
        insert terms;

        Opportunity opty = new Opportunity(Name='PartnerTermsConditionsExtTest',StageName = 'Created',CloseDate= Date.Today()+30);
        insert opty;

        Proposal__c p = new Proposal__c(Name='PartnerTermsConditionsExtTestPropsal',Opportunity__c=opty.id,
                                        Proposal_Source__c='BB',Sales_Rep_Email__c='PartnerTermsConditionsExtTestPropsal@yopmail.com',
                                        Date_Issued__c=Date.Today(),System_Size_STC_DC__c=10,Upfront_Payment__c=500);
        insert p;
        
        PageReference testPage = Page.PartnerTermsConditions;
        testPage.getParameters().put('Id',partnerContact.Id);
        testPage.getParameters().put('returnId',p.Id);
        testPage.getParameters().put('returnPage','Proposal');
        testPage.getParameters().put('selectedDesign','Design New Proposal');
        testPage.getParameters().put('tandCType','PARTNER');
        testPage.getParameters().put('prospectId','LTEST123');
        testPage.getParameters().put('src','B');
        Test.setCurrentPage(testPage);

        ApexPages.StandardController controller = new ApexPages.StandardController(partnerContact);
        PartnerTermsConditionsExt controllerExtn = new PartnerTermsConditionsExt(controller);

        System.assert(controllerExtn.PartnerTermsConditions.size() > 0);

        controllerExtn.acceptTermsandConditions();

        partnerContact = [SELECT Id, T_C_Accepted__c, T_C_Accepted_Date__c FROM Contact WHERE Id =:partnerContact.Id];
        
        System.debug(LoggingLevel.INFO,'T_C_Accepted__c : '+partnerContact.T_C_Accepted__c);
        System.debug(LoggingLevel.INFO,'redirectURL : '+controllerExtn.redirectURL);
        
        system.assert(partnerContact.T_C_Accepted__c);
        system.assert(controllerExtn.redirectURL != null && controllerExtn.redirectURL.containsIgnoreCase('RedirectLMFromTandC'));
    }

    static void setupData() {
        // selecting partner profile to be used for user creation
        Profile partnerProfile = [select Id,Name from Profile where Name = 'PartnerOperations' limit 1];
        System.debug(LoggingLevel.INFO,'partnerProfile : '+partnerProfile);
        // selecting record type for partner
        Id accountRecTypeId = [select Id from RecordType where Name = 'Partner' and SobjectType = 'Account' limit 1].Id;
        Id contactRecTypeId = [select Id from RecordType where Name = 'Partner' and SobjectType = 'Contact' limit 1].Id;

        Account oAccount = new Account();
        oAccount.Name = 'PartnerTermsConditionsExtTest';
        oAccount.BillingStreet = '123 Unit Test Street';
        oAccount.BillingCity ='Union City';
        oAccount.BillingState = 'CA';
        oAccount.BillingPostalCode = '94587';
        oAccount.BillingCountry='US';
        oAccount.RecordTypeId = accountRecTypeId;
        insert oAccount;

        partnerContact = new Contact (AccountId = oAccount.id,LastName = 'portalTestUser',RecordTypeId = contactRecTypeId,
                                      FirstName='Test');
        insert partnerContact;

        partnerUser = new User(alias = 'standt', email='standarduser@PartnerTermsConditionsExtTest.com',
                      emailencodingkey='UTF-8', lastname='PartnerTermsConditionsExtTest', LanguageLocaleKey='en_US',
                      localesidkey='en_US', profileid = partnerProfile.Id,timezonesidkey='America/Los_Angeles',
                      username='systemadmin@testorg.com',contactId=partnerContact.Id,Title='PartnerTermsConditionsExtTest',
                      FirstName='Test');
               
        insert partnerUser;
    }
}