SFDCProject/src/objects/Referral_Input__c.object
<CustomObject>
    <description>We are collecting the referred by and referred to in this object. In some cases, we will have the account id and contact id, and in some we will not, hence the other fields such as first name, last name etc.</description>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <formula>TEXT(Lead__r.Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Referrals_Input</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referee Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals_Input</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract_RR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract (RR)</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Referrals (Service Contract (RR))</relationshipLabel>
        <relationshipName>Referrals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals (New Customers Contacts)</relationshipLabel>
        <relationshipName>Referrals_Input</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>TEXT(Opportunity__r.StageName)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Stage</label>
        <type>Text</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{0000000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/ReferralTriggerHandlerTest.cls
@istest
public class ReferralTriggerHandlerTest
{
private static BaseClass utils = new BaseClass();
 static testMethod void myunitReferral()
 {
   Contact contactObj1 = TestPRMLibrary.insertContact('PRMTestAccount1', 
                      PRMLibrary.PARTNER, 
                      'PRMTestLastName1',
                      'prmcontact1@sunrun.com');
                      
      Opportunity optyObj1 = TestPRMLibrary.insertOpportunity('ResidentialAccount-01', 'Residential','ResOpty-01', 'Platinum'); 
      optyObj1.SalesRep__c = UserInfo.getUserId();
      optyObj1.Sales_Partner__c  = contactObj1.AccountId;
      upsert optyObj1;
  
        Account acct = new Account(Id=contactObj1.AccountId,Name='Foo', RecordTypeId=utils.getRecordTypeId('Account', 'Partner'), 
        Sqs_Queue_Name__c='Test',
        Office_Location__c  = 'Headquarters',
        Stage__c = 'Confirmed',
        Active__c  = true);
        update acct;
    
                      
                         
        Lead lead = new Lead(FirstName='Foo', LastName='Bar', Company='Foo');   
        lead.Lead_Status__c = 'Updated2';
        lead.Lead_Gen_Partner__c = contactObj1 .accountId;
        lead.Sales_Partner__c = contactObj1 .accountId;
        lead.Partner_for_Lead_Passing__c = contactObj1 .accountId;
        insert lead;
        ServiceContract objSC = new ServiceContract(ContactId =contactObj1.Id,Opportunity__c = optyObj1.Id );
        insert objSC;
  
     Referral_Input__c referral = new Referral_Input__c(Lead__c =lead.id,Service_Contract_RR__c  =objSC.Id );
    referral.Source_Contact_Id__c  = contactObj1.Id;
    insert referral;
 
 
 }

}