SFDCProject/src/objects/Referral_Input__c.object
<CustomObject>
    <description>We are collecting the referred by and referred to in this object. In some cases, we will have the account id and contact id, and in some we will not, hence the other fields such as first name, last name etc.</description>
    <fields>
        <fullName>Ambassador_Sync_Status__c</fullName>
        <inlineHelpText>Indicates the status of syncing this referral to ambassador system for referral commission updates.</inlineHelpText>
        <label>Ambassador Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Be Synced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{0000000}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/AmbassadorSyncJob.cls
public class AmbassadorSyncJob extends BaseClass implements Queueable, Database.AllowsCallouts {
	
    public List<Id> referralIds {get;set;}
    
    public AmbassadorSyncJob() {
    	this(null);
    }
    
    public AmbassadorSyncJob(List<Id> referralIds) {
        this.referralIds = referralIds;
    }

    public void execute(QueueableContext ctx) {
        if (referralIds == null) {
            Integer limitValue = Sf.settingsService.getInteger('AmbassadorSyncJobLimit', 100);
            
            referralIds = getUniqueIdList([
                select id
                from Referral_Input__c 
                where Ambassador_Sync_Status__c = :BaseClass.Status_ToBeSynced
	                	or Ambassador_Sync_Status__c = :BaseClass.Status_SyncError
	                	or Ambassador_Sync_Status__c = 'Commission Id Empty'
                limit :limitValue
            ]);
        }
        
        Sf.ambassadorSyncService.syncReferrals(referralIds);
    }
}