SFDCProject/src/objects/Service_Contract_Partner_Rel__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Service_Contract_Partner_Rels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipName>Service_Contract_Partner_Rels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Gen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solar Waterproofing Subcontractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Borrower</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Related Partner</label>
    <nameField>
        <displayFormat>SCPR{00000000}</displayFormat>
        <label>Service Contract Partner Rel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_RelatedPartner_After_Update.cls
@isTest
private class Test_RelatedPartner_After_Update {

    static testMethod void Test_RelatedPartner_After_Update() {
    Account a = New Account(Name = 'TestAccount2');
        insert a;
    ServiceContract sc = New ServiceContract(Name = 'Testsc',AccountId =a.Id,Legacy_Asset_Number__c = '12222006');
        insert sc; 
    Service_Contract_Partner_Rel__c scpr = New Service_Contract_Partner_Rel__c(Account__c=a.Id, ServiceContract__c = sc.Id, Type__c = 'Install');
      	insert	scpr;  
    Service_Contract_Partner_Rel__c scpr1 = New Service_Contract_Partner_Rel__c(Account__c=a.Id, ServiceContract__c = sc.Id, Type__c = 'Sales');
      	insert	scpr1;    	
      	  
    }
}