SFDCProject/src/objects/Service_Contract_Event__c.object
<CustomObject>
    <fields>
        <fullName>External_Sync_Status__c</fullName>
        <label>External Sync Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sync Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sync Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Be Synced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_Sync_System__c</fullName>
        <label>External Sync System</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Service Contract Event</label>
    <nameField>
        <displayFormat>SCA-{00000}</displayFormat>
        <label>Service Contract Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/CostcoLeadUpdateInstallInfoJob.cls
public with sharing class CostcoLeadUpdateInstallInfoJob extends BaseClass implements Queueable, Database.AllowsCallouts{
public List<Id> sceIds {get;set;}
    
    public CostcoLeadUpdateInstallInfoJob() {
        this(null);
    }
    
    public CostcoLeadUpdateInstallInfoJob(List<Id> sceIds) {
        this.sceIds = sceIds;
    }
    
    public void execute(QueueableContext ctx) {
        if (sceIds == null) {
            sceIds = getUniqueIdList([
                select id
                from Service_Contract_Event__c 
                where External_Sync_System__c = 'Costco' 
                and (External_Sync_Status__c = :BaseClass.Status_ToBeSynced
                    or External_Sync_Status__c = :BaseClass.Status_SyncError)
            ]);
        }
        
        Sf.costcoSyncService.updateInstallationInfo(sceIds);
    }

}