SFDCProject/src/objects/Service_Contract_Event__c.object
<CustomObject>
    <fields>
        <fullName>CAP_date_approved__c</fullName>
        <label>CAP date approved</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commencement_of_Construction__c</fullName>
        <label>Commencement of Construction</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Completion_of_Construction__c</fullName>
        <label>Completion of Construction</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Critter_guard__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Critter guard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_when_Site_Audit_was_Scheduled__c</fullName>
        <label>Date when Site Audit was Scheduled</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Inspection_Signoff__c</fullName>
        <label>Final Inspection Signoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Call_Completed_Date__c</fullName>
        <description>Holds value of the date on which the first call with client was placed</description>
        <label>First Call Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Layout_Approval_Start__c</fullName>
        <label>Layout Approval Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Layout_Rcvd__c</fullName>
        <label>Layout Rcvd</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Main_Panel_Size_Amps__c</fullName>
        <label>Main Panel Size Amps</label>
        <picklist>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>125</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>175</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>225</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>275</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>300</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>400</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (put in notes)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>On_Hold_End_Date__c</fullName>
        <label>On Hold End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>On_Hold_Start_Date__c</fullName>
        <label>On Hold Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Service_Contract__r.Opportunity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Opportunity_Close_Date__c</fullName>
        <label>Oracle Opportunity Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Oracle_Revenue_Amount__c</fullName>
        <label>Oracle Revenue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Permit_Approval_Date__c</fullName>
        <label>Permit Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Permit_Jurisdiction_municipality__c</fullName>
        <label>Permit Jurisdiction (municipality)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permit_Submitted_Date__c</fullName>
        <label>Permit Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plans_Completed_Date__c</fullName>
        <label>Plans Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plans_Reviewed_Date__c</fullName>
        <label>Plans Reviewed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Creation_Date__c</fullName>
        <formula>Service_Contract__r.Opportunity__r.Project_Creation_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Creation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Planner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Contract_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reroof_under_array__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reroof under array</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Return_to_Sales_Date__c</fullName>
        <label>Return to Sales Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scheduled_Construction_Start_Date__c</fullName>
        <label>Estimated Construction Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Service Contract Events</relationshipLabel>
        <relationshipName>Service_Contract_Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Panel_Upgrade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Panel Upgrade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Site_Audit_Complete__c</fullName>
        <label>Site Audit Complete</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site_Audit_Results_Rcvd__c</fullName>
        <label>Site Audit Results Rcvd</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site_Audit_Scheduled__c</fullName>
        <label>Site Audit Scheduled</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Submit_Final_Interconnection__c</fullName>
        <label>Submit Final Interconnection</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SunRun_NTP_Costco_PO_Issued__c</fullName>
        <label>SunRun NTP Costco PO Issued</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vaulted_Ceilings__c</fullName>
        <label>Vaulted Ceilings</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (put in notes)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Contract Event</label>
    <nameField>
        <displayFormat>SCA-{00000}</displayFormat>
        <label>Service Contract Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_trg_bef_ins_upd_oppty.cls
@isTest(SeeAllData=true)
public with sharing class Test_trg_bef_ins_upd_oppty {
    static testMethod void Test_trg_bef_ins_upd_oppty(){
    Test.StartTest();
    Profile p = [ Select id,name from Profile where Name ='Operations' LIMIT 1];
    User u = [Select id,ContactId from User where isactive=true and profileid = :p.Id limit 1];
    Account a= [select id,name from account where office_location__c='Headquarters' and Ultimate_Parent_Account__c=null limit 1];
    Contact cont= new Contact (firstname='Test',LastName='TestCt',Accountid=a.Id,Ultimate_Parent_Account__c=a.id,Email='Test_trg_bef_ins_upd_oppty.Customer1@yopmail.com');
    insert cont;  
        
    Opportunity opp = new Opportunity (Name ='Test111',StageName='Created',Sales_Representative__c=cont.id,Critter_Guard__c=true,Reroof_under_Array__c=true,Service_Panel_Upgrade__c=true,Vaulted_Ceilings__c='Yes',Main_Panel_Size_Amps__c='200',Scheduled_Construction_Start_Date__c=system.today(),
    Job_Type__c='Sales Representative',SunRun_NTP_Costco_PO_Issued__c=system.today()-2,Oracle_Revenue_Amount__c=20,Permit_Jurisdiction_municipality__c='San Jose',Layout_Approval_Start__c=system.today(),Elect_PV_Finish_Date__c=system.today(),
    Permitting_Process_Start_Date__c=system.today()-1,Permitting_Process_Finish_Date__c=system.today(),Actual_Construction_Finish__c=system.today()-4,Actual_Construction_Start__c=system.today(),Plans_Completed_Date__c=system.today(),
    Submit_Final_Interconnection__c=system.today()-2,Site_Audit_Completed__c=system.today()-3,Layout_Approval_Finish__c=system.today()-1,Oracle_Opportunity_Close_Date__c=system.today()-2,Plans_Reviewed_Date__c=system.today()-3,Project_Manager__c=u.id);
    
    Opportunity opp1 = new Opportunity (Name ='Test1',StageName='Created',On_Hold_Start_Date__c = system.today(),On_Hold_End_Date__c = system.today() + 90,Sales_Representative__c=cont.id,Critter_Guard__c=false,Reroof_under_Array__c=false,Service_Panel_Upgrade__c=false,Vaulted_Ceilings__c='No',Main_Panel_Size_Amps__c='125',Scheduled_Construction_Start_Date__c=system.today()-1,
    Job_Type__c='Sales Associate',SunRun_NTP_Costco_PO_Issued__c=system.today()-1,Oracle_Revenue_Amount__c=10,Permit_Jurisdiction_municipality__c='Sunnyvale',Layout_Approval_Start__c=system.today()-1,Elect_PV_Finish_Date__c=system.today()-3,
    Permitting_Process_Start_Date__c=system.today(),Permitting_Process_Finish_Date__c=system.today(),Actual_Construction_Finish__c=system.today(),Actual_Construction_Start__c=system.today()-2,Plans_Completed_Date__c=system.today(),
    Submit_Final_Interconnection__c=system.today(),Site_Audit_Completed__c=system.today(),Return_to_Sales_Date__c=system.today(),Layout_Approval_Finish__c=system.today(),Oracle_Opportunity_Close_Date__c=system.today()-1,Plans_Reviewed_Date__c=system.today()-1,Project_Manager__c=u.id); 
 
    List<Opportunity>opplist = new List<Opportunity>();
    opplist.add(opp);
    opplist.add(opp1);
    insert opplist;  
    
    ServiceContract sc = new ServiceContract(Name='9Test9',Opportunity__c=opp.id, contactid=cont.id);
    ServiceContract sc1 = new ServiceContract(Name='Test10',Opportunity__c=opp1.id, contactid=cont.id);
    

    List<ServiceContract> sclist = new List<ServiceContract>();
    sclist.add(sc);
    sclist.add(sc1);
    insert sclist;
    
    Service_Contract_Event__c sce = new Service_Contract_Event__c (Service_Contract__c = sc1.id,Critter_Guard__c =false,Reroof_under_Array__c=false,Service_Panel_Upgrade__c=false,Vaulted_Ceilings__c='No',Main_Panel_Size_Amps__c='125',Scheduled_Construction_Start_Date__c=system.today()-1,
    Oracle_Revenue_Amount__c=10,Permit_Jurisdiction_municipality__c='Sunnyvale',Layout_Approval_Start__c=system.today()-1,Final_Inspection_Signoff__c=system.today()-3,
    Permit_Submitted_Date__c=system.today(),Permit_Approval_Date__c=system.today(),Completion_of_Construction__c=system.today(),Commencement_of_Construction__c=system.today()-2,Plans_Completed_Date__c=system.today(),
    Submit_Final_Interconnection__c=system.today(),Site_Audit_Complete__c=system.today(),Oracle_Opportunity_Close_Date__c=system.today()-2,CAP_date_approved__c=system.today(),Layout_Rcvd__c=system.today()-1,SunRun_NTP_Costco_PO_Issued__c = system.today()-2,Return_to_Sales_Date__c=system.today()+1);
    
        insert sce;
        
        System.runAs(u){
            try{
                opp1.On_Hold_Start_Date__c = system.today() +1;
                opp1.On_Hold_End_Date__c = system.today() + 89;
                opp1.Oracle_Opportunity_Close_Date__c =system.today() +10;
                opp1.SunRun_NTP_Costco_PO_Issued__c =system.today();
                opp1.Oracle_Revenue_Amount__c =1200;
                opp1.Permit_Jurisdiction_municipality__c ='Dublin';
                opp1.Return_to_Sales_Date__c = system.today()-1;
                opp1.Plans_Reviewed_Date__c = system.today();
                opp1.Plans_Completed_Date__c =system.today() +10;
                opp1.Layout_Approval_Start__c =system.today() -10;
                opp1.Layout_Approval_Finish__c =system.today()+1;
                opp1.Project_Creation_Date__c =system.today();
                opp1.Submit_Final_Interconnection__c = system.today()-1;
                opp1.Actual_Construction_Start__c= system.today()-1;
                opp1.Actual_Construction_Finish__c = system.today()+2;
                opp1.Permitting_Process_Start_Date__c = system.today()-1;
                opp1.Permitting_Process_Finish_Date__c =system.today()+20;
                opp1.Elect_PV_Finish_Date__c = system.today()+30;
                opp1.Job_Type__c = 'Sales Representative';
                opp1.Site_Audit_Completed__c = system.today()+5;
                opp1.Site_Audit_Scheduled__c= system.now()+30;
                opp1.Site_Audit_Results_Rcvd__c =system.today()+3;
                opp1.Date_when_Site_Audit_was_Scheduled__c = system.today() -10;
                opp1.First_Call_Completed_Date__c = system.today()+3;
                opp1.Scheduled_Construction_Start_Date__c = system.today()+8;
                opp1.Critter_Guard__c = true;
                opp1.Reroof_under_Array__c = true;
                opp1.Service_Panel_Upgrade__c = true;
                opp1.Vaulted_Ceilings__c = 'yes';
                opp1.Main_Panel_Size_Amps__c = '200';
                update opp1;
                }
            catch(Exception e){
                Boolean expectedExceptionThrown = e.getMessage().contains('Field can not be edited as Service Contract Event has been created')? true :false;
                //System.AssertEquals(expectedExceptionThrown, true);
            } 
      }
    
       Test.StopTest(); 
    } 
 
    
}