SFDCProject/src/objects/SR_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Signed__c</fullName>
        <label>Customer Signed</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Name_On_File_Server__c</fullName>
        <label>Document Name on File Server</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <label>Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Source__c</fullName>
        <label>Document Source</label>
        <picklist>
            <picklistValues>
                <fullName>Proposal Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual Upload</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eSign</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Folder_Name__c</fullName>
        <label>Folder Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>SR_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Proposal_Name__c</fullName>
        <label>Parent Proposal Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Signed__c</fullName>
        <label>Partner Signed</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SunRun_Signed__c</fullName>
        <label>SunRun Signed</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wet Signed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Wet_Sign_Status__c</fullName>
        <description>This Field used to Specify the status whether signature is required or not</description>
        <label>Wet Signature Status</label>
        <picklist>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SR Attachment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SR Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/SRAttachmentWrapper.cls
public class SRAttachmentWrapper {
    public SR_Attachment__C srAttachment{get;set;}
    public String partnerName {get;set;}
    public String partnerEmail {get;set;}
    public String partnerStatus {get;set;}
    
    public String primaryCustomerName {get;set;}
    public String primaryCustomerEmail {get;set;}
    public String primaryCustomerStatus {get;set;}

    public String secondaryCustomerName {get;set;}
    public String secondaryCustomerEmail {get;set;}
    public String secondaryCustomerStatus {get;set;}

    public String sunrunOperationName {get;set;}
    public String sunrunOperationEmail {get;set;}
    public String sunrunOperationStatus {get;set;}
    public Boolean readyForSubmission {get;set;}
    public Boolean signatureRequired {get;set;}
    
    public Boolean selected {
        get; 
        set{selected = value;}
    }
    public String signedURL {get;set;}
    public SRAttachmentWrapper(SR_Attachment__C srAttachmentObj)
    {
        sunrunOperationName = '';
        primaryCustomerName = '';
        secondaryCustomerName = '';
        partnerName = '';
        readyForSubmission = true;
        signatureRequired = true;
        
        srAttachment = srAttachmentObj;
        selected = false;
        if(srAttachment != null){
            String proxySettingName = SRAttachmentManager.getSunRunS3ProxySettingsName(srAttachmentObj, false);
            String proposalName = srAttachmentObj.Parent_Proposal_Name__c ;
            String fileName = (srAttachmentObj.Document_Name_On_File_Server__c == null 
                                || srAttachmentObj.Document_Name_On_File_Server__c == '') ? srAttachmentObj.Document_Name__c : srAttachmentObj.Document_Name_On_File_Server__c;
            if(srAttachmentObj.Document_Source__c == EDPUtil.PROPOSAL_TOOL_SOURCE){
                proposalName = SunRunS3RestConnection.getProposalNameForMasterDocs(proposalName);               
            }
            System.debug('proposalName: ' + proposalName);
            signedURL = SunRunS3RestConnection.getSignedURL('GET', proxySettingName, proposalName, fileName);
            if(srAttachmentObj.Wet_Sign_Status__c == EDPUtil.SIGNED){
                if(srAttachmentObj.Partner_Signed__c == EDPUtil.COMPLETED){
                    partnerStatus = srAttachmentObj.Partner_Signed__c; 
                }
                
                if(srAttachmentObj.Customer_Signed__c == EDPUtil.COMPLETED){
                    primaryCustomerStatus = srAttachmentObj.Customer_Signed__c; 
                }
            }
            
            if(srAttachmentObj != null && (srAttachmentObj.Wet_Sign_Status__c == EDPUtil.SIGNED 
                || srAttachmentObj.Wet_Sign_Status__c == EDPUtil.SR_COUNTERSIGNED)){
                sunrunOperationName = srAttachmentObj.SunRun_Signed__c;
                partnerName = srAttachmentObj.Partner_Signed__c;
                primaryCustomerName = srAttachmentObj.Customer_Signed__c;
                secondaryCustomerName = 'N/A';                  
            }
        }
    }
    
    public SRAttachmentWrapper(SR_Attachment__C srAttachmentObj,boolean IsOpportunity)
    {
        sunrunOperationName = '';
        primaryCustomerName = '';
        secondaryCustomerName = '';
        partnerName = '';
        readyForSubmission = true;
        signatureRequired = true;
        
        srAttachment = srAttachmentObj;
        selected = false;
        if(srAttachment != null){
            
            String proxySettingName;
            if(!String.isEmpty(srAttachmentObj.folder_name__c)){
            	proxySettingName = srAttachmentObj.folder_name__c;
            }else if(IsOpportunity){
                proxySettingName =  'Prospects';
            }else{
                proxySettingName = SRAttachmentManager.getSunRunS3ProxySettingsName(srAttachmentObj, false);
        	}
        	System.debug('srAttachmentObj1: ' + srAttachmentObj);
        	
            String proposalName = (String.isEmpty(srAttachmentObj.Parent_Proposal_Name__c)) ? srAttachmentObj.Opportunity__c + '' : srAttachmentObj.Parent_Proposal_Name__c;
            String fileName = (srAttachmentObj.Document_Name_On_File_Server__c == null 
                                || srAttachmentObj.Document_Name_On_File_Server__c == '') ? srAttachmentObj.Document_Name__c : srAttachmentObj.Document_Name_On_File_Server__c;
           
            System.debug('proposalName: ' + proposalName);
            signedURL = SunRunS3RestConnection.getSignedURL('GET', proxySettingName, proposalName, fileName);
            if(srAttachmentObj.Wet_Sign_Status__c == EDPUtil.SIGNED){
                if(srAttachmentObj.Partner_Signed__c == EDPUtil.COMPLETED){
                    partnerStatus = srAttachmentObj.Partner_Signed__c; 
                }
                
                if(srAttachmentObj.Customer_Signed__c == EDPUtil.COMPLETED){
                    primaryCustomerStatus = srAttachmentObj.Customer_Signed__c; 
                }
            }
            
            if(srAttachmentObj != null && (srAttachmentObj.Wet_Sign_Status__c == EDPUtil.SIGNED 
                || srAttachmentObj.Wet_Sign_Status__c == EDPUtil.SR_COUNTERSIGNED)){
                sunrunOperationName = srAttachmentObj.SunRun_Signed__c;
                partnerName = srAttachmentObj.Partner_Signed__c;
                primaryCustomerName = srAttachmentObj.Customer_Signed__c;
                secondaryCustomerName = 'N/A';                  
            }
        }
    }
    
}