SFDCProject/src/objects/Survey__c.object
<CustomObject>
    <description>Captures surveys info from clicktools or other survey tools</description>
    <fields>
        <fullName>Agreement_Number__c</fullName>
        <formula>Service_Contract__r.Agreement_Number__c</formula>
        <label>Agreement Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Answer_1__c</fullName>
        <label>Answer 1</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_2__c</fullName>
        <label>Answer 2</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_3__c</fullName>
        <label>Answer 3</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_4__c</fullName>
        <label>Answer 4</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_5__c</fullName>
        <label>Answer 5</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_6__c</fullName>
        <label>Answer 6</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_7__c</fullName>
        <label>Answer 7</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Answer_8__c</fullName>
        <label>Answer 8</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSAT_Survey_Response__c</fullName>
        <label>CSAT Survey Response</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <label>Question 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_2__c</fullName>
        <label>Question 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_3__c</fullName>
        <label>Question 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_4__c</fullName>
        <label>Question 4</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_5__c</fullName>
        <label>Question 5</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_6__c</fullName>
        <label>Question 6</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_7__c</fullName>
        <label>Question 7</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_8__c</fullName>
        <label>Question 8</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <label>Survey Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Sub_Type__c</fullName>
        <label>Survey Sub Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>Survey {00000000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_trg_survey_createcase.cls
@istest(seeAllData=true)
public with sharing class Test_trg_survey_createcase {
	public static testMethod void Test_trg_survey_createcase(){
		Test.starttest();
         Recordtype r=[select id from recordtype where sobjecttype='Case' and name='Survey' limit 1];
         Group Detractorid = [Select Id from Group where Name = 'Detractor Call Cases' and Type = 'Queue'];         
          Contact cont= new Contact (firstname='Test',LastName='TestCt');
          insert cont;
        ServiceContract sc = [Select id,agreement_number__c from ServiceContract where agreement_number__c !=null limit 1];
         Survey__c sy = new Survey__c (Contact__c=cont.id,CSAT_Survey_Response__c=3,Question_1__c='TestQ1',Question_2__c='TestQ2',Question_3__c='TestQ3',Question_4__c='TestQ4',Question_5__c='TestQ5',Question_6__c='TestQ6',Question_7__c='TestQ7',Question_8__c='TestQ8',
         Answer_1__c='TestA1',Answer_2__c='TestA2',Answer_3__c='TestA3',Answer_4__c='TestA4',Answer_5__c='TestA5',Answer_6__c='TestA6',Answer_7__c='TestA7',Answer_8__c='TestA8',Service_Contract__c=sc.id,Survey_Name__c='TestSurveyName',Survey_Sub_Type__c='TestSurveySubType');
         insert sy;
         Case c=new case ();
         c.Origin ='CSAT Survey';
         c.Service_Contract__c = sc.id;
         c.Survey__c =sy.id;
         c.Status = 'Open';
         c.Subject='Survey Detractor Callback';
         c.RecordTypeId = r.id;
         c.ContactId = cont.id;        
         insert c;
          Test.stoptest();
	}

}