SFDCProject/src/objects/Task__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <picklist>
            <picklistValues>
                <fullName>Branch Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brea PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drafting Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspection Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interconnection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Milestone Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NTP Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting/Design Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Planner/Brea PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Payment Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Change Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialist Team</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Workflow Task</label>
    <nameField>
        <label>Workflow Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflow Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDCProject/src/classes/wfTaskRedirect.cls
public class wfTaskRedirect {
	public string taskId ;
    private Boolean systemAdmin = false;
    private Task__c taskObj;
    private string baseUrl;
    public boolean showEditPage = false;
    public wfTaskRedirect(ApexPages.StandardController controller) {
		taskObj = (Task__c) controller.getRecord();
        if (taskId == null) {
            taskId = taskObj.Id;
        }
        initialize();
    }

    private void initialize(){
    	if(taskId != null){
    		taskObj = [Select Id,Task_Owner__c, Group_Name__c, status__c from Task__c where Id =: taskId];
    	}
		showEditPage = false;
    	Set<Id> userIds = new Set<Id>();
    	Id userId = UserInfo.getUserId();
    	userIds.add(userId);
		Map<Id, Set<String>> userGroupMap = wfUtil.getUserGroups(userIds);  	
		Set<String> userGroups = userGroupMap.get(userId);
		if(taskObj.status__c == wfUtil.OPEN  
			&& ((taskObj.Task_Owner__c == userId ) || (taskObj.Task_Owner__c == null && userGroups != null && userGroups.contains(taskObj.Group_Name__c)))){
			showEditPage = true;
		}
		baseUrl = EDPUtil.getBaseURL();
    }

    private String taskViewURL {
        get {
        	return baseUrl + '/apex/wfTask_View?id=' + taskId + '&retURL=%2F' + taskId + '&&sfdc.override=1';
        }
        set;
    }  

    private String taskEditURL {
        get {
            return baseUrl + '/apex/wfTask_Edit?id=' + taskId + '&retURL=%2F' + taskId + '&sfdc.override=1';
        }
        set;
    }

	public PageReference getWfTaskEditPage() {
        PageReference ref = null;
        System.debug('showEditPage: ' + showEditPage);
        System.debug('taskEditURL: ' + taskEditURL);
		System.debug('taskViewURL: ' + taskViewURL);
        if(showEditPage == true ){
            ref = new PageReference(taskEditURL);
            ref.setRedirect(true);      
        }else{
            ref = new PageReference(taskViewURL);
            ref.setRedirect(true);          
        }
        return ref;
    }

}