SFDCProject/src/objects/Territory__c.object
<CustomObject>
    <description>Captures territory information</description>
    <fields>
        <fullName>Zip_code__c</fullName>
        <description>Territory Zipcode</description>
        <label>Zip Codes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/objects/ZipUtility__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Branch__c</fullName>
        <label>Sales Branch</label>
        <picklist>
            <picklistValues>
                <fullName>Bakersfield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Bay Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fresno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inland Empire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Las Vegas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD - Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Jersey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North San Diego</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orange County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phoenix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prescott</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sacramento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Diego</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Luis Obispo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC Charleston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC Greenville</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Bay Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Carolina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Los Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ventura</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adirondack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frontier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genessee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I don&apos;t know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>J</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lanai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maui</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Molokai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mountain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <label>Utility Company</label>
        <picklist>
            <picklistValues>
                <fullName>ACE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alameda Municipal Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona Public Service Co</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ - Arizona Public Service (APS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ - Salt River Project Power (SRP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ - Tucson Electric Power (TEP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore Gas &amp; Electric Co</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banning Electric Utility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG&amp;E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burbank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Anaheim Public Utilities (APU)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Banning Power (BPC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Los Angeles Dept of Water &amp; Power (LADWP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Pacific Gas &amp; Electric (PG&amp;E)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Pasadena Water and Power (PWP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Sacramento Municipal Utility District (SMUD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - San Diego Gas &amp; Electric (SDG&amp;E)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA - Southern California Edison (SCE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Hudson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Hudson Gas &amp; Elec Corp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City of Palo Alto Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City of Pasadena</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City of Riverside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL&amp;P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colton Electric Utility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ConEdison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut Light &amp; Power Co</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated Edison Co-NY Inc</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>ZipUtility</label>
    <nameField>
        <displayFormat>Z-{0000}</displayFormat>
        <label>ZipUtility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZipUtility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDCProject/src/classes/Test_trg_opp_zip_to_utility.cls
@isTest(SeeAllData=true)
public with sharing class Test_trg_opp_zip_to_utility {
    
    static testmethod void method1(){
    ZipUtility__c zp=new ZipUtility__c(Territory__c='P',Zip_Code__c='00000',State__C='CA',Utility_Company__c='Pacific Gas and Electric (PG&E)',Sales_Branch__c='Bakersfield');
    List<ZipUtility__c> zpList=new List<ZipUtility__c>();
    zpList.add(zp);
    insert zp; 
    Account recAcc= new Account(name='SunRun',billingpostalcode='00000');
    insert recAcc;
    Opportunity opp = new Opportunity(Accountid=recAcc.id,Name='Test123',stagename='Closed Won',Closedate=system.today(),Sales_Branch__c='South Bay Area');
    insert opp;
    opp.Sales_Branch__c='Bakersfield';
    update opp;
    }

    static testmethod void method2(){
    ZipUtility__c zp=new ZipUtility__c(Territory__c='P',Zip_Code__c='00000',State__C='CA',Utility_Company__c='Pacific Gas and Electric (PG&E)',Sales_Branch__c='Bakersfield');
    List<ZipUtility__c> zpList=new List<ZipUtility__c>();
    zpList.add(zp);
    insert zp; 
    Account recAcc= new Account(name='SunRun',billingpostalcode='00000');
    insert recAcc;
    Lead newlead = new Lead(state='CA',city='San Francisco',street='123 street',postalcode='12345',lastname='Test',channel__c='Test',company='Home');
    insert newlead; 
    Opportunity opp = new Opportunity(Accountid=recAcc.id,lead_id__c=newlead.Id,Name='Test123',stagename='Closed Won',Closedate=system.today(),Sales_Branch__c='South Bay Area');
    insert opp;
    opp.Sales_Branch__c='Bakersfield';
    update opp;
    }
    
    static testmethod void method3(){
    ZipUtility__c zp=new ZipUtility__c(Territory__c='P',Zip_Code__c='00000',State__C='CA',Utility_Company__c='Pacific Gas and Electric (PG&E)',Sales_Branch__c='Bakersfield');
    List<ZipUtility__c> zpList=new List<ZipUtility__c>();
    zpList.add(zp);
    insert zp; 
    Account recAcc= new Account(name='SunRun',billingpostalcode='11111');
    insert recAcc;
    Lead newlead = new Lead(state='CA',city='San Francisco',street='123 street',postalcode='12345',lastname='Test',channel__c='Test',company='Home');
    insert newlead; 
    Opportunity opp = new Opportunity(Accountid=recAcc.id,lead_id__c=newlead.Id,Name='Test123',stagename='Closed Won',Closedate=system.today(),Sales_Branch__c='South Bay Area');
    insert opp;
    opp.Sales_Branch__c='Bakersfield';
    update opp;
    }
 }